// AUTO-GENERATED by pipeline/generate_founder_stories.py
// Each story is a COMPOSITE based on patterns across our agency clients.
// Names, locations, and figures have been anonymised; the tax mechanics are real.

export type FounderStory = {
  slug: string;
  title: string;
  topic: string;
  agency_type: string;
  stage: string;
  outcome: string;
  body: string;
};

export const STORIES: Record<string, FounderStory> = {
  "creative-agency-badr-exit": {
    slug: "creative-agency-badr-exit",
    title: "How a 7-Person Bristol Creative Agency Saved \u00a343k Restructuring Before a Trade Sale",
    topic: "BADR-eligible exit planning",
    agency_type: "Creative agency",
    stage: "Pre-exit",
    outcome: "Saved \u00a343k in CGT by restructuring 14 months before completion",
    body: `<em>Composite case study based on patterns across our agency clients. Names, locations and specific figures have been anonymised; the financial mechanics and tax treatment are real and reflect current UK rules.</em>

<h2>The situation</h2>
<p>A seven-person creative agency based in Bristol Harbourside, specialising in brand strategy and visual identity for B2B tech companies. The agency had been trading for nine years, with a solid reputation and a loyal client base that included three long-term retainers. Revenue had grown steadily to £1.2m in the last financial year, with net profits of £210,000. The two founding directors, both in their early 40s, owned 60% and 40% of the shares respectively. They had built the business from scratch, working from a shared desk in a co-working space to a leasehold studio overlooking the water.</p>
<p>The founders had received an unsolicited offer from a mid-sized international agency group looking to expand its UK footprint. The offer was for 100% of the shares, with a total consideration of £1.8m, structured as £1.4m cash on completion and £400,000 in earn-out over two years. The deal was attractive, but the founders were worried about the tax bill. They had never taken formal advice on exit planning and had always assumed they would simply sell their shares and pay Capital Gains Tax at the standard rate.</p>

<h2>The decision</h2>
<p>The founders came to us with a straightforward question: "How much tax will we pay, and is there anything we can do about it?" They had heard about Business Asset Disposal Relief (BADR) but didn't know if they qualified, or what steps they needed to take. The offer had been made in early March 2025, and the buyer wanted to complete by the end of June 2026. That gave us roughly 14 months to restructure the business in a way that would maximise the available reliefs.</p>
<p>We ran an initial diagnostic. The agency was trading as a limited company, with the shares held directly by the two founders. Both had been directors and employees for the full nine years. The business met the trading condition for BADR, over 80% of its income came from qualifying trading activities. The problem was that the company had accumulated a significant cash reserve of £280,000, built up over the years from retained profits. That cash was sitting in a business bank account, earning minimal interest. Under BADR rules, if a company has more than 20% of its assets as non-trading (i.e. cash or investments), the relief can be restricted. In this case, the cash represented roughly 22% of total assets, just over the threshold.</p>

<h2>What we modelled</h2>
<p>We built three scenarios in our financial model, using real numbers from the agency's management accounts and tax returns.</p>
<p><strong>Scenario A: Do nothing.</strong> Sell the shares as-is. The total gain would be £1.8m minus the original subscription cost of £2,000 (negligible). Each founder would pay CGT at 24% (the higher rate for 2026/27) on their share of the gain. Total tax: approximately £432,000. That was the baseline.</p>
<p><strong>Scenario B: Restructure to qualify for BADR.</strong> This meant reducing the non-trading cash to below 20% of total assets, and ensuring both founders held their shares for at least two years before the sale. The two-year holding period was already met, they had held shares since incorporation. The cash issue was the main blocker. We modelled two sub-options:</p>
<ul>
<li><strong>Option B1:</strong> Pay out the excess cash as dividends before the sale. This would reduce the cash reserve to £180,000, bringing non-trading assets to 18% of the total. The dividends would be taxed at the shareholders' marginal dividend rates (10.75% for basic rate, 35.75% for higher rate, 39.35% for additional rate). For the two founders, both higher-rate taxpayers, the tax on a £100,000 dividend would be £33,750 each. Total dividend tax: £67,500. But the gain on the sale would then qualify for BADR at 14% on the first £1m of gains per person. Total CGT: £252,000. Combined tax: £319,500.</li>
<li><strong>Option B2:</strong> Invest the excess cash into qualifying business assets, new equipment, software, or a pension contribution for the directors. This would convert non-trading cash into trading assets, keeping the balance sheet clean. We modelled a £100,000 investment in new Mac workstations, a server upgrade, and a contribution to a director's SIPP. This would reduce the cash to £180,000, achieving the same 18% ratio. No dividend tax, but the investment would reduce the company's net assets slightly. Total CGT: £252,000. No additional tax on the investment.</li>
</ul>
<p><strong>Scenario C: Partial claim.</strong> If the cash couldn't be fully addressed, we could claim BADR on the trading element of the gain only. This would be messy and likely challenged by HMRC. We advised against it.</p>

<h2>The outcome</h2>
<p>The founders chose Option B2. They invested £100,000 into new equipment (Macs, monitors, a server, and a high-end colour calibration system) and contributed £40,000 into a SIPP for one director who had low pension savings. The remaining £40,000 was used to pay down a small director's loan account, further cleaning the balance sheet. The restructuring was completed by August 2025, well within the 14-month window.</p>
<p>The sale completed in June 2026 as planned. Each founder claimed BADR on their share of the gain, paying the 18% BADR rate that applies to disposals from 6 April 2026. Total CGT bill: £324,000. Compared to the baseline of £432,000 with no BADR, they saved £108,000 in tax (£54,000 each). After accounting for the £40,000 pension contribution (which reduced corporation tax by £7,600 at 19%), the net saving was approximately £115,600.</p>
<p>The agency continued to trade under the new ownership, with the founders staying on as creative directors for the earn-out period. The new equipment and pension contribution were seen as sensible investments that also served the business post-sale.</p>

<h2>What others can learn</h2>
<ul>
<li><strong>Check your balance sheet early.</strong> BADR is generous, but the 20% non-trading asset rule catches many agency owners who have built up cash reserves. If you're planning an exit, review your balance sheet at least 18 months before the sale. A simple dividend or investment can fix the ratio.</li>
<li><strong>Pension contributions are a double win.</strong> Paying into a director's SIPP reduces corporation tax, lowers non-trading assets, and builds retirement savings. It's one of the most tax-efficient ways to clean up a balance sheet before a sale.</li>
<li><strong>Don't assume you qualify automatically.</strong> Even if you've held shares for two years and the business is trading, small details like cash levels or a property held in the company can disqualify you. Always get a formal review before signing a heads of terms.</li>
<li><strong>Timing is everything.</strong> The restructuring must be completed at least two years before the sale (for shares held at that point) and the non-trading asset test must be met at the time of sale. Starting 14 months out gave this agency enough time to act without rushing.</li>
<li><strong>Earn-out structures need care.</strong> The £400,000 earn-out in this deal was structured as deferred consideration, not as employment income. That meant it qualified for BADR too, as long as the shares were held for the earn-out period. If the earn-out had been structured as a consultancy fee, it would have been taxed as income at 45%. Always negotiate the earn-out structure with tax in mind.</li>
</ul>`,
  },
  "digital-agency-incorporation-mid-year": {
    slug: "digital-agency-incorporation-mid-year",
    title: "Sole Trader to Ltd Mid-Year: Why a \u00a3180k Digital Agency Did It in October",
    topic: "Mid-year incorporation timing",
    agency_type: "Digital agency",
    stage: "Early scaling",
    outcome: "\u00a311k tax saving in first 12 months of operating as Ltd",
    body: `<em>Composite case study based on patterns across our agency clients. Names, locations and specific figures have been anonymised; the financial mechanics and tax treatment are real and reflect current UK rules.</em>

<h2>The situation</h2>

<p>In early 2024, a digital agency founder we’ll call Tom was running a successful solo operation from a co-working space in Shoreditch. His agency specialised in Klaviyo email automation and Shopify conversion optimisation for DTC brands. By September, his revenue was on track to hit £180,000 for the tax year, a figure that had crept up from £95,000 the previous year, and £62,000 the year before that.</p>

<p>Tom was a sole trader, using FreeAgent for bookkeeping and Float for cash flow forecasting. He had one part-time VA and two freelance copywriters on retainers. His clients were mostly UK-based, with one US brand paying in dollars. He was profitable, cash-rich, and growing fast, but his accountant had been gently nudging him for months: “You need to think about incorporating.”</p>

<p>The problem was timing. Tom had always assumed you incorporated at the start of a tax year, April 6th, to keep things simple. But his accountant explained that mid-year incorporation was not only possible, but often more tax-efficient when you were crossing the £100k–£200k profit threshold. By late September 2024, Tom had already earned £140,000 in net profit as a sole trader. The remaining £40,000 of projected earnings for the year would fall into the new company.</p>

<p>Tom’s personal tax position was straightforward: single, no children, renting in London, no other income. His only significant tax planning concern was that his sole trader profits were pushing him into the 40% income tax bracket, and he was paying 9% Class 4 NIC on top. He felt the sting every time he filed his self-assessment.</p>

<h2>The decision</h2>

<p>Tom’s core question was simple: <strong>Should he incorporate on 1 October 2024, or wait until April 2025?</strong></p>

<p>He had three concerns:</p>
<ul>
<li>Would the administrative hassle of a mid-year switch be worth the tax saving?</li>
<li>Could he legally transfer ongoing client contracts and work-in-progress to the new company without triggering a VAT or income tax issue?</li>
<li>Would the timing affect his ability to claim Entrepreneurs’ Relief (now Business Asset Disposal Relief) on a future sale?</li>
</ul>

<p>His accountant ran the numbers on three scenarios: incorporate in October 2024, incorporate in April 2025, or stay as a sole trader for another full year. The answer was clear, but only if Tom was willing to act before the end of the calendar year.</p>

<h2>What we modelled</h2>

<p>We built a cash-flow model in Excel, using Tom’s actual September 2024 year-to-date figures and his projected pipeline for the next 12 months. The key assumptions were:</p>

<ul>
<li><strong>Sole trader profit (April–September 2024):</strong> £140,000</li>
<li><strong>Projected profit (October 2024–March 2025):</strong> £40,000</li>
<li><strong>Projected profit (April 2025–March 2026):</strong> £200,000 (full first year as Ltd)</li>
<li><strong>Tom’s salary:</strong> £12,570 per year (personal allowance) from the Ltd company</li>
<li><strong>Dividends:</strong> drawn quarterly, targeting basic rate band</li>
</ul>

<p><strong>Scenario A: Incorporate 1 October 2024</strong></p>
<p>Tom would pay income tax and Class 4 NIC on the £140,000 sole trader profit at his marginal rate (40% + 9% = 49% on most of it). That gave a sole trader tax bill of roughly £56,000. The new company would pay 19% corporation tax on its first £40,000 of profit (£7,600). Tom would take a £12,570 salary (no employer NIC due below secondary threshold) and draw dividends up to the basic rate band. Total tax for the 12 months to September 2025: approximately £67,000.</p>

<p><strong>Scenario B: Incorporate 6 April 2025</strong></p>
<p>Tom would pay income tax and NIC on the full £180,000 sole trader profit for 2024/25, a tax bill of roughly £74,000. The company would then start fresh in April 2025, paying 19% CT on its first £50,000 of profit, then 25% on the rest. Total tax for the 12 months to March 2026: approximately £82,000.</p>

<p><strong>Scenario C: Stay sole trader</strong></p>
<p>Tom would pay income tax and NIC on £180,000 for 2024/25, then on a projected £220,000 for 2026/27. Total two-year tax bill: roughly £168,000. No corporation tax, no dividend tax, but also no ability to retain profits in the company for future investment.</p>

<p>The October incorporation saved Tom approximately <strong>£11,000</strong> in the first 12 months compared to waiting until April. The saving came from three sources: lower corporation tax on the first £40,000 of profit (19% vs 49% personal rate), the ability to use the personal allowance twice in one tax year (once as a sole trader, once as a director), and the dividend allowance (£500) being available to the company.</p>

<h2>The outcome</h2>

<p>Tom incorporated on 1 October 2024. The process took four working days via Companies House and his accountant’s formation service. He opened a business bank account with Starling, transferred his FreeAgent subscription to the company, and novated his key client contracts with a simple letter of assignment.</p>

<p>The VAT registration was a minor headache, Tom had been below the £90,000 threshold as a sole trader, but the company’s projected turnover meant he registered for VAT from day one. He opted for the Flat Rate Scheme at 16.5% (limited cost trader) to simplify things.</p>

<p>By March 2025, the company had turned over £210,000 (the £40,000 projection was conservative, he won two new retainers in November). Corporation tax for the first six months came to £7,980. Tom paid himself the £12,570 salary and took £37,700 in dividends (staying within the basic rate band). His personal tax liability for 2024/25 was £56,000 on the sole trader portion, plus £2,300 in dividend tax, a total of £58,300.</p>

<p>Compared to Scenario B (incorporating in April), Tom saved £11,200 in tax and NIC in the first 12 months. He also retained £38,000 of profit in the company, which he used to hire a full-time junior developer in January 2025, something he couldn’t have done as a sole trader without taking on personal debt.</p>

<p>One unexpected benefit: the company structure made it easier to onboard the US client, who preferred invoicing a Ltd company over a sole trader. Tom also found that applying for a business credit card (Capital On Tap) was straightforward with the company’s strong early revenue.</p>

<h2>What others can learn</h2>

<ul>
<li><strong>Mid-year incorporation is often more tax-efficient than waiting for April.</strong> If your sole trader profits are pushing you into the 40% or 45% bracket, incorporating mid-year lets you divert future earnings into a company where they’re taxed at 19% or 25%, and you can use your personal allowance twice in one tax year.</li>
<li><strong>The £90,000 VAT threshold is a trigger point, not a barrier.</strong> If your company’s projected turnover exceeds £90,000 in its first 12 months, you must register for VAT from day one. Factor this into your pricing, either absorb the VAT or adjust your rates.</li>
<li><strong>Novation of contracts is straightforward if done properly.</strong> A simple letter signed by you, your client, and the new company is usually enough. Most clients don’t mind, they’re invoicing a company instead of an individual, which often feels more professional.</li>
<li><strong>Don’t forget the dividend allowance.</strong> It’s only £500 for 2026/27, but if you time your first dividend payment correctly, you can use it in two different tax years, once as a sole trader drawing profits, and once as a company director.</li>
<li><strong>Business Asset Disposal Relief (BADR) clock starts on incorporation.</strong> If you plan to sell the agency in future, the 14% CGT rate (2026/27) requires you to have held the shares for at least two years. Incorporating earlier starts that clock ticking, another reason not to wait.</li>
</ul>`,
  },
  "ppc-agency-rd-credit-first-claim": {
    slug: "ppc-agency-rd-credit-first-claim",
    title: "First-Time R&D Claim: How a 5-Person PPC Agency Recovered \u00a362k",
    topic: "R&D tax credit eligibility for performance marketing",
    agency_type: "PPC agency",
    stage: "Growth (\u00a3800k-1.5m)",
    outcome: "\u00a362k R&D credit on first claim, \u00a391k expected in year 2",
    body: `<em>Composite case study based on patterns across our agency clients. Names, locations and specific figures have been anonymised; the financial mechanics and tax treatment are real and reflect current UK rules.</em>

<h2>The situation</h2>
<p>In early 2025, a five-person PPC agency based in Manchester’s Northern Quarter approached us. They’d been trading for four years, specialising in paid search and paid social for e-commerce brands. Revenue had grown from £320,000 in year one to £1.1 million in their most recent financial year. Their client list included a mix of Shopify stores and Klaviyo-driven email campaigns, and they used Xero for bookkeeping, Float for cash flow forecasting, and a suite of Google Ads and Meta Ads tools.</p>
<p>The agency was profitable, net profit around £180,000, but the directors were frustrated. They’d heard about R&D tax credits but assumed they were only for tech startups building software, not for a service business running ad campaigns. Their accountant at the time had dismissed the idea, saying “PPC isn’t R&D.”</p>
<p>They came to us after a referral from another agency founder who’d successfully claimed. Their question was simple: “Can we really claim for what we do every day?”</p>

<h2>The decision</h2>
<p>The directors needed to decide whether to invest time and money in preparing a first-time R&D claim. The process would require digging through two years of project notes, client emails, and campaign data. They also needed to understand the risk, HMRC’s R&D rules are strict, and a failed claim could trigger an enquiry.</p>
<p>Specifically, they wanted to know:</p>
<ul>
<li>Which projects qualified as R&D under the current rules</li>
<li>How to calculate the eligible costs (staff time, software, subcontractors)</li>
<li>Whether the claim would be worth the effort, they’d heard figures of £20,000–£50,000 but had no benchmark</li>
<li>How to structure future projects to maximise claims in year two and beyond</li>
</ul>

<h2>What we modelled</h2>
<p>We started by reviewing their project pipeline for the last two financial years. The agency had worked on 14 major campaigns, but only six involved genuine technical uncertainty, the legal test for R&D. The others were standard optimisation work: adjusting bids, testing ad copy, or scaling budgets.</p>
<p>The six qualifying projects all involved developing new bidding algorithms, custom attribution models, or automated reporting systems. For example:</p>
<ul>
<li>Building a machine learning model to predict ROAS across 12 client accounts, using historical data from Google Ads and Klaviyo. The team spent three months iterating on the model because off-the-shelf tools couldn’t handle the multi-channel complexity.</li>
<li>Creating a proprietary dashboard that pulled real-time data from Meta Ads, Google Ads, and Shopify into a single view, solving a data integration problem that no existing tool (including Supermetrics) could address without heavy customisation.</li>
<li>Developing a script to automate A/B testing of landing pages across 40+ campaigns, which required writing custom JavaScript and working with their developers to handle API rate limits.</li>
</ul>
<p>We modelled two scenarios:</p>
<p><strong>Scenario A: Claim for year one only (2023/24)</strong><br>
Eligible costs: £145,000 (staff time: £98,000; software licences: £22,000; subcontractor costs: £25,000). Under the R&D SME scheme, the enhanced expenditure (130% uplift) gave a total qualifying spend of £333,500. At 19% corporation tax rate (they were under the £250,000 profit threshold for the small profits rate), the payable credit was £63,365. After accounting for the surrender of losses and the notional tax calculation, the net benefit was £62,000.</p>
<p><strong>Scenario B: Claim for year one and year two together (2023/24 and 2024/25)</strong><br>
Year two eligible costs were higher at £210,000, reflecting more staff time and a new subcontractor. The combined claim would be worth approximately £91,000 in year two alone (using 2024/25 rates), plus the £62,000 from year one, total £153,000. However, this would require more documentation and a longer HMRC review period.</p>
<p>We also modelled the impact on their corporation tax bill. Without the claim, they’d pay £34,200 in tax on £180,000 profit. With the claim, they’d receive a cash refund of £62,000, effectively turning a tax liability into a cash injection.</p>

<h2>The outcome</h2>
<p>The directors chose Scenario A, claiming for year one only, with a view to filing year two separately. They wanted to test the process with a smaller claim before committing to a larger one. The claim was prepared over six weeks, with our team working alongside their lead strategist to document the technical uncertainties, the methods used, and the outcomes.</p>
<p>The claim was submitted in May 2025. HMRC processed it in nine weeks, faster than the typical 12–16 weeks, and the £62,000 landed in the agency’s business account in July 2025. The directors used the cash to hire a junior data analyst, upgrade their reporting stack, and pay down a £15,000 overdraft.</p>
<p>For year two, they’ve already structured their projects to maximise eligibility. They’re now tracking staff time on R&D projects using a dedicated code in FreeAgent, and they’ve hired a part-time developer to handle the technical work. Their expected claim for 2024/25 is £91,000, and they’re planning to claim annually going forward.</p>
<p>The agency’s net profit margin improved from 16% to 22% after the first claim, and the cash injection gave them the confidence to pitch for larger clients. They’ve since won two £200,000+ retainers.</p>

<h2>What others can learn</h2>
<ul>
<li><strong>PPC work can qualify as R&D if it involves technical uncertainty.</strong> Standard campaign management doesn’t count, but developing new algorithms, custom integrations, or automated systems that solve a genuine technical problem does. The key is whether you had to overcome uncertainty that a competent professional in your field couldn’t resolve without experimentation.</li>
<li><strong>Documentation is everything.</strong> HMRC expects to see contemporaneous records: project briefs, meeting notes, test results, and time logs. The agency had Slack threads and Trello boards that proved invaluable. If you’re not documenting your R&D work as you go, start now.</li>
<li><strong>The first claim is the hardest, but it sets the template.</strong> Expect to spend 4–8 weeks gathering evidence for a first claim. Once you have a methodology, subsequent years are much faster, the agency’s year two claim took three weeks to prepare.</li>
<li><strong>Don’t let your accountant dismiss the idea without a proper review.</strong> Many general practice accountants don’t understand R&D in a services context. Work with a specialist who knows the HMRC guidelines for software and digital projects.</li>
<li><strong>Cash from R&D credits can transform your growth trajectory.</strong> £62,000 on £1.1 million revenue is a 5.6% boost, enough to hire a key person, invest in tools, or reduce debt. For a five-person agency, that’s a material difference.</li>
</ul>`,
  },
  "recruitment-agency-ir35-mass-determination": {
    slug: "recruitment-agency-ir35-mass-determination",
    title: "IR35 Mass Determination: A Recruitment Agency's 90-Day Compliance Sprint",
    topic: "Recruitment agency IR35 mass determination",
    agency_type: "Recruitment agency",
    stage: "Established",
    outcome: "Compliance achieved before HMRC enquiry window, zero reclassification challenges",
    body: `<em>Composite case study based on patterns across our agency clients. Names, locations and specific figures have been anonymised; the financial mechanics and tax treatment are real and reflect current UK rules.</em>

<h2>The situation</h2>
<p>By early 2025, a Manchester-based recruitment agency with 40 staff and a turnover of £18m had built a strong reputation placing senior contractors into financial services, tech and engineering roles across the North West and London. The agency operated from a converted warehouse in the Northern Quarter, with a satellite office in Leeds Holbeck. Most of its 200+ active contractors worked through their own limited companies, and the agency had historically treated all engagements as outside IR35.</p>
<p>Then the landscape shifted. HMRC had been running targeted IR35 compliance campaigns in the recruitment sector since 2023, and the agency's directors knew they were a prime candidate for an enquiry. Their largest client, a London-based fintech, had already announced it would conduct its own IR35 status determinations for all contractors starting in April 2025. The agency had 90 days to assess every single contractor placement across all clients, or face the risk of retrospective tax bills, penalties and reputational damage.</p>
<p>The directors had never formally documented their IR35 decision-making process. They relied on verbal agreements and standard contracts that didn't reflect the actual working practices of each engagement. A single HMRC enquiry could easily reclassify 30-40 contractors as inside IR35, triggering a liability for unpaid PAYE, National Insurance and interest stretching back six years. The potential exposure was north of £2m.</p>

<h2>The decision</h2>
<p>The agency needed a mass determination process that could assess every active contractor placement within 90 days, produce defensible status determination statements, and flag any engagements that clearly fell inside IR35. They also needed a clear plan for what to do with contractors who were reclassified: would the agency move them onto an umbrella company, offer a fixed-term employment contract, or simply stop working with them?</p>
<p>The directors had three core questions:</p>
<ul>
<li>How do we assess 200+ placements quickly without relying on guesswork?</li>
<li>What happens to contractors who are reclassified mid-contract?</li>
<li>How do we protect the agency if a client disagrees with our determination?</li>
</ul>

<h2>What we modelled</h2>
<p>We ran three scenarios with the agency's finance director and compliance lead. Each scenario assumed a 90-day implementation window and used real contractor data from the agency's Xero and FreeAgent records.</p>
<p><strong>Scenario A: Full external IR35 assessment firm.</strong> The agency would hire a specialist IR35 consultancy to assess every placement individually. Cost: £150-£200 per contractor, plus a £5,000 setup fee. Total: £35,000-£45,000. Timeline: 12-16 weeks, which was too slow. The agency would miss the client's April deadline.</p>
<p><strong>Scenario B: In-house assessment using HMRC's Check Employment Status for Tax (CEST) tool.</strong> The agency would train two staff members to use CEST and run assessments themselves. Cost: minimal software cost, plus two days of training at £800 per person. Total: £1,600 plus staff time. Timeline: 6-8 weeks. The risk: CEST has a high rate of "undetermined" results, especially for complex financial services roles. The agency could end up with 40% of assessments unresolved.</p>
<p><strong>Scenario C: Hybrid approach, in-house triage using CEST plus external review for complex cases.</strong> The agency would run all 200+ placements through CEST first. Any "undetermined" or borderline results would be sent to a specialist IR35 solicitor for a written opinion. Cost: £1,600 for training, plus £250-£400 per complex case. Estimated 40-50 complex cases. Total: £11,600-£21,600. Timeline: 8-10 weeks. This was the only scenario that met the deadline and kept costs under control.</p>
<p>We also modelled the financial impact of reclassification. If 30 contractors were moved inside IR35, the agency would need to deduct employer's National Insurance at 15% and apprenticeship levy at 0.5% on top of the contractor's fee. The contractors would see their net income drop by roughly 12-15%. The agency would need to renegotiate rates with clients to absorb some of the cost, or risk losing contractors to competitors who offered better terms.</p>

<h2>The outcome</h2>
<p>The agency chose Scenario C. They trained two compliance staff on CEST in early January 2025, then ran all 200+ active placements through the tool over three weeks. The results were sobering: 62 placements came back as "undetermined," and another 18 were flagged as "inside IR35." The remaining 120 were assessed as "outside IR35" with a reasonable degree of confidence.</p>
<p>The 80 problematic cases were sent to a specialist IR35 solicitor in London, who reviewed the actual contracts, working practices and client relationships. After four weeks, the solicitor confirmed that 45 of the 62 "undetermined" cases were genuinely outside IR35, but 17 were inside. Combined with the 18 already flagged, the agency had 35 contractors who needed to be reclassified.</p>
<p>The agency then had difficult conversations with those 35 contractors. They offered two options: move onto an umbrella company arrangement (where the agency would handle PAYE and NI deductions), or accept a fixed-term employment contract with the agency itself. 28 contractors chose the umbrella route; 7 left the agency altogether. The agency also renegotiated rates with the fintech client, securing a 5% uplift on all inside-IR35 placements to offset the additional employer costs.</p>
<p>By the end of March 2025, the agency had issued status determination statements for every single placement. The total cost was £18,400, well within budget. The fintech client accepted all determinations without challenge. HMRC has not opened an enquiry as of September 2025, and the agency now runs quarterly IR35 reviews as standard practice.</p>

<h2>What others can learn</h2>
<ul>
<li><strong>Start early, even if you think you're low-risk.</strong> The 90-day window felt tight, but it would have been impossible if the agency had waited until HMRC came knocking. Any agency with 50+ contractors should run a mass determination at least once a year.</li>
<li><strong>CEST is a useful triage tool, not a definitive answer.</strong> It works well for simple, standardised roles, but it struggles with senior contractors who have genuine control over their work. Budget for external review on at least 20-30% of your placements.</li>
<li><strong>Reclassification is a commercial problem, not just a tax problem.</strong> Contractors will push back, and some will leave. Have a clear offer ready, umbrella company, fixed-term contract, or rate renegotiation, before you start the process.</li>
<li><strong>Document everything.</strong> The agency now keeps a digital file for every contractor with the CEST output, the solicitor's opinion, the signed status determination statement, and a record of the contractor's response. If HMRC ever does open an enquiry, they can produce a defensible paper trail within hours.</li>
<li><strong>Clients will appreciate proactive compliance.</strong> The fintech client was impressed that the agency had done the work before being asked. It strengthened the relationship and led to a larger contract in Q2 2025.</li>
</ul>`,
  },
  "pr-agency-holding-company-investor-prep": {
    slug: "pr-agency-holding-company-investor-prep",
    title: "A 12-Person London PR Agency Setting Up a Holding Company Before Series A",
    topic: "Holding company structure for investor preparation",
    agency_type: "PR agency",
    stage: "Pre-investment",
    outcome: "Clean cap table ready in 8 weeks, founder retained CGT efficiency",
    body: `<em>Composite case study based on patterns across our agency clients. Names, locations and specific figures have been anonymised; the financial mechanics and tax treatment are real and reflect current UK rules.</em>

<h2>The situation</h2>
<p>A 12-person PR agency based in Shoreditch, London, specialising in B2B tech and fintech clients. The agency had grown steadily over five years, reaching £2.8m in annual recurring revenue with a 22% EBITDA margin. The founder, a former journalist, owned 100% of the ordinary shares. The business had always been run as a straightforward limited company, with no holding structure, no group entities, and a single trading subsidiary.</p>
<p>In early 2025, the founder began exploratory conversations with a growth equity firm that specialised in professional services. The investor was interested in a £1.5m Series A round for a 20% stake, valuing the agency at £7.5m post-money. The term sheet was promising, but the investor’s legal team flagged a structural issue: the agency’s single-company setup would make it difficult to ring-fence IP, separate the founder’s personal assets, and offer future equity incentives to senior staff without creating a messy cap table.</p>

<h2>The decision</h2>
<p>The founder needed to decide whether to restructure the agency into a holding company structure before accepting the investment. The investor made it clear they would prefer a clean parent-subsidiary arrangement, with the holding company holding the shares of the trading company and any future subsidiaries. The founder’s core concerns were:</p>
<ul>
<li>Preserving the ability to sell shares in the future under Business Asset Disposal Relief (BADR) at 18% CGT (the rate from 6 April 2026), rather than the higher 24% rate for non-qualifying disposals.</li>
<li>Ensuring the holding company could issue share options to key employees without diluting the founder’s personal stake in the trading company.</li>
<li>Avoiding a tax charge on the transfer of the trading company’s shares to the new holding company.</li>
<li>Getting the structure in place within 8 weeks to meet the investor’s due diligence timeline.</li>
</ul>

<h2>What we modelled</h2>
<p>We modelled three options for the founder, using 2026/27 UK tax rates and reliefs:</p>
<p><strong>Option 1: Do nothing – remain as a single limited company.</strong> The investor would take 20% of the trading company directly. The founder’s remaining 80% would be worth £6m on paper. Future share options for staff would be issued from the same company, diluting the founder’s stake. On a future exit, the founder would pay 24% CGT on gains above the annual exempt amount (£3,000), unless they qualified for BADR – which would require meeting the 5% holding and 2-year ownership conditions at the time of sale. The investor’s legal team had already indicated they would require a separate IP holding entity, which would add complexity later.</p>
<p><strong>Option 2: Share-for-share exchange into a holding company (Section 135 TCGA 1992).</strong> The founder would exchange their shares in the trading company for shares in a new holding company. This would be a tax-neutral transaction, meaning no immediate CGT charge. The holding company would then own 100% of the trading company. The investor would subscribe for shares in the holding company, not the trading company. This kept the cap table clean and allowed the holding company to issue EMI share options to staff. The founder’s shares in the holding company would qualify for BADR on a future sale, provided they met the 2-year holding period and 5% economic interest test. The downside: legal and accounting fees of £12,000–£15,000, plus 6–8 weeks of work.</p>
<p><strong>Option 3: Holding company with a separate IP company.</strong> A variant of Option 2, where the founder also transferred the agency’s brand trademarks and proprietary media monitoring software into a separate IP holding company, owned by the holding company. This would allow the trading company to pay a royalty to the IP company, reducing corporation tax in the trading company (from 25% to 19% on the royalty income, after the IP company’s own costs). The investor was comfortable with this, as it protected the IP from any future trading liabilities. The extra cost: £5,000–£8,000 for IP valuation and legal work, plus 2 more weeks.</p>

<h2>The outcome</h2>
<p>The founder chose Option 3. The share-for-share exchange was completed in 7 weeks, just ahead of the investor’s deadline. The holding company (PR Group Ltd) was incorporated, and the founder received 100% of its shares in exchange for their shares in the trading company (PR Agency Ltd). The IP company (PR IP Ltd) was set up as a wholly-owned subsidiary of the holding company, and the trademarks and software were transferred to it at market value, with a deferred tax election to avoid an immediate CGT charge.</p>
<p>The investor subscribed for £1.5m of new shares in the holding company, giving them 20% of the group. The founder retained 80% of the holding company, which in turn owned 100% of the trading company and 100% of the IP company. The cap table was clean: three entities, one holding company, one investor, one founder.</p>
<p>The financial result: the founder’s effective tax rate on a future exit would be 18% under BADR (the rate from 6 April 2026), rather than 24% – a saving of £60,000 on every £1m of gain above the annual exempt amount. The IP company’s royalty income was taxed at 19% corporation tax, compared to the 25% the trading company would have paid on the same profits, saving approximately £12,000 per year in tax. The total cost of the restructuring was £19,000, which was fully deductible against the holding company’s future corporation tax.</p>
<p>The agency continued to trade profitably, and the investor’s due diligence was completed without any structural issues. The founder reported that the clean cap table made it easier to recruit a finance director and a head of growth, both of whom received EMI share options in the holding company.</p>

<h2>What others can learn</h2>
<ul>
<li><strong>Restructure before you raise, not after.</strong> Investors prefer a clean holding company structure from day one. Trying to reorganise after a term sheet is signed can delay the round and create tax complications. Start the process at least 8 weeks before you expect to accept investment.</li>
<li><strong>Share-for-share exchanges are tax-neutral if done correctly.</strong> Section 135 of TCGA 1992 allows you to swap your trading company shares for holding company shares without triggering a CGT charge. Get professional advice to ensure the exchange meets HMRC’s clearance requirements – we submitted a clearance application and received confirmation in 4 weeks.</li>
<li><strong>BADR is worth protecting.</strong> The difference between 14% and 24% CGT is significant. A holding company structure preserves your ability to claim BADR on a future sale, provided you hold at least 5% of the shares and meet the 2-year qualifying period. If you sell within 2 years of the restructuring, you may lose BADR on that portion of the gain.</li>
<li><strong>Separate IP from trading risk.</strong> If your agency owns valuable trademarks, software, or methodologies, consider putting them in a separate IP company. This protects the IP from any future trading liabilities and can reduce your group’s overall corporation tax bill through royalty payments.</li>
<li><strong>Budget for professional fees.</strong> A holding company restructuring typically costs £12,000–£20,000 in legal and accounting fees, plus 6–8 weeks of time. This is a small price to pay for a clean cap table and significant future tax savings. The fees are tax-deductible against the holding company’s future profits.</li>
</ul>`,
  },
  "marketing-agency-retainer-to-project-cash-flow": {
    slug: "marketing-agency-retainer-to-project-cash-flow",
    title: "From Retainer to Project Billing: A 15-Person Marketing Agency's Cash Flow Cliff (and How They Fixed It)",
    topic: "Cash flow management when shifting revenue model",
    agency_type: "Marketing agency",
    stage: "Growth",
    outcome: "Cash position stabilised in 4 months, returned to 60-day buffer",
    body: `<em>Composite case study based on patterns across our agency clients. Names, locations and specific figures have been anonymised; the financial mechanics and tax treatment are real and reflect current UK rules.</em>

<h2>The situation</h2>

<p>When we first met the founders of a 15-person marketing agency based in Manchester's Northern Quarter, they were running a business that looked healthy on paper. Revenue had grown from £850,000 to £1.2 million in two years. They specialised in performance marketing for ecommerce brands, with a strong roster of clients using Klaviyo, Shopify and Google Ads. The team was young, ambitious, and the founders had built a reputation for delivering measurable results.</p>

<p>But the founders were stressed. Their bank balance was swinging wildly. Some months they had £80,000 in the account; others they were scraping to make payroll. The problem was their revenue model: they had moved from a mix of retainers and project work to almost entirely project-based billing. The shift had been driven by client demand, brands wanted fixed-scope campaigns, not ongoing retainers. But the cash flow consequences were brutal.</p>

<p>Retainers had given them predictable monthly income of around £70,000. Projects brought in larger invoices, typically £15,000 to £40,000, but with long payment terms. Their average debtor days had stretched from 28 to 62. They were winning more work, but the cash wasn't arriving fast enough to cover wages, rent on their Northern Quarter office, and the £25,000 monthly payroll.</p>

<p>The founders had tried factoring invoices through a finance company, but the fees were eating into margins. They'd also taken a £50,000 overdraft facility, which they were using almost every month. The interest was manageable, but the psychological toll was real.</p>

<h2>The decision</h2>

<p>The founders came to us with a single question: "Should we go back to retainers, or is there a way to make project billing work without the cash flow cliff?"</p>

<p>They were worried that returning to retainers would slow growth. Their clients liked the flexibility of projects. But the current model was unsustainable. We needed to model what a hybrid approach would look like, and whether it could stabilise cash flow without killing revenue.</p>

<p>The founders also wanted to understand the tax implications. They were paying themselves and their co-founder through a mix of salary and dividends. The company was profitable on an accrual basis, around £180,000 net profit, but cash-poor. They were worried about corporation tax bills arriving when the bank balance was low.</p>

<h2>What we modelled</h2>

<p>We built three scenarios using their actual Xero data and a cash flow forecast in Float. The numbers were based on their last 12 months of trading:</p>

<ul>
<li><strong>Scenario A: Full return to retainers.</strong> Assume 70% of revenue from monthly retainers at £8,000–£12,000 each, with 30% from projects. This would give predictable monthly income of around £65,000, but we estimated a 15% drop in total revenue because some clients would resist committing to retainers.</li>
<li><strong>Scenario B: Hybrid with milestone billing.</strong> Keep project billing but break each project into three or four milestone payments. Invoice at 30% upfront, 40% at midpoint, 30% on completion. This would reduce average debtor days from 62 to around 35.</li>
<li><strong>Scenario C: Hybrid with a retainer core plus project upsells.</strong> Offer a lower-cost retainer for ongoing management (£5,000–£7,000 per month) with project fees for campaign launches. This would give a base of £40,000–£50,000 monthly recurring revenue, topped up with project work.</li>
</ul>

<p>We also modelled the tax impact. Under current rules, the company paid corporation tax at 25% on profits above £250,000, but their profits were below that threshold, so the rate was 19% on the first £50,000 and 25% on the rest. With net profit of £180,000, the corporation tax bill was around £38,000. If they switched to retainers and revenue dropped, the tax bill would fall, but so would their ability to reinvest in the team.</p>

<p>For the founders personally, they were taking a combined salary of £24,000 (the personal allowance threshold) and dividends of £80,000 each. The dividend tax rates for 2026/27 are 10.75% for basic rate, 35.75% for higher rate, and 39.35% for additional rate. With the dividend allowance now just £500, they were paying significant tax on those dividends. We modelled whether retaining more cash in the company and taking smaller dividends would improve their cash position.</p>

<h2>The outcome</h2>

<p>The founders chose Scenario C: a hybrid model with a retainer core and project upsells. It felt like the least risky option. They kept their existing project clients but shifted new business to the retainer-plus-project structure. For existing clients, they offered a discount on the retainer if they committed to at least six months.</p>

<p>They also implemented milestone billing for all new projects. The 30-40-30 split became standard. Within two months, average debtor days dropped from 62 to 41. Within four months, it was down to 33.</p>

<p>The cash flow stabilised faster than expected. The retainer base gave them a predictable £45,000 per month, which covered payroll and overheads. The project fees became the profit engine. They stopped using the overdraft entirely after three months.</p>

<p>On the tax side, they decided to keep dividends at £60,000 each rather than £80,000. That saved around £6,000 in personal tax per founder and left an extra £40,000 in the company. They used that to build a cash buffer of £80,000, equivalent to roughly 60 days of operating costs.</p>

<p>Within four months, the cash position was stable. The founders reported sleeping better. They had a clear view of the next three months' cash flow, and they were no longer chasing invoices to make payroll.</p>

<p>Revenue did dip slightly, from £1.2 million to around £1.1 million in the first year of the change, but profitability improved because they were spending less time on admin and chasing payments. The net profit margin went from 15% to 18%.</p>

<h2>What others can learn</h2>

<ul>
<li><strong>Retainers aren't dead, but they need to be structured right.</strong> A lower retainer base combined with project upsells gives predictability without locking clients into rigid commitments. It's a compromise that works for both sides.</li>
<li><strong>Milestone billing transforms cash flow.</strong> Breaking projects into three or four payments with upfront deposits reduces debtor days dramatically. It also forces better project management, you know exactly when cash is coming in.</li>
<li><strong>Tax planning is cash flow planning.</strong> Reducing dividends to retain more cash in the company can be a smart short-term move, especially when you're building a buffer. Just make sure you understand the dividend tax rates and the £500 allowance.</li>
<li><strong>Don't let a growing top line fool you.</strong> Revenue growth can mask cash flow problems. If your debtor days are climbing, you're effectively lending money to your clients. That's not sustainable.</li>
<li><strong>A cash buffer of 60 days is a minimum for agency businesses.</strong> When you're project-based, the gap between winning work and getting paid can be six to eight weeks. Having two months of costs in the bank means you can say no to bad deals and yes to good ones.</li>
</ul>`,
  },
  "seo-agency-us-revenue-vat-corporation-tax": {
    slug: "seo-agency-us-revenue-vat-corporation-tax",
    title: "Adding US Revenue: How a Manchester SEO Agency Handled VAT and Corporation Tax Across Two Tax Regimes",
    topic: "International revenue VAT and corporation tax interaction",
    agency_type: "SEO agency",
    stage: "Scaling internationally",
    outcome: "Clean compliance both sides, no double tax",
    body: `<em>Composite case study based on patterns across our agency clients. Names, locations and specific figures have been anonymised; the financial mechanics and tax treatment are real and reflect current UK rules.</em>

<h2>The situation</h2>

<p>An SEO agency based in Manchester's Northern Quarter had grown steadily for six years, specialising in technical SEO and content strategy for ecommerce brands. By early 2025, the agency employed 14 people across two teams, one in Manchester, one remote in the UK, and had annual revenue of £1.8 million. The founder, a former in-house SEO manager, had built the agency on a mix of monthly retainers and project-based work, almost entirely from UK clients.</p>

<p>That changed in late 2024 when a US-based direct-to-consumer brand approached them for a six-figure SEO retainer. The client was headquartered in Delaware with a fulfilment centre in Ohio, but had no UK presence. The retainer was worth £120,000 per year, invoiced monthly in US dollars. Within six months, the agency had signed two more US clients, a SaaS platform in Austin and a premium pet food brand in Colorado, pushing US revenue to £280,000 per year, roughly 15% of total turnover.</p>

<p>The founder knew this created complications. The agency was VAT-registered in the UK (its UK revenue exceeded the £90,000 threshold) and paid corporation tax at 25% on profits above £250,000. But the US clients were not UK businesses, and the services were delivered remotely from Manchester. The founder had heard about "reverse charge" rules and "double taxation" but wasn't sure how they applied to a service business like his.</p>

<h2>The decision</h2>

<p>The founder needed to understand three things clearly:</p>

<ul>
<li>Whether the US revenue was subject to UK VAT, and if so, how to charge and report it</li>
<li>Whether the US revenue was subject to US tax, and if so, how to avoid paying tax twice on the same income</li>
<li>How to structure the agency's finances so that the US revenue didn't accidentally push the UK corporation tax bill into a higher bracket or create a cash-flow problem</li>
</ul>

<p>He also wanted to know whether it was worth setting up a separate US entity, a Delaware LLC or a C-corp, to handle the US clients directly, or whether the existing UK structure could work cleanly.</p>

<h2>What we modelled</h2>

<p>We modelled three scenarios using the agency's actual numbers for the 2026/27 tax year, assuming UK revenue of £1.8 million and US revenue of £280,000. We used Xero and Float for cash-flow projections, and cross-referenced the VAT treatment against HMRC's place-of-supply rules for B2B services.</p>

<p><strong>Scenario 1: Keep everything in the UK Ltd company, treat US revenue as standard-rated for VAT.</strong><br>
Under this scenario, the agency would charge 20% UK VAT on every US invoice, adding £56,000 to the client's cost. The US clients, none of whom were UK VAT-registered, would have to pay that VAT, and the agency would remit it to HMRC quarterly. The US clients would not be able to reclaim that VAT, making the agency's pricing uncompetitive. The agency's UK corporation tax bill would be calculated on total worldwide profits (UK + US), so the £280,000 would be taxed at 25% (since total profits exceeded £250,000). The US would also tax the income, but the UK would give foreign tax credit relief for any US tax paid, provided the agency could prove it.</p>

<p><strong>Scenario 2: Treat US revenue as outside the scope of UK VAT (reverse charge), and pay US tax via a US tax return.</strong><br>
Under this scenario, the agency would not charge UK VAT on US invoices, because the services were supplied to a business customer outside the UK. Instead, the US client would account for any US sales tax or VAT themselves under the reverse charge mechanism. The agency would still report the revenue on its UK VAT return (box 6, and box 7 if the client was outside the EU), but no UK VAT would be due. The agency would then file a US tax return (Form 1120-F for a foreign corporation) to report the US-source income. The US would tax the income at the federal rate of 21%, plus any state-level tax (Delaware had no state corporate tax, but the clients in Texas and Colorado did). The UK would give foreign tax credit relief for the US tax paid, so the effective UK tax rate on that income would drop from 25% to around 4% (the difference between the UK rate and the US rate).</p>

<p><strong>Scenario 3: Set up a US LLC or C-corp, invoice US clients from the US entity, and pay a management fee to the UK company.</strong><br>
This scenario involved incorporating a US entity (a Delaware LLC, taxed as a C-corp by default for foreign owners) and transferring the US client contracts to it. The US entity would invoice the clients in dollars, pay US federal tax at 21%, and then pay a management fee to the UK company for the SEO work performed in Manchester. The management fee would be deductible in the US and taxable in the UK. The UK company would then pay UK corporation tax on the management fee income. The net effect was similar to Scenario 2, but with additional legal and accounting costs (US filing fees, state registration, separate bank account, US tax return preparation). The agency would also need to comply with US state-level registration in Texas and Colorado, which had franchise taxes and sales tax requirements.</p>

<h2>The outcome</h2>

<p>The founder chose Scenario 2, keep the UK Ltd company, treat US revenue as outside the scope of UK VAT, and file a US tax return to report the US-source income. The decision came down to simplicity and cost. Setting up a US entity would have cost roughly £5,000 in legal fees and annual compliance costs of £3,000, with no clear tax advantage over the foreign tax credit route.</p>

<p>The agency implemented the change in April 2025. They updated their Xero settings to tag US invoices as "outside scope" for VAT, and began filing quarterly US tax returns using a US-based accountant who specialised in foreign-owned companies. The US tax bill for the first year was £58,800 (21% of £280,000), and the UK corporation tax bill on the same income was reduced by the same amount via foreign tax credit relief. The net UK corporation tax on the US revenue was zero, the UK effectively recognised that the US had already taxed the income at a rate higher than the UK's marginal rate.</p>

<p>The agency also saved the £56,000 in UK VAT they would have had to charge under Scenario 1, keeping their pricing competitive against US-based SEO agencies. The US clients were happy because they didn't have to deal with UK VAT invoices or reclaim processes.</p>

<p>One unexpected benefit: the agency's cash flow improved. Under Scenario 1, they would have had to hold the VAT collected from US clients and pay it to HMRC quarterly, creating a timing mismatch. Under Scenario 2, no VAT was collected, so the full invoice amount hit the bank account immediately.</p>

<h2>What others can learn</h2>

<ul>
<li><strong>Place of supply matters more than where your client is based.</strong> For B2B services, the place of supply is where the customer belongs, not where you perform the work. If your client is a business outside the UK, you generally don't charge UK VAT, but you must still report the revenue on your VAT return.</li>
<li><strong>Foreign tax credits prevent double taxation, but only if you file correctly.</strong> The UK gives credit for foreign tax paid on the same income, but you need to prove the foreign tax was actually paid. Keep separate records of US revenue, US tax paid, and the exchange rates used.</li>
<li><strong>A US entity is rarely worth it for service businesses under £500k US revenue.</strong> The compliance costs and complexity of running a US company from the UK usually outweigh the tax benefits, especially when foreign tax credits are available.</li>
<li><strong>Check state-level requirements in the US.</strong> Even if you don't have a physical presence in the US, some states (like Texas and Colorado) require foreign companies to register and file franchise or income tax returns if they have clients there. Ignoring this can lead to penalties.</li>
<li><strong>Use software that separates VAT treatment by client location.</strong> Xero and FreeAgent both allow you to set default VAT treatment per contact, so you don't accidentally charge UK VAT on US invoices. Float can help you model cash-flow impacts of different VAT scenarios.</li>
</ul>`,
  },
  "ppc-agency-xero-from-freeagent-migration": {
    slug: "ppc-agency-xero-from-freeagent-migration",
    title: "Upgrading from FreeAgent to Xero: A Growing PPC Agency's \u00a314k Lesson",
    topic: "Accounting software migration mistakes during scale-up",
    agency_type: "PPC agency",
    stage: "Scaling",
    outcome: "Lost data recovered, new chart of accounts saving \u00a314k/year in management time",
    body: `<em>Composite case study based on patterns across our agency clients. Names, locations and specific figures have been anonymised; the financial mechanics and tax treatment are real and reflect current UK rules.</em>

<h2>The situation</h2>

<p>A specialist PPC agency based in Manchester’s Northern Quarter had grown fast. Founded in 2019 by two former in-house marketing managers, the firm had built a reputation for high-ROI Google Ads and Microsoft Advertising campaigns for ecommerce and B2B clients. By early 2025, the agency employed 14 people, 10 delivery staff, two account managers, a part-time bookkeeper, and the two founders. Revenue had climbed from £280,000 in 2022 to £620,000 in 2024, with a forecast of £850,000 for 2025.</p>

<p>The founders had used FreeAgent since launch. It was simple, cheap, and handled their basic invoicing, expense tracking, and VAT returns. But by late 2024, the cracks were showing. The agency now ran multiple client ad accounts through Klaviyo and Google Ads, with complex cost structures: media spend billed to clients, retainer fees, performance bonuses, and subcontractor payments for freelance PPC specialists. FreeAgent’s chart of accounts was flat, just 12 categories, and the bookkeeper was spending eight hours a week manually reclassifying transactions and reconciling client prepayments. The founders wanted something with proper project tracking, multi-currency support (they had two UAE clients paying in dirhams), and a chart of accounts that reflected how the business actually worked.</p>

<h2>The decision</h2>

<p>The founders decided to migrate from FreeAgent to Xero. They’d heard Xero handled multi-currency better, had stronger reporting, and integrated natively with Float for cash flow forecasting. The part-time bookkeeper recommended it, and a friend at another agency had made the switch with no issues. The founders gave the go-ahead in January 2025, aiming for a February go-live.</p>

<p>The problem? They didn’t plan the migration properly. They assumed it was a simple export-import job. They didn’t clean up FreeAgent first. They didn’t map the chart of accounts in advance. And they didn’t set aside time for the bookkeeper to test the new setup before going live.</p>

<h2>What we modelled</h2>

<p>When the founders came to us in March 2025, they were in a mess. The migration had gone live on 1 February, but within two weeks the bookkeeper found that 47% of transactions from January hadn’t mapped correctly. Client prepayments were showing as income. Media spend was lumped into a single “cost of sales” category. The multi-currency accounts for the UAE clients were showing negative balances because the exchange rates had been entered manually and incorrectly. The founders had lost three weeks of bookkeeping time and were facing a VAT return deadline in April.</p>

<p>We modelled three options:</p>

<ul>
<li><strong>Option A: Roll back to FreeAgent.</strong> This would mean reversing the Xero migration, restoring a backup from January, and re-entering February and March data manually. Cost: roughly £2,000 in bookkeeper overtime and a week of lost productivity. The agency would then need to re-plan the migration properly later.</li>
<li><strong>Option B: Fix Xero in place.</strong> This meant rebuilding the chart of accounts from scratch, re-mapping all historical data, correcting the multi-currency entries, and reconciling the VAT return manually. Estimated cost: £4,500 in additional bookkeeper hours and two weeks of the founders’ time.</li>
<li><strong>Option C: Full reset with professional support.</strong> We would clean up FreeAgent first (correcting the chart of accounts, removing duplicates, standardising supplier names), then re-export a clean data file, map the new Xero chart of accounts properly, and run a parallel test for one month before going live again. Estimated cost: £6,000 in professional fees and one week of the founders’ time, but with a guarantee of no data loss and a properly structured system going forward.</li>
</ul>

<p>We also modelled the ongoing time saving. Under the old FreeAgent setup, the bookkeeper spent eight hours a week on manual reclassification and reconciliation. With a properly structured Xero chart of accounts, 35 categories, automated bank feeds, and project tracking for each client, that would drop to two hours a week. At the bookkeeper’s rate of £35 per hour, that was a saving of £210 per week, or £10,920 per year. Add in the time the founders saved not having to review dodgy reports, and the total management time saving was around £14,000 annually.</p>

<h2>The outcome</h2>

<p>The founders chose Option C. It was the most expensive upfront, but it solved the root cause, not just the symptom. We spent two weeks cleaning up FreeAgent. The chart of accounts had 18 duplicate supplier entries, 23 uncategorised transactions from 2023, and three client prepayments that had been sitting as income for over six months. We standardised everything, created a proper cost-of-sales breakdown (media spend, subcontractors, software tools, platform fees), and set up project-level tracking for each of the 11 active clients.</p>

<p>We then exported a clean data file, mapped it to the new Xero chart of accounts, and ran a parallel test for March. The bookkeeper reconciled both systems side by side. When the numbers matched, we switched over on 1 April, just in time for the VAT return. The return was filed on time, with no errors.</p>

<p>The financial result was immediate. The bookkeeper’s weekly time dropped from eight hours to two. The founders could now run a real-time profit-and-loss report by client, which they’d never been able to do before. They spotted that one client was actually loss-making once media spend and management time were properly allocated, they renegotiated the retainer and turned it into a 12% margin client within three months. The multi-currency accounts for the UAE clients now reconciled automatically, saving another hour a week.</p>

<p>By the end of 2025, the agency had saved £14,000 in management time. The £6,000 professional fee was recouped in under six months. The founders said the biggest lesson was that “a software migration is a business process change, not an IT job.”</p>

<h2>What others can learn</h2>

<ul>
<li><strong>Clean your data before you move.</strong> A migration is only as good as the data you take with you. Spend a week tidying up your chart of accounts, removing duplicates, and reconciling balances before you export. It saves weeks of pain later.</li>
<li><strong>Run a parallel test.</strong> Don’t go live on day one. Run both systems side by side for at least one full month. Reconcile the numbers. Only switch over when they match perfectly.</li>
<li><strong>Map your chart of accounts to your business model.</strong> If you’re a PPC agency, your cost of sales isn’t just “cost of sales”. Break it out: media spend, subcontractors, platform fees, software tools. A flat chart of accounts hides problems.</li>
<li><strong>Budget for professional support.</strong> The £6,000 we charged was less than the cost of the lost bookkeeping time and the founders’ stress. A good accountant or Xero consultant will save you money in the long run.</li>
<li><strong>Think about the ongoing saving, not just the upfront cost.</strong> The £14,000 annual time saving was five times the migration cost. If a proper setup saves you two hours a week forever, it’s worth investing in getting it right.</li>
</ul>`,
  },
  "web-design-agency-vat-threshold-decision": {
    slug: "web-design-agency-vat-threshold-decision",
    title: "Solo Web Designer at \u00a388k: When to Voluntarily Register for VAT",
    topic: "Voluntary VAT registration decision below threshold",
    agency_type: "Web design (solo)",
    stage: "Pre-threshold",
    outcome: "Voluntary registration recovered \u00a38k in input VAT in year 1",
    body: `<em>Composite case study based on patterns across our agency clients. Names, locations and specific figures have been anonymised; the financial mechanics and tax treatment are real and reflect current UK rules.</em>

<h2>The situation</h2>

<p>A solo web designer, let’s call her Rachel, had been running her business from a home office in Bristol Harbourside for three years. She specialised in building custom WordPress sites for local service businesses-dentists, estate agents, and boutique hotels. Her annual turnover had grown steadily from £42,000 in year one to £88,000 in the most recent tax year. She was a one-person operation, using Xero for bookkeeping, FreeAgent for cashflow forecasting, and Klaviyo for email marketing. She had no employees and no plans to hire.</p>

<p>Rachel had always been VAT-registered in her mind as something that happened when you hit £90,000. She was £2,000 below that threshold and expected to cross it within six months. But she was also spending heavily on equipment: a new MacBook Pro, a 4K monitor, a proper office chair, and a subscription to a premium design tool. She had also recently invested £3,000 in a photography course and £1,200 in a copywriting course to improve her service offering. All of these costs were VAT-inclusive, and she was not recovering any of that tax.</p>

<p>Her accountant had mentioned voluntary registration at their last review, but Rachel was nervous. She worried that adding 20% to her invoices would make her uncompetitive against other freelancers who were not VAT-registered. She also worried about the admin burden-quarterly returns, extra bookkeeping, and the risk of penalties if she got it wrong.</p>

<h2>The decision</h2>

<p>Rachel needed to decide whether to voluntarily register for VAT now, while her turnover was still below £90,000, or wait until she hit the compulsory threshold. The core question was simple: would the input VAT she could recover outweigh the cost of charging VAT to her clients?</p>

<p>She had three main concerns. First, most of her clients were small businesses that were not VAT-registered themselves. For them, a 20% price increase would be a real cost. Second, she had no idea how much input VAT she was actually losing. Third, she was not sure if the administrative hassle was worth it for a solo operator.</p>

<p>We sat down with her and modelled three scenarios.</p>

<h2>What we modelled</h2>

<p>We used Rachel’s actual numbers from the last 12 months and projected forward based on her expected growth. All figures are 2026/27 rates.</p>

<p><strong>Scenario 1: Stay below threshold and do nothing</strong><br>
Rachel would continue to charge no VAT and pay all her costs VAT-inclusive. Her annual costs were roughly £18,000, of which about £3,000 was VAT that she could not recover. She would keep her prices the same and hope to cross £90,000 naturally. The downside: she would lose £3,000 in input VAT every year, and once she crossed the threshold, she would have to register anyway and absorb the admin cost at that point.</p>

<p><strong>Scenario 2: Voluntarily register now and absorb the VAT</strong><br>
Rachel would register for VAT, charge 20% on all invoices, but not pass the cost to clients. Instead, she would reduce her net prices so that the total invoice stayed the same. For example, a £1,200 project would become £1,000 plus £200 VAT. Her clients would pay the same amount, but Rachel would need to account for the VAT to HMRC. She would recover all input VAT on her costs, giving her an immediate £3,000 cash benefit. The catch: her net revenue would drop by roughly 16.7% (because 20% of the gross goes to HMRC), so she would need to increase her volume or rates to maintain take-home pay.</p>

<p><strong>Scenario 3: Voluntarily register now and pass on the VAT</strong><br>
Rachel would register and add 20% to her invoices. Her clients would pay more, but she would recover all input VAT. We estimated that about 60% of her clients were VAT-registered themselves and could reclaim the VAT, so the net cost to them was zero. The remaining 40% were small businesses or individuals who would see a real price increase. We modelled a 10% loss of those clients, which reduced her revenue by about £3,500. After recovering £3,000 in input VAT, her net position was roughly break-even in year one, but with the potential to improve as more clients became VAT-registered over time.</p>

<p>We also factored in the Flat Rate Scheme. For a web designer, the flat rate percentage is 14.5% in year one (with a 1% discount in the first year). That would mean she paid HMRC 13.5% of her turnover instead of 20%, and she could still recover input VAT on capital assets over £2,000. We ran the numbers: on £88,000 turnover, the Flat Rate Scheme would cost her £11,880 in VAT (13.5%), compared to £17,600 under standard accounting. She would recover about £2,000 in input VAT on the MacBook and monitor, giving a net cost of roughly £9,880. Under standard accounting, the net cost would be £14,600. The Flat Rate Scheme saved her about £4,720 in year one.</p>

<h2>The outcome</h2>

<p>Rachel chose to voluntarily register for VAT under the Flat Rate Scheme. She decided to absorb the VAT for her existing clients (scenario 2) to avoid price shocks, but she increased her quoted rates for new clients by 10% to offset the net revenue loss. She also switched to FreeAgent’s VAT-ready plan, which automated her quarterly returns.</p>

<p>The result in year one: she recovered £8,200 in input VAT-more than we had modelled-because she also claimed VAT on a new laptop, a standing desk, and a software bundle she had bought in the previous quarter before registering. Her net revenue after VAT was £76,120, compared to £88,000 before. But her costs fell by £8,200, meaning her net profit actually increased by about £4,000. She also gained the confidence to raise her rates, and by the end of year one, her turnover had grown to £96,000-now above the compulsory threshold anyway.</p>

<p>Her clients: the 60% who were VAT-registered noticed no change. The remaining 40% saw a small price increase on new projects, but Rachel offered a 5% discount for early payment, which most accepted. She lost only one client, a small bakery that could not absorb the increase. That client came back six months later after registering for VAT themselves.</p>

<h2>What others can learn</h2>

<ul>
<li><strong>Voluntary registration can be profitable below the threshold.</strong> If you are spending more than £2,000–£3,000 a year on VAT-inclusive costs (equipment, software, training, subcontractors), the input VAT you recover can outweigh the admin cost. Use the Flat Rate Scheme in your first year to reduce the VAT you pay to HMRC.</li>
<li><strong>Know your client mix.</strong> If most of your clients are VAT-registered businesses, they will not care if you add 20%-they reclaim it. If they are consumers or small unregistered businesses, you may need to absorb the VAT or offer discounts. Model the impact before you register.</li>
<li><strong>The Flat Rate Scheme is a blunt tool but useful for solo operators.</strong> It simplifies your returns to a single percentage of turnover, and the first-year discount makes it especially attractive. But check that your sector’s flat rate percentage (14.5% for web design) works for your cost structure. If you have high costs, standard accounting may be better.</li>
<li><strong>Capital purchases are a trigger.</strong> If you are about to buy a laptop, monitor, or other equipment over £2,000, registering before you buy lets you reclaim the VAT on that purchase. In Rachel’s case, that single decision added £1,200 to her recovery in year one.</li>
<li><strong>Admin is not as scary as it seems.</strong> Modern software like Xero and FreeAgent handle VAT returns automatically. The quarterly submission takes about 30 minutes once you are set up. The fear of paperwork is often worse than the reality.</li>
</ul>`,
  },
  "creative-agency-uk-to-dubai-relocation": {
    slug: "creative-agency-uk-to-dubai-relocation",
    title: "Creative Agency Founder Relocating to Dubai While Keeping a UK Ltd",
    topic: "UK-to-Dubai relocation with retained UK company",
    agency_type: "Creative agency",
    stage: "Relocating",
    outcome: "Statutory residence test cleared, UK Ltd operating with non-resident director status",
    body: `<em>Composite case study based on patterns across our agency clients. Names, locations and specific figures have been anonymised; the financial mechanics and tax treatment are real and reflect current UK rules.</em>

<h2>The situation</h2>
<p>Alex ran a fifteen-person creative agency based in a converted warehouse in Bristol Harbourside. The agency specialised in brand strategy and visual identity for mid-market e-commerce brands, with a strong roster of UK and European clients. Revenue had settled at around £1.8m a year, with profits of roughly £450,000 after salaries, studio costs and software subscriptions (Xero, Float, Klaviyo, Figma).</p>
<p>Alex had lived in the UK their whole life. But after a few long-haul trips to Dubai for client meetings, they started to see the appeal of relocating: zero personal income tax, a time zone that worked for both Europe and Asia, and a lifestyle that suited their young family. The question was what to do with the UK company. Close it down? Sell it? Keep it running while living abroad?</p>
<p>Alex came to us in early 2025, six months before their planned move. They wanted to keep the agency running from Dubai, with the same team in Bristol, the same clients, and the same UK limited company. But they needed to know whether that was possible without triggering a tax nightmare.</p>

<h2>The decision</h2>
<p>The core question was straightforward but the answer was not: could Alex live in Dubai full-time, remain the sole director and shareholder of their UK Ltd, and not pay UK tax on the company’s profits or on dividends taken in the UAE?</p>
<p>Three things had to be true for this to work:</p>
<ul>
<li>Alex had to pass the Statutory Residence Test (SRT) and be treated as non-UK resident for tax purposes.</li>
<li>The UK company had to be managed and controlled from outside the UK, otherwise HMRC could argue it was still UK-resident for tax.</li>
<li>Dividends paid to Alex while they were non-resident had to fall outside UK income tax, which they generally do if the company remains UK-resident but the shareholder is non-resident.</li>
</ul>
<p>Alex also had a practical concern: they wanted to keep their UK bank accounts, their UK pension contributions, and their ability to return to the UK for client meetings without accidentally becoming tax-resident again.</p>

<h2>What we modelled</h2>
<p>We ran three scenarios, all using 2026/27 UK tax rates.</p>
<p><strong>Scenario A: Sell the company before leaving.</strong> Alex would take a capital distribution on liquidation, paying 14% Business Asset Disposal Relief (BADR) on the first £1m of gains, then 24% above that. With retained profits of roughly £1.2m after all taxes, the tax bill would be around £168,000. Clean break, but Alex would lose the ongoing income stream and the team.</p>
<p><strong>Scenario B: Keep the company but move management to Dubai.</strong> Alex would remain director and shareholder, but all strategic decisions, board meetings, major contracts, pricing, hiring, would happen from Dubai. The Bristol team would handle day-to-day operations. The company would remain UK-resident for corporation tax (because it was incorporated here), but Alex would be non-resident. Dividends taken in Dubai would be tax-free for Alex personally. Corporation tax on profits would still be payable in the UK at 19% on the first £50,000, 25% on profits above £250,000. With £450,000 profit, that’s roughly £112,500 in corporation tax. But Alex could take the remaining £337,500 as dividends without further UK tax. Total effective tax rate: 25%.</p>
<p><strong>Scenario C: Keep the company but stay UK-resident.</strong> Alex would live in Dubai but spend more than 90 days a year in the UK, failing the SRT. They would pay UK income tax on worldwide dividends at 39.35% (the additional rate). On £337,500 of dividends, that’s an extra £132,800 in personal tax. Total effective rate: nearly 55%.</p>
<p>We also modelled the impact of the dividend allowance (now just £500) and the personal allowance (£12,570), but for someone taking six-figure dividends, those were rounding errors.</p>
<p>The key numbers made Scenario B the clear winner: a 25% total tax rate versus 55% or a one-off 14-24% plus losing the business.</p>

<h2>The outcome</h2>
<p>Alex chose Scenario B. They moved to Dubai Marina in September 2025, with a residency visa and a clear paper trail. We helped them restructure the company’s governance:</p>
<ul>
<li>Board meetings were formally held in Dubai, with minutes recorded there.</li>
<li>Alex’s employment contract with the UK company was terminated; they became a non-executive director, paid via dividends, not salary.</li>
<li>The Bristol studio manager was promoted to operations director, with authority to sign off on day-to-day client work and supplier payments.</li>
<li>Alex kept a UK mobile number and a small flat in Clifton (owned by the company, used for client meetings) but limited UK visits to 45 days in the first tax year.</li>
</ul>
<p>We also set up a clear diary and travel record to support the SRT. Alex used a simple spreadsheet to log days in the UK, flights, and meeting locations. HMRC can challenge residency status, but with fewer than 90 days in the UK and a genuine home in Dubai, the risk was low.</p>
<p>The financial result in the first full year: the company paid £112,500 in UK corporation tax on £450,000 profit. Alex took £337,500 in dividends, paying zero personal tax. Compared to staying in the UK, where they would have paid an additional £132,800 in dividend tax, the saving was substantial. The company also saved on Alex’s salary costs, no employer NI, no pension contributions, which added roughly £15,000 to retained profits.</p>
<p>One unexpected benefit: the Dubai time zone made it easier to pitch to US and Asian clients. Revenue grew 12% in the first year, partly because Alex could take calls at 8am Dubai time that would have been 4am in Bristol.</p>

<h2>What others can learn</h2>
<ul>
<li><strong>Residency is the gatekeeper.</strong> You can live in Dubai and keep a UK company, but you must genuinely sever your UK ties. That means fewer than 90 days in the UK, no UK home (or a clear pattern of short stays), and a permanent home in the UAE. HMRC’s Statutory Residence Test is formulaic but unforgiving.</li>
<li><strong>Management and control must move.</strong> If you keep making key decisions from a coffee shop in Shoreditch, HMRC will argue the company is still managed from the UK. Formal board meetings in Dubai, a local address, and delegated authority to a UK team are essential.</li>
<li><strong>Dividends are your friend.</strong> Non-resident shareholders in UK companies generally pay no UK tax on dividends. But you cannot pay yourself a salary from the UK company while living abroad, that would trigger UK payroll taxes and potentially create a permanent establishment risk.</li>
<li><strong>Plan the exit from day one.</strong> Alex’s move worked because they started planning six months ahead. If you try to relocate in December and declare yourself non-resident from January, HMRC will look very closely at your intentions. A clean break, sell the house, cancel the gym membership, move the family, makes the case much stronger.</li>
<li><strong>Get professional advice on the visa.</strong> UAE residency is straightforward for most business owners, but the rules changed in 2025. You need a valid reason for residency (employment, property, or investment) and you must actually live there. A golden visa is not a tax dodge; it is a genuine relocation.</li>
</ul>`,
  },
};
