"""Ecommerce Tax Partners (ecommerce) site configuration.

Generated by optimisation_engine.ops.spinup_site on 2026-07-15. Edit freely
after the scaffold is in place.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]


SITE_CONFIG: dict = {
    "site_key": "ecommerce",
    "display_name": "Ecommerce Tax Partners",
    "domain": "www.ecommercetaxpartners.co.uk",
    "site_base_url": "https://www.ecommercetaxpartners.co.uk",
    "author_name": "Ecommerce Tax Partners Editorial Team",
    "output_dir": "ecommerce/web/content/blog",
    "pillar_output_dir": None,

    # Post Phase 4: all sites share blog_topics; site_key isolates rows.
    "topic_table": "blog_topics",
    "topic_column": "topic",
    "secondary_keywords_shape": "array",
    "done_marker_field": "used",
    "done_marker_value": True,
    "done_timestamp_field": "used_at",
    "slug_field": "slug",
    "topic_order": "publish_priority.desc.nullslast,keyword_difficulty.asc.nullslast,created_at.asc",

    "llm_provider": "anthropic",
    "llm_model": "claude-sonnet-4-6",
    "max_tokens": 6500,
    "temperature": 0.3,
    "verify_with_haiku": True,

    "post_categories": [],
    "internal_link_slugs": [],
    "anchor_terms": [],
    "hallucination_zones": [],
    "blog_system_prompt": """You are an expert UK accountant writing for UK ecommerce and marketplace sellers (Amazon, eBay, Etsy, Shopify): tax, VAT, platform reporting and seller accounts.""".strip(),

    "seo_persona": {
        "audience": "UK ecommerce and marketplace sellers (Amazon, eBay, Etsy, Shopify): tax, VAT, platform reporting and seller accounts",
        "language_cues": [],
        "preferred_hooks": [],
        "banned_openers_extra": [],
        "brand_authority": "mid",
        "geo_qualifiers": ["UK"],
        "voice_signature": "specialist, evidence-driven, plain English",
    },
}
