"""Final redacted messages for the sample table. Hand-reviewed 2026-07-15:
regex pass plus manual redaction of names/companies/addresses.
Key = lead id 8-char prefix. New leads without an entry trigger a review prompt."""

OVERRIDES = {
  "c57d1cea": "Situation: I am considering purchasing a property in Aberdeen to operate as a short-term let/Airbnb business. I am exploring whether to buy personally or through a limited company and would like advice on the tax implications, structure, allowable expenses, and how funding options (including possible remortgaging of my existing property) could work alongside a limited company setup.\n\nI would like to understand the most tax-efficient approach before proceeding with the purchase.\nI would like to understand the most tax-efficient approach before proceeding with the purchase.\n\nPrompted by: I am at the planning stage of my first property investment and want professional advice before setting up a company or purchasing a property.\n\nWants from call: Advice on the best ownership structure (personal vs limited company), short-term let tax considerations, company setup, and how property finance could be structured.",
  "025fd0bc": "Situation: I’m needing advice and help pointed  in the rite direction on what I do 1st, how I do it and what are the best options. I can go more into detail if needed. I need to know about property tax..is this something you specialise in\n\nPrompted by: I’m going  to build me own portfolio\n\nWants from call: Knowledge",
  "23e989ae": "want to know if its best to transfer the property in to a ltd company",
  "eb23434e": "Situation: I own a flat and am\nConsidering giving to a Airbnb rental firm to let out\n\nPrompted by: Making the above choice\n\nWants from call: I’d like a quote for accountancy from a firm with experience in how to handle property repairs and deductibles",
  "8b87e37c": "cgt tax to pay if bought at £132,500.00 and sold at £220.000",
  "e8240209": "Situation: I'm an unincorporated landlord (an individual, not a limited company) looking for help on a few connected tax matters.\n\n1. Capital gain: I have a gain this year from a members' voluntary liquidation of a company I owned, on which I expect to claim Business Asset Disposal Relief. Part of the distribution was an overdrawn director's loan account released in specie, so I need someone comfortable with the CGT treatment and reconciling the liquidator's paperwork.\n\n2. Self-assessment 2026/27: two residential rental properties, one a shared-ownership flat, so SA105 pages, Section 24, and full allowable-expense capture. Employment income that, with rental profit, puts me near the £100,000 adjusted-net-income threshold, so I'm managing the taper via pension salary sacrifice.\n\nPrompted by: FY26 Self-Assessment\n\nWants from call: Quote",
  "b3d7ccda": "Situation: I own two buy to let properties. I am seeking help to get ready for MTD. Whilst my income is <£30000, I am seeking help to get set up and then for ongoing support.\n\nPrompted by: MTD is causing severe worry.\n\nWants from call: Support to begin digitising and preparing for MTD. I currently work using a paper based system and spreadsheets.",
  "da7a30cb": "Situation: Hi. I have 3 btls in my personal name and also a Ltd company with 3 btls. I want to transfer my properties out of my personal name into the Ltd company\n\nPrompted by: I was going to sell them one by one to the company but may be a better way?\n\nWants from call: What’s the best option financially",
  "d650f5b2": "retired with 5 flats, private pension, state pension",
  "53f31e13": "My wife and I own 15 properties privately together. We have run this a  business for many years, seperate bank account, wages for property manager etc etc. We are considering moving these properties into a limited company and would like to explore the process in more detail.",
  "f4ea2e60": "explore implications of transferring a property under ltd",
  "d8283a3e": "[Specialist question] Hello — I'm an adviser to a private client with a property portfolio of around £5 million, mixed residential and commercial. I'd like to send a short written brief to your property tax or private client specialist, asking for a written proposal on fees and approach. Could you tell me the best person to send it to, and their email? I'll send it across today so they can look out for it.",
  "8c63d2a0": "Trying to understand mortgage interest tax relief for personal purchase  vs limited company",
  "5f95f87e": "I WISH TO SELL MY SECOND PROPERTY PREVIOUSLY RENTED OUT.  I HAVE NO MORTGAGE ON THE PROPERTY AND WOULD LIKE TO TRANSFER MY PROPERTY INTO JOINT NAMES (mine and my husband's) TO REDUCE THE CGT ON SALE.  AS WE HAVE ANOTHER PROPERTY IN JOINT NAMES, WHERE WE LIVE, WOULD ANY ADDITIONAL TAX BE DUE?",
  "83e35f85": "Situation: Hello team,\n\nThis is a request for advice on a property acquisition and the tax structuring around it.\n\nI live in a block of four flats in [AREA].\n\n1. [ADDRESS A].  I am currently in negotiation to purchase this.\n2. [ADDRESS B].  I own this on a BTL mortgage with [LENDER].  £163k outstanding on a £295k purchase.  Current value around £325k.\n3. [ADDRESS C].  Separately owned by a professional landlord.  Available in due course.\n4. [ADDRESS D].  I own this and live here.  Unencumbered.\n\nThe freehold is held by [COMPANY], a dormant management company in which I am one of three directors and shareholders alongside the other two flat owners.\n\nI am in active negotiation to buy [ADDRESS A] at £330k-£360k.  The deal\n\nPrompted by: Re-starting purchase negotiation\n\nWants from call: Advice on matters stated above.  Any other points you think i may have missed.",
  "37df11ad": "Situation: We are about to purchase a home in Edinburgh in August for a £1.5m cost.  Within the property footprint, we are being offered an adjoining apartment worth £400k with an understanding that we would purchase this from the owner exactly a year after we purchase the main house.  We are looking to commit to both of these with an offer which has been verbally accepted however, we are trying to look at the best route for removing the ADS burden and have a couple of options that we were hoping to get advice with.\n\nPrompted by: Imminent purchase of 1st property in August.\n\nWants from call: To understand the options to negate ahving the apartment deemd as a second home and this the tax burden and increased council tax burden.",
  "4bffe7ac": "[Specialist question (landlord-essentials)] My LTD is VAT registered. It recently acquired a residential property in a simple way, no SPV, no subsidiaries. \nDoes rental income fall within VAT rules?\n\n---\nSituation: I own an LTD. It is VAT registered due to its trading. It purchased a residential property (no SPV). Is the rent VATtable?\n\nPrompted by: cross checking advice\n\nWants from call: checking tax liability",
  "1b7b6a54": "Situation: Hi, I would like to know if you have any advice or help for Non-resident landlord? Thanks\n\nPrompted by: nope\n\nWants from call: nope",
  "ad6ead36": "Situation: Council tax advice. Currently paying 100% increase, as section 106 is stopping us from selling/renting on open market\n\nPrompted by: Frustration at increased cost\n\nWants from call: To know if there are ways of getting an exemption or reduction",
  "20162539": "[Mobile tool: capital-gains]: Looking to sell property for 230,000",
  "65ac80d4": "[Inline mini-form (Property Accountant Services)]: Advice on Tax on Rental Income\n\nDear Sir/Madam,\n\nMy name is [NAME]. I am seeking advice regarding UK tax obligations on rental income from a flat I let in [AREA], London. The rental income was used largely to cover the monthly repayments of a repayment mortgage, and I would like to understand what tax may be due and what information is required for compliance.\n\nPlease let me know whether you could assist and what details you would need from me.\n\nKind regards,\n[NAME]",
  "549d7498": "Situation: I am  looking for  SA 25/26  and  MTD  services,  plus  CGT  Advice\n\nPrompted by: I  looked up your  advice  on  Rental Insurance  payment classification\n\nWants from call: A clear  reasonably  priced  SA  MTD service  but to find a trusted adviser on  tax planning",
  "35464f1e": "Situation: My husband solely owns a mortgage-free buy-to-let property (some cash remortgaged from another one), but I paid a part  in December 2023. At purchase, we privately signed a Declaration of Trust splitting beneficial interest, but it was never solicitor-verified. My husband is a 40% taxpayer; I have no employment income but earn £15,600/year gross rent from another property. We want to restructure this property to a 99:1 split to optimize tax.I need to know:Must we legally add my name to the deeds as Tenants in Common, or is a Sole Owner Trust enough?Can we use our unverified 2023 deed to retrospectively apply the 99:1 split to the 2025/2026 tax year due January 2027?Do we need a Form 17?Do you offer an all-in-one legal/tax package including solicitor work, and what are your quotes?\n\nPrompted by: We want our new tax arrangement to take official effect ASAP. Crucially, I am traveling overseas on 17 July 2026 for a month, so we need to speak to an expert immediately.\n\nWants from call: I would like answers to the questions about 1.Title Deeds, 2.\tSplit & Form 17, 3.\t25/26 Retrospective Tax, 4. Quotes",
  "67f2239c": "Situation: I am looking to buy a buy to let property in a limited company.  My question is about adding my husband as a director, and how to extract money from the company tax efficiently.  We are starting this with a directors loan into the company.\n\nPrompted by: Offered on a property and need to check LTD is set up correctly\n\nWants from call: Advise on tax and company structure",
  "0a8b9d70": "[Specialist question (incorporation)] I have had a partnership property portfolio with my brother for 20 years. property purchased for £350,00 now valued at 1,213,000. we are both retired and would like to transfer the portfolio into a limited company using Incorporation Relief. we spend more than 20 hours a week on running the portfolio",
  "b0f00f0d": "I think incorporation of our property portfolio would benefit us at our age and in our position.",
  "67b2507c": "I have just sold a property in London that I use to live in but rented it out for the last 5 years.",
  "5c6f9f19": "[Mobile tool: capital-gains]: I have just sold my flat that was rented out for 6 years with a 6 month sabbatical.",
  "c7c334f2": "We are a married couple who own a leasehold flat jointly\nWe have an outstanding £198k mortgage on the flat.\n\nWe are buying a second property and rent out this flat.\nMy husband earns 100k and we are considering changing beneficial ownership from 50/50 to 99/1 to reduce rental income tax and at least broke even. Can you advise on Form 17 and preparation of  a Declaration of Trust?",
  "b73c14bb": "[Result gate: capital-gains-premium]: I am considering selling a buy to let property",
  "b06d35a4": "Subject: Non-resident UK residential property CGT - quote and capability check (London sale)\n\nHello,\n\nI am a non-UK-resident individual (Hong Kong permanent resident) preparing to sell a UK residential property in [AREA], London. \n\nI would like to ask questions regarding whether I can use your services,  is there an email address I can contact you at?\nI don't have a UK phone number.\n\nThanks and Regards,\n\n[NAME]",
  "e80a08d5": "[Inline mini-form (Non-Resident Landlord Tax)]: I live in South Africa, and at the end of last year, my three siblings (based in the UK) and I sold a piece of ground in [COUNTY]. This land was left to us jointly by my mother. I wasn't aware of the 60-day rule and now I seem to be in trouble. I'm finding the submission of information a minefield (not as sharp at 81 as I used to be). I need help and I can't seem to get the payment made and hopefully not pay penalites.",
  "ee488715": "Fair point. Here's the revised message:\n\n---\n\nI'm looking to purchase my first buy-to-let property (3-bed terraced house, £80k–£150k, targeting Northern cities) and need advice on ownership structure before I buy. I'm currently a basic rate taxpayer on ~£30k salary, but I also day trade and I am targeting £30k+ in gains next year on a consistent and growing basis. I need to understand whether HMRC would classify my trading as income rather than capital gains, and if so, whether that makes an SPV limited company the right structure for property one rather than personal name. I'd also want to cover allowable expenses, Self Assessment setup, and bookkeeping from day one.",
  "cfde219a": "[Result gate: section-24-premium]: PAYING TAX ON A RENTED PROPERTY",
  "4bc79f79": "Dear Sir/Madam\n\nI am looking to appoint new accountancy/bookkeeper services and would welcome a quote for the following scope of work.\n\nWe have holiday and residential accommodation with a current turnover of c£750k.\n\n- [COMPANY] (holiday and residential) – trading company, vat\n- Personal self-assessment tax returns for myself (holiday lets) and my wife\n- Partnership accounts (joint) \n- Two small property management companies\n\nPlease send your email so I can finish the work required. Thanks",
  "bb104e32": "I need to find some expert support with a Buy to Let/CGT problem. Transfer of ownership (2007) to my company was valued high but no money changed hands. I now want to sell my 4 converted flats (in a large Victorian terrace) asap but my current accountant seems unable to advise – I presume because this requires specialist advice.",
  "54262c2c": "I'm enquiring about new business incorporation and accounting. I'm a SME business director, looking to start in property investments",
  "92d955cc": "I am in the process of buying a rental property in a Ltd company. I'd like to work with accountants who understand the ins and outs of that from an accounting perspective who can advise accordingly.",
  "0a0ce93d": "[Exit intent (capital-gains)]: We bought a property in 2006 for about 170.000 incl estate agents fees and stamp duty. we hope to sell at 450,000. we lived in the house for 2 years. Thanks",
  "ca2b3253": "[Specialist question] Would you have soft copies of Form SA109 and Notes SA 109 say for tax-year 2014, 2025 etc that can be used online to file or be printed to file Tax return in paper form"
}

# Reviewed 2026-07-16: no names/companies/addresses present; regex output kept as-is.
OVERRIDES.update({
    "729416b5": "[Specialist question] I am looking for tax advice to ensure I am paying tax efficiently. I have 3 properties which combined generate over £100,000 in rent, one is held by a ltd company.  I have an accountant, but he's not a property tax specialist.  I am currently within the basic tax band, but I am close to the higher tax band (I could be in the higher tax band if I chose to pay myself via dividends or higher salary but I have a director's loan and half of my income is from this, tax free, but it is depleting.",
    "08c9ffcd": "Situation: Would like to get a quote for incorporation costs and annual filing services.\n\nPrompted by: Buying first BTL\n\nWants from call: Quote for above services",
    "3788e0a2": "Looking at tax planning. I am 62, and have one child. Also a large pension.",
})

# Reviewed 2026-07-17: no names/companies/addresses; kept as-is.
OVERRIDES.update({
    "4799b085": "Situation: Dear Sir/Madam,\n\nMy wife and I are planning to buy a property in England for around £445,000 as our main residence. I am a first-time buyer, and My wife is on a land registry of a commercial property with her parents, and also as a trust in another residential property. and we're unsure whether this means we'll have to pay the higher rate of SDLT.\n\nCould you advise whether the higher rate applies and whether there are any legitimate options to reduce or avoid it? Please also let me know your fees and availability for a consultation.\n\nPrompted by: advice\n\nWants from call: advice",
})
