import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

const SLUG_TO_CATEGORY_MAP: Record<string, string> = {
  "accountant-accounting-services": "property-accountant-services",
  "accountant-corporation-tax-property-companies": "incorporation-and-company-structures",
  "accountant-payroll-services": "incorporation-and-company-structures",
  "accountants-that-specialise-in-property": "portfolio-management",
  "average-accountant-salary-manchester": "portfolio-management",
  "best-mtd-software-landlords-2026": "making-tax-digital-mtd",
  "best-property-accountant-london": "property-accountant-services",
  "best-property-accountant-near-me": "portfolio-management",
  "best-property-accountants-london": "portfolio-management",
  "best-property-accountants-uk": "portfolio-management",
  "birmingham-property-accountant": "property-accountant-services",
  "bristol-property-accountant": "property-accountant-services",
  "buy-to-let-limited-company-complete-guide-uk": "incorporation-and-company-structures",
  "buy-to-let-limited-company-mortgage": "incorporation-and-company-structures",
  "buy-to-let-limited-company-mortgage-options": "incorporation-and-company-structures",
  "buy-to-let-refinancing-when-does-it-make-sense": "section-24-and-tax-relief",
  "capital-gains-tax-property-complete-guide-uk": "capital-gains-tax",
  "capital-gains-tax-property-sale-uk-2026": "capital-gains-tax",
  "capital-gains-tax-property-sale-uk-2026-rates-allowances": "capital-gains-tax",
  "cgt-payment-deadlines-property-sales-2026": "capital-gains-tax",
  "cgt-property-transfer-limited-company-calculate": "capital-gains-tax",
  "cgt-property-transfer-spouse": "capital-gains-tax",
  "cgt-property-transfer-spouse-exempt": "capital-gains-tax",
  "coventry-property-accountant": "property-accountant-services",
  "director-loan-property-company": "incorporation-and-company-structures",
  "do-i-need-a-property-accountant-complete-guide": "portfolio-management",
  "furnished-holiday-let-tax-rules-exemptions": "section-24-and-tax-relief",
  "hmo-landlord-accounting-multi-tenant-property-tax": "landlord-tax-essentials",
  "how-much-do-accountants-make-in-london": "portfolio-management",
  "how-much-do-property-accountants-make": "portfolio-management",
  "how-much-does-a-property-accountant-cost": "property-accountant-services",
  "how-much-does-property-accountant-cost-uk": "portfolio-management",
  "how-much-is-a-property-accountant": "portfolio-management",
  "how-to-become-property-accountant": "property-accountant-services",
  "how-to-choose-a-property-accountant": "property-accountant-services",
  "how-to-choose-property-accountant": "portfolio-management",
  "how-to-find-a-property-accountant": "portfolio-management",
  "how-to-transfer-property-into-limited-company-uk": "incorporation-and-company-structures",
  "incorporate-rental-property-without-cgt": "incorporation-and-company-structures",
  "incorporation-case-study-5-property-portfolio-analysis": "incorporation-and-company-structures",
  "incorporation-cost-calculator-cgt-sdlt-implications": "incorporation-and-company-structures",
  "incorporation-existing-portfolios-phased-approach": "incorporation-and-company-structures",
  "incorporation-holdover-relief-property": "incorporation-and-company-structures",
  "incorporation-timing-when-to-incorporate-property-portfolio": "incorporation-and-company-structures",
  "investment-property-accountant-near-me": "portfolio-management",
  "investment-property-accounting-uk-expert-services": "portfolio-management",
  "landlord-accounting-software-uk-2026": "portfolio-management",
  "landlord-accounting-software-uk-best-options-2026": "making-tax-digital-mtd",
  "landlord-capital-allowances-maximizing-tax-relief": "section-24-and-tax-relief",
  "landlord-capital-allowances-tax-relief": "section-24-and-tax-relief",
  "landlord-incorporation-step-by-step-guide-uk": "incorporation-and-company-structures",
  "landlord-insurance-tax-deductible": "section-24-and-tax-relief",
  "landlord-insurance-tax-deductible-what-can-you-claim": "section-24-and-tax-relief",
  "landlord-tax-accountant-when-you-need-professional-help": "portfolio-management",
  "landlord-tax-deductions-uk-2026-complete-list": "section-24-and-tax-relief",
  "landlord-tax-return-complete-guide-2026": "landlord-tax-essentials",
  "landlord-tax-return-deadline-2026": "making-tax-digital-mtd",
  "landlord-tax-return-self-assessment": "section-24-and-tax-relief",
  "landlord-vat-registration-when-required": "landlord-tax-essentials",
  "limited-company-vs-personal-ownership-tax-comparison-2026": "incorporation-and-company-structures",
  "local-property-accountant-expert-services": "portfolio-management",
  "london-property-accountant": "property-accountant-services",
  "london-property-accountants-expert-services": "portfolio-management",
  "making-tax-digital-landlords-april-2026": "making-tax-digital-mtd",
  "making-tax-digital-landlords-april-2026-deadline": "making-tax-digital-mtd",
  "manchester-property-accountant": "property-accountant-services",
  "mortgage-interest-tax-relief-changes-landlords": "section-24-and-tax-relief",
  "mtd-rental-income-threshold-exemptions": "making-tax-digital-mtd",
  "principal-private-residence-relief-landlords": "capital-gains-tax",
  "property-accountant-advice-complete-guide": "portfolio-management",
  "property-accountant-birmingham": "portfolio-management",
  "property-accountant-bristol": "portfolio-management",
  "property-accountant-cost-complete-guide": "portfolio-management",
  "property-accountant-cost-guide": "portfolio-management",
  "property-accountant-fees-complete-guide": "portfolio-management",
  "property-accountant-fees-guide": "portfolio-management",
  "property-accountant-glasgow": "property-accountant-services",
  "property-accountant-help": "portfolio-management",
  "property-accountant-job-description": "portfolio-management",
  "property-accountant-jobs": "portfolio-management",
  "property-accountant-jobs-london": "portfolio-management",
  "property-accountant-jobs-manchester": "portfolio-management",
  "property-accountant-jobs-near-me": "portfolio-management",
  "property-accountant-jobs-remote": "portfolio-management",
  "property-accountant-jobs-uk": "property-accountant-services",
  "property-accountant-leicester": "property-accountant-services",
  "property-accountant-london-expert-services": "portfolio-management",
  "property-accountant-london-jobs": "portfolio-management",
  "property-accountant-near-me": "property-accountant-services",
  "property-accountant-responsibilities-complete-guide": "portfolio-management",
  "property-accountant-salary-complete-guide": "property-accountant-services",
  "property-accountant-salary-london": "portfolio-management",
  "property-accountant-salary-uk-guide": "portfolio-management",
  "property-accountant-services": "property-accountant-services",
  "property-accountant-services-expert-solutions": "portfolio-management",
  "property-accountant-vs-general-accountant": "property-accountant-services",
  "property-accountants-manchester": "portfolio-management",
  "property-accountants-near-me": "portfolio-management",
  "property-accounting-course-uk-expert-services": "portfolio-management",
  "property-accounting-services": "portfolio-management",
  "property-accounting-services-london": "portfolio-management",
  "property-bookkeeping-services": "portfolio-management",
  "property-business-rates-council-tax-landlords": "landlord-tax-essentials",
  "property-capital-gains-tax-calculator": "capital-gains-tax",
  "property-company-dividend-tax": "incorporation-and-company-structures",
  "property-company-profit-extraction-salary-vs-dividends": "incorporation-and-company-structures",
  "property-disposal-tax-planning-minimize-cgt": "capital-gains-tax",
  "property-financial-planning-expert-services": "portfolio-management",
  "property-investment-company-structure-planning": "incorporation-and-company-structures",
  "property-investment-tax-uk-complete-guide-2026": "landlord-tax-essentials",
  "property-jobs-in-manchester": "portfolio-management",
  "property-management-accounting-services": "property-accountant-services",
  "property-management-accounts-monthly-tracking": "portfolio-management",
  "property-payroll-services": "incorporation-and-company-structures",
  "property-portfolio-accounting-monthly-tracking": "portfolio-management",
  "property-portfolio-accounting-tracking-profitability": "portfolio-management",
  "property-self-assessment-expert-services": "portfolio-management",
  "property-specialist-accountant-near-me": "portfolio-management",
  "property-specialist-tax-accountant-uk": "portfolio-management",
  "property-tax-accountant-birmingham": "portfolio-management",
  "property-tax-accountant-london": "portfolio-management",
  "property-tax-accountant-manchester": "portfolio-management",
  "property-tax-accountant-near-me": "portfolio-management",
  "property-tax-advice-expert-services": "portfolio-management",
  "property-tax-planning-expert-services": "portfolio-management",
  "property-tax-return-expert-services": "portfolio-management",
  "property-vat-registration-expert-services": "portfolio-management",
  "reduce-cgt-property-disposal-uk": "capital-gains-tax",
  "rental-income-tax-calculator": "section-24-and-tax-relief",
  "rental-income-tax-uk-complete-guide-landlords": "section-24-and-tax-relief",
  "rental-property-accountant-near-me": "portfolio-management",
  "rental-yield-calculation-gross-vs-net-yield": "portfolio-management",
  "rental-yield-calculator-guide-uk-landlords": "landlord-tax-essentials",
  "residential-property-developer-tax-uk": "incorporation-and-company-structures",
  "sdlt-incorporation-stamp-duty-twice": "incorporation-and-company-structures",
  "section-24-basic-rate-taxpayer-affected": "section-24-and-tax-relief",
  "section-24-basic-rate-taxpayers": "section-24-and-tax-relief",
  "section-24-calculator": "section-24-and-tax-relief",
  "section-24-case-study-100k-rental-income-portfolio": "section-24-and-tax-relief",
  "section-24-higher-rate-taxpayers-2026": "section-24-and-tax-relief",
  "section-24-mortgage-interest-restriction-explained": "section-24-and-tax-relief",
  "section-24-mortgage-interest-restriction-uk-landlords": "section-24-and-tax-relief",
  "section-24-pension-contributions-tax-planning": "section-24-and-tax-relief",
  "section-24-relief-how-much-can-i-claim-2026": "section-24-and-tax-relief",
  "section-24-repeal-future-reversed": "section-24-and-tax-relief",
  "section-24-tax-calculator-annual-cost": "section-24-and-tax-relief",
  "section-24-tax-relief-complete-guide": "section-24-and-tax-relief",
  "section-24-vs-incorporation-tax-savings": "section-24-and-tax-relief",
  "section-24-vs-incorporation-which-saves-more-tax": "section-24-and-tax-relief",
  "senior-property-accountant-london": "portfolio-management",
  "should-i-incorporate-buy-to-let-portfolio-2026": "incorporation-and-company-structures",
  "stamp-duty-buy-to-let-surcharge": "landlord-tax-essentials",
  "stamp-duty-buy-to-let-surcharge-explained": "portfolio-management",
  "uk-property-accountants-london-expert-services": "portfolio-management",
  "2027-property-tax-rates-section-24-relief-uk-landlords": "section-24-and-tax-relief",
  "what-does-a-property-accountant-do": "property-accountant-services",
  "when-to-incorporate-property-portfolio-timing": "incorporation-and-company-structures",
  "why-do-we-need-accountants-property-investors": "portfolio-management",
  "mortgage-interest-deductible-landlords-uk-2026": "section-24-and-tax-relief",
  "section-24-higher-rate-taxpayers-changes-2027": "section-24-and-tax-relief",
  "2027-tax-rates-incorporation-decision-uk-landlords": "incorporation-and-company-structures",
  "corporation-tax-vs-income-tax-landlords-2027": "incorporation-and-company-structures",
  "section-24-2027-tax-year-planning-uk-landlords": "section-24-and-tax-relief",
  "cgt-selling-buy-to-let-property-calculation-guide": "capital-gains-tax",
  "how-to-report-property-sale-hmrc-60-days": "capital-gains-tax",
  "landlord-tax-calendar-2026-27-key-dates": "landlord-tax-essentials",
  "60-day-cgt-reporting-property-sales-rule": "capital-gains-tax",
  "2027-property-tax-rates-affect-capital-gains-tax-sales": "capital-gains-tax",
  "section-24-2027-tax-year-planning-landlords": "section-24-and-tax-relief",
  "2027-tax-rates-incorporation-decision-property-landlords": "incorporation-and-company-structures",
  "cgt-property-2027-rate-changes-uk-landlords": "capital-gains-tax",
  "report-property-sale-hmrc-60-days-guide": "capital-gains-tax",
  "2027-property-tax-rates-cgt-capital-gains-changes": "capital-gains-tax",
  "60-day-cgt-reporting-property-sales-complete-guide": "capital-gains-tax",
  "cgt-calculation-selling-buy-to-let-property-step-by-step": "capital-gains-tax",
  "hmo-tax-guide-rental-income-deductions-multi-tenant": "property-types-and-specialist-tax",
  "how-much-tax-rental-income-uk-complete-guide": "landlord-tax-essentials",
  "income-tax-rates-landlords-2026-27-complete-guide": "landlord-tax-essentials",
  "airbnb-tax-uk-short-term-rental-income-taxed": "property-types-and-specialist-tax",
  "serviced-accommodation-tax-fhl-abolition-april-2025": "property-types-and-specialist-tax",
  "first-time-landlord-tax-guide-everything-you-need-to-know": "landlord-tax-essentials",
  "2027-property-income-tax-rates-landlords-uk": "landlord-tax-essentials",
  "how-to-register-mtd-landlord-step-by-step-guide": "making-tax-digital-mtd",
  "mtd-quarterly-reporting-landlords-step-by-step-guide": "making-tax-digital-mtd",
  "making-tax-digital-property-income-2026-complete-guide": "making-tax-digital-mtd",
  "tax-sell-rental-property-uk": "capital-gains-tax",
  "landlord-tax-changes-2026-complete-guide": "landlord-tax-essentials",
  "non-resident-landlord-scheme-uk-complete-guide": "non-resident-landlord-tax",
  "mtd-quarterly-deadlines-2026-2027-landlords": "making-tax-digital-mtd",
  "what-services-buy-to-let-accountant": "property-accountant-services",
  "liverpool-property-accountant-tax-services-landlords": "property-accountant-services",
  "newcastle-property-accountant-landlord-tax-services": "property-accountant-services",
  "why-sheffield-landlords-need-property-accountant": "property-accountant-services",
  "property-accountant-edinburgh-landlord-tax-services": "property-accountant-services",
  "section-24-higher-rate-threshold-landlords": "section-24-and-tax-relief",
  "claim-mortgage-interest-rental-property-uk-section-24": "section-24-and-tax-relief",
  "section-24-tax-credit-20-percent-basic-rate-relief": "section-24-and-tax-relief",
  "what-should-property-investors-expect-from-specialist-accountants": "property-accountant-services",
  "leeds-property-accountant-specialist-tax-services": "property-accountant-services",
  "capital-vs-revenue-expenditure-landlord-uk": "landlord-tax-essentials",
  "sdlt-transfer-property-company-cost": "incorporation-and-company-structures",
  "tax-efficient-property-investment-structure-guide": "incorporation-and-company-structures",
  "types-of-property-company-structure-uk-guide": "incorporation-and-company-structures",
  "how-to-choose-right-property-company-structure-uk-landlords-2026": "incorporation-and-company-structures",
  "section-162-incorporation-relief-property-landlords": "incorporation-and-company-structures",
  "corporation-tax-rates-property-companies-2026-27": "incorporation-and-company-structures",
  "property-company-running-costs-annual-budget": "incorporation-and-company-structures",
  "how-to-set-up-property-investment-company-uk-guide": "incorporation-and-company-structures",
  "section-24-personal-allowance-60-percent-tax-rate-landlords": "section-24-and-tax-relief",
  "can-section-24-push-higher-rate-tax": "section-24-and-tax-relief",
  "spv-property-investment-special-purpose-vehicle-guide": "incorporation-and-company-structures",
  "how-to-calculate-section-24-tax-credit-step-by-step": "section-24-and-tax-relief",
  "tax-relief-mortgage-interest-rented-property-guide": "section-24-and-tax-relief",
  "what-repairs-can-landlords-deduct-from-rental-income": "landlord-tax-essentials",
  "how-to-scale-buy-to-let-portfolio-1-to-10-properties": "portfolio-management",
  "track-rental-property-profitability-per-property-pl-guide": "portfolio-management",
  "buy-to-let-limited-company-mortgage-rates-2026-market-guide": "incorporation-and-company-structures",
  "non-resident-cgt-uk-property-rates-reporting": "non-resident-landlord-tax",
  "cgt-inherited-rental-property-calculation-uk": "capital-gains-tax",
  "hmrc-penalties-late-landlord-tax-returns-2026": "landlord-tax-essentials",
  "deposit-buy-to-let-2026-mortgage-requirements": "landlord-tax-essentials",
  "end-tax-year-checklist-landlords-april-2026": "landlord-tax-essentials",
  "how-to-calculate-net-rental-income-after-all-costs-uk-guide": "landlord-tax-essentials",
  "landlord-accounting-spreadsheet-template-free-excel-guide": "landlord-tax-essentials",
  "record-keeping-landlords-what-track-how-long-keep": "landlord-tax-essentials",
  "property-investment-benchmarks-uk-2026-good-yield": "portfolio-management",
  "ppr-relief-calculation-former-home-step-by-step": "capital-gains-tax",
  "hmo-vs-standard-buy-to-let-tax-comparison": "property-types-and-specialist-tax",
  "inheritance-tax-rental-property-uk-guide": "landlord-tax-essentials",
  "hmo-licensing-costs-tax-deductible": "property-types-and-specialist-tax",
  "cgt-annual-exempt-amount-3000-allowance-2026-27": "capital-gains-tax",
  "cgt-rates-property-2026-27-current-rates-explained": "capital-gains-tax",
  "capital-allowances-commercial-property-what-can-claim": "property-types-and-specialist-tax",
  "commercial-property-tax-landlords-rates-reliefs-allowances": "property-types-and-specialist-tax",
  "serviced-accommodation-vs-buy-to-let-tax-comparison-2026": "property-types-and-specialist-tax",
  "holiday-let-tax-calculator-fhl-changes": "property-types-and-specialist-tax",
  "property-development-tax-trading-vs-investment-income": "property-types-and-specialist-tax",
  "how-much-tax-holiday-let-property-uk": "property-types-and-specialist-tax",
  "sdlt-buy-to-let-rates-surcharge-guide-2025": "landlord-tax-essentials",
  "how-to-complete-landlord-self-assessment-filing-step-by-step-guide": "landlord-tax-essentials",
  "penalties-not-declaring-rental-income-hmrc": "landlord-tax-essentials",
  "renters-rights-act-2026-tax-implications-landlords": "landlord-tax-essentials",
  "mtd-penalties-landlords-miss-deadline": "making-tax-digital-mtd",
  "mtd-software-landlords-free-vs-paid-options-compared": "making-tax-digital-mtd",
  "mtd-record-keeping-landlords-digital-requirements": "making-tax-digital-mtd",
  "mtd-10000-threshold-when-does-it-apply": "making-tax-digital-mtd",
  "hmo-licensing-fees-tax-deductible-uk-landlords": "property-types-and-specialist-tax",
  "uk-property-income-expats-tax-obligations-explained": "non-resident-landlord-tax",
  "nrl-withholding-tax-20-percent-basic-rate-deduction": "non-resident-landlord-tax",
  "nrl-approval-receive-rent-gross-hmrc-guide": "non-resident-landlord-tax",
  "non-resident-landlord-self-assessment-filing-requirements": "non-resident-landlord-tax",
  "sa105-property-income-form-2026-complete-guide": "landlord-tax-essentials",
  "non-resident-cgt-selling-uk-property-overseas-guide": "non-resident-landlord-tax",
  "how-to-switch-self-assessment-mtd-property-income": "making-tax-digital-mtd",
  "peterborough-property-accountant-specialist-tax-services": "property-accountant-services",
  "property-accountant-stockport-landlords": "property-accountant-services",
  "slough-property-accountant-landlord-tax-services": "property-accountant-services",
  "cambridge-property-accountant-landlord-tax-services": "property-accountant-services",
  "brighton-property-accountant-specialist-tax-services": "property-accountant-services",
  "why-luton-landlords-need-specialist-property-accountant-2026": "property-accountant-services",
  "why-southampton-landlords-need-property-accountant": "property-accountant-services",
  "property-accountant-nottingham-landlords": "property-accountant-services",
  "why-cardiff-landlords-need-specialist-property-accountant-2026": "property-accountant-services",
  "property-accountant-warrington-landlord-services-2026": "property-accountant-services",
  "swindon-property-accountant-specialist-tax-services": "property-accountant-services",
  "property-accountant-middlesbrough-specialist-tax-services": "property-accountant-services",
  "property-accountant-preston-expert-tax-services-local-landlords": "property-accountant-services",
  "ipswich-property-accountant-tax-services-local-landlords": "property-accountant-services",
  "cheltenham-property-accountant-landlord-tax-services": "property-accountant-services",
  "property-accountant-bournemouth-landlords-tax-services": "property-accountant-services",
  "property-accountant-northampton-expert-services": "property-accountant-services",
  "property-accountant-milton-keynes-landlord-guide": "property-accountant-services",
  "belfast-property-accountant-specialist-tax-services": "property-accountant-services",
  "property-accountant-swansea-landlord-tax-services": "property-accountant-services",
  "property-accountant-dundee-landlord-tax-services": "property-accountant-services",
  "property-accountant-aberdeen-landlords-tax-services": "property-accountant-services",
  "portsmouth-property-accountant-landlord-tax-services": "property-accountant-services",
  "property-accountant-wolverhampton-specialist-tax-services": "property-accountant-services",
  "section-24-remortgaging-btl-property-tax-implications": "section-24-and-tax-relief",
  "section-24-employment-income-paye-landlords": "section-24-and-tax-relief",
  "derby-property-accountant-specialist-tax-services-local-landlords": "property-accountant-services",
  "exeter-property-accountant-specialist-tax-services": "property-accountant-services",
  "section-24-multiple-properties-cumulative-impact": "section-24-and-tax-relief",
  "section-24-joint-property-ownership-tax-split": "section-24-and-tax-relief",
  "online-property-accountant-remote-accounting": "property-accountant-services",
  "sunderland-property-accountant-specialist-tax-services": "property-accountant-services",
  "property-accountant-norwich-landlords-2026": "property-accountant-services",
  "property-accountant-bath-expert-tax-services-local-landlords": "property-accountant-services",
  "york-property-accountant-landlord-tax-services": "property-accountant-services",
  "plymouth-property-accountant-local-landlord-tax-services": "property-accountant-services",
  "property-accountant-reading-specialist-tax-services": "property-accountant-services",
  "property-accountant-oxford-guide-local-landlords": "property-accountant-services",
  "property-company-employer-pension-contributions-directors": "incorporation-and-company-structures",
  "incorporation-case-study-10-property-portfolio-200k-mortgage": "incorporation-and-company-structures",
  "transfer-properties-to-company-phased-guide": "incorporation-and-company-structures",
  "section-24-worked-example-50k-rental-income-portfolio": "section-24-and-tax-relief",
  "finance-costs-section-24-complete-guide": "section-24-and-tax-relief",
  "mortgage-arrangement-fees-deductible-landlord": "section-24-and-tax-relief",
  "when-does-hmrc-accept-rental-property-incorporation-business": "incorporation-and-company-structures",
  "property-portfolio-review-checklist-landlords-2026": "portfolio-management",
  "refinancing-rental-property-when-does-it-make-financial-sense": "portfolio-management",
  "replacement-domestic-items-relief-uk-landlords-guide": "section-24-and-tax-relief",
  "property-company-accounting-requirements-hmrc-expectations": "incorporation-and-company-structures",
  "llp-property-investment-worth-considering": "incorporation-and-company-structures",
  "section-24-self-assessment-tax-return": "section-24-and-tax-relief",
  "when-to-sell-rental-property-key-indicators-landlords": "portfolio-management",
  "rental-yield-vs-roi-property-investors-uk": "portfolio-management",
  "when-does-property-holding-company-structure-make-sense-uk-landlords": "incorporation-and-company-structures",
  "pre-letting-expenses-landlord-claim-before-first-tenant": "landlord-tax-essentials",
  "section-24-child-benefit-high-income-charge-landlords": "section-24-and-tax-relief",
  "section-24-commercial-property-complete-guide": "property-types-and-specialist-tax",
  "retained-profits-property-company-tax-advantages": "incorporation-and-company-structures",
  "section-24-interest-only-mortgage-tax-planning": "section-24-and-tax-relief",
  "rent-a-room-relief-uk-landlords-lodgers-guide": "section-24-and-tax-relief",
  "family-investment-company-property-worth-it": "incorporation-and-company-structures",
  "what-is-good-gross-yield-buy-to-let-property-2026": "portfolio-management",
  "reduce-void-periods-rental-properties-uk-landlords": "portfolio-management",
  "landlord-insurance-guide-types-costs-tax-deductible": "landlord-tax-essentials",
  "property-investment-exit-strategy-planning-guide": "portfolio-management",
  "letting-relief-landlords-2026-changes": "capital-gains-tax",
  "multi-property-landlord-tax-planning-strategies-5-plus-properties": "portfolio-management",
  "cgt-property-sold-loss-claim-capital-losses": "capital-gains-tax",
  "cgt-commercial-property-different-residential": "capital-gains-tax",
  "rollover-relief-property-landlords": "capital-gains-tax",
  "cgt-gifting-property-family-members-uk": "capital-gains-tax",
  "cgt-divorce-property-transfer-tax-implications": "capital-gains-tax",
};

const DUPLICATE_REDIRECTS: Record<string, string> = {
  "accountants-that-specialise-in-property": "/blog/property-accountant-services/property-accountant-vs-general-accountant",
  "average-accountant-salary-manchester": "/blog/property-accountant-services/property-accountant-salary-complete-guide",
  "best-property-accountant-near-me": "/blog/property-accountant-services/how-to-choose-a-property-accountant",
  "best-property-accountants-london": "/blog/property-accountant-services/best-property-accountant-london",
  "best-property-accountants-uk": "/blog/property-accountant-services/how-to-choose-a-property-accountant",
  "buy-to-let-limited-company-mortgage": "/blog/incorporation-and-company-structures/buy-to-let-limited-company-mortgage-options",
  "capital-gains-tax-property-sale-uk-2026": "/blog/capital-gains-tax/capital-gains-tax-property-sale-uk-2026-rates-allowances",
  "cgt-property-transfer-spouse-exempt": "/blog/capital-gains-tax/cgt-property-transfer-spouse",
  "do-i-need-a-property-accountant-complete-guide": "/blog/property-accountant-services/how-to-choose-a-property-accountant",
  "how-much-do-accountants-make-in-london": "/blog/property-accountant-services/property-accountant-salary-complete-guide",
  "how-much-do-property-accountants-make": "/blog/property-accountant-services/property-accountant-salary-complete-guide",
  "how-much-does-property-accountant-cost-uk": "/blog/property-accountant-services/how-much-does-a-property-accountant-cost",
  "how-much-is-a-property-accountant": "/blog/property-accountant-services/how-much-does-a-property-accountant-cost",
  "how-to-choose-property-accountant": "/blog/property-accountant-services/how-to-choose-a-property-accountant",
  "how-to-find-a-property-accountant": "/blog/property-accountant-services/how-to-choose-a-property-accountant",
  "investment-property-accountant-near-me": "/blog/property-accountant-services/property-accountant-near-me",
  "investment-property-accounting-uk-expert-services": "/blog/property-accountant-services/property-accountant-services",
  "landlord-accounting-software-uk-2026": "/blog/making-tax-digital-mtd/landlord-accounting-software-uk-best-options-2026",
  "landlord-capital-allowances-maximizing-tax-relief": "/blog/section-24-and-tax-relief/landlord-capital-allowances-tax-relief",
  "landlord-insurance-tax-deductible-what-can-you-claim": "/blog/section-24-and-tax-relief/landlord-insurance-tax-deductible",
  "landlord-tax-accountant-when-you-need-professional-help": "/blog/property-accountant-services/how-to-choose-a-property-accountant",
  "landlord-tax-return-self-assessment": "/blog/landlord-tax-essentials/landlord-tax-return-complete-guide-2026",
  "local-property-accountant-expert-services": "/blog/property-accountant-services/how-to-choose-a-property-accountant",
  "london-property-accountants-expert-services": "/blog/property-accountant-services/london-property-accountant",
  "making-tax-digital-landlords-april-2026": "/blog/making-tax-digital-mtd/making-tax-digital-landlords-april-2026-deadline",
  "mortgage-interest-tax-relief-changes-landlords": "/blog/section-24-and-tax-relief/section-24-mortgage-interest-restriction-uk-landlords",
  "property-accountant-advice-complete-guide": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "property-accountant-birmingham": "/blog/property-accountant-services/birmingham-property-accountant",
  "property-accountant-bristol": "/blog/property-accountant-services/bristol-property-accountant",
  "property-accountant-cost-complete-guide": "/blog/property-accountant-services/how-much-does-a-property-accountant-cost",
  "property-accountant-cost-guide": "/blog/property-accountant-services/how-much-does-a-property-accountant-cost",
  "property-accountant-fees-complete-guide": "/blog/property-accountant-services/how-much-does-a-property-accountant-cost",
  "property-accountant-fees-guide": "/blog/property-accountant-services/how-much-does-a-property-accountant-cost",
  "property-accountant-help": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "property-accountant-job-description": "/blog/property-accountant-services/property-accountant-jobs-uk",
  "property-accountant-jobs": "/blog/property-accountant-services/property-accountant-jobs-uk",
  "property-accountant-jobs-london": "/blog/property-accountant-services/property-accountant-jobs-uk",
  "property-accountant-jobs-manchester": "/blog/property-accountant-services/property-accountant-jobs-uk",
  "property-accountant-jobs-near-me": "/blog/property-accountant-services/property-accountant-jobs-uk",
  "property-accountant-jobs-remote": "/blog/property-accountant-services/property-accountant-jobs-uk",
  "property-accountant-london-expert-services": "/blog/property-accountant-services/london-property-accountant",
  "property-accountant-london-jobs": "/blog/property-accountant-services/property-accountant-jobs-uk",
  "property-accountant-responsibilities-complete-guide": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "property-accountant-salary-london": "/blog/property-accountant-services/property-accountant-salary-complete-guide",
  "property-accountant-salary-uk-guide": "/blog/property-accountant-services/property-accountant-salary-complete-guide",
  "property-accountant-services-expert-solutions": "/blog/property-accountant-services/property-accountant-services",
  "property-accountants-manchester": "/blog/property-accountant-services/manchester-property-accountant",
  "property-accountants-near-me": "/blog/property-accountant-services/property-accountant-near-me",
  "property-accounting-course-uk-expert-services": "/blog/property-accountant-services/how-to-become-property-accountant",
  "property-accounting-services": "/blog/property-accountant-services/property-accountant-services",
  "property-accounting-services-london": "/blog/property-accountant-services/london-property-accountant",
  "property-bookkeeping-services": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "property-disposal-tax-planning-minimize-cgt": "/blog/capital-gains-tax/reduce-cgt-property-disposal-uk",
  "property-financial-planning-expert-services": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "property-jobs-in-manchester": "/blog/property-accountant-services/property-accountant-jobs-uk",
  "property-management-accounts-monthly-tracking": "/blog/portfolio-management/property-portfolio-accounting-tracking-profitability",
  "property-payroll-services": "/blog/incorporation-and-company-structures/accountant-payroll-services",
  "property-portfolio-accounting-monthly-tracking": "/blog/portfolio-management/property-portfolio-accounting-tracking-profitability",
  "property-self-assessment-expert-services": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "property-specialist-accountant-near-me": "/blog/property-accountant-services/property-accountant-near-me",
  "property-specialist-tax-accountant-uk": "/blog/property-accountant-services/property-accountant-vs-general-accountant",
  "property-tax-accountant-birmingham": "/blog/property-accountant-services/birmingham-property-accountant",
  "property-tax-accountant-london": "/blog/property-accountant-services/london-property-accountant",
  "property-tax-accountant-manchester": "/blog/property-accountant-services/manchester-property-accountant",
  "property-tax-accountant-near-me": "/blog/property-accountant-services/property-accountant-near-me",
  "property-tax-advice-expert-services": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "property-tax-planning-expert-services": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "property-tax-return-expert-services": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "property-vat-registration-expert-services": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "rental-property-accountant-near-me": "/blog/property-accountant-services/property-accountant-near-me",
  "rental-yield-calculation-gross-vs-net-yield": "/blog/landlord-tax-essentials/rental-yield-calculator-guide-uk-landlords",
  "section-24-basic-rate-taxpayer-affected": "/blog/section-24-and-tax-relief/section-24-basic-rate-taxpayers",
  "section-24-mortgage-interest-restriction-explained": "/blog/section-24-and-tax-relief/section-24-mortgage-interest-restriction-uk-landlords",
  "section-24-relief-how-much-can-i-claim-2026": "/blog/section-24-and-tax-relief/section-24-calculator",
  "section-24-tax-calculator-annual-cost": "/blog/section-24-and-tax-relief/section-24-calculator",
  "section-24-vs-incorporation-tax-savings": "/blog/section-24-and-tax-relief/section-24-vs-incorporation-which-saves-more-tax",
  "senior-property-accountant-london": "/blog/property-accountant-services/property-accountant-jobs-uk",
  "should-i-incorporate-buy-to-let-portfolio-2026": "/blog/incorporation-and-company-structures/incorporation-timing-when-to-incorporate-property-portfolio",
  "stamp-duty-buy-to-let-surcharge-explained": "/blog/landlord-tax-essentials/stamp-duty-buy-to-let-surcharge",
  "uk-property-accountants-london-expert-services": "/blog/property-accountant-services/london-property-accountant",
  "when-to-incorporate-property-portfolio-timing": "/blog/incorporation-and-company-structures/incorporation-timing-when-to-incorporate-property-portfolio",
  "why-do-we-need-accountants-property-investors": "/blog/property-accountant-services/how-to-choose-a-property-accountant",
  // Consolidated dead posts → keepers
  "accountant-tax-advice-property-investors": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "accountant-tax-planning-services": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "accountant-tax-return-services": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "accountant-financial-planning-property-investors": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "accountant-vat-registration-expert-services": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "accountant-bookkeeping-services": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "accountant-self-assessment": "/blog/property-accountant-services/what-does-a-property-accountant-do",
  "best-property-accountant": "/blog/property-accountant-services/how-to-choose-a-property-accountant",
  "local-property-accountant": "/blog/property-accountant-services/how-to-choose-a-property-accountant",
  "when-to-hire-property-accountant": "/blog/property-accountant-services/how-to-choose-a-property-accountant",
};

const LOCATION_TO_BLOG: Record<string, string> = {
  "london": "/blog/property-accountant-services/london-property-accountant",
  "manchester": "/blog/property-accountant-services/manchester-property-accountant",
  "birmingham": "/blog/property-accountant-services/birmingham-property-accountant",
  "bristol": "/blog/property-accountant-services/bristol-property-accountant",
};

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Redirect /locations/[city] to corresponding blog post
  const locationMatch = pathname.match(/^\/locations\/([^\/]+)$/);
  if (locationMatch) {
    const city = locationMatch[1];
    const blogTarget = LOCATION_TO_BLOG[city];
    if (blogTarget) {
      return NextResponse.redirect(new URL(blogTarget, request.url), 301);
    }
  }

  // Redirect old flat /blog/[slug] to nested /blog/[category]/[slug]
  const oldBlogMatch = pathname.match(/^\/blog\/([^\/]+)$/);
  if (oldBlogMatch) {
    const slug = oldBlogMatch[1];
    const duplicateTarget = DUPLICATE_REDIRECTS[slug];
    if (duplicateTarget) {
      return NextResponse.redirect(new URL(duplicateTarget, request.url), 301);
    }
    const categorySlug = SLUG_TO_CATEGORY_MAP[slug];
    if (categorySlug) {
      return NextResponse.redirect(new URL(`/blog/${categorySlug}/${slug}`, request.url), 301);
    }
  }

  // Redirect old /blog/category/[slug] format
  const oldCategoryMatch = pathname.match(/^\/blog\/category\/([^\/]+)$/);
  if (oldCategoryMatch) {
    const categorySlug = oldCategoryMatch[1];
    return NextResponse.redirect(new URL(`/blog/${categorySlug}`, request.url), 301);
  }

  // Redirect consolidated duplicate posts to their keeper
  const nestedMatch = pathname.match(/^\/blog\/[^\/]+\/([^\/]+)$/);
  if (nestedMatch) {
    const slug = nestedMatch[1];
    const target = DUPLICATE_REDIRECTS[slug];
    if (target) {
      return NextResponse.redirect(new URL(target, request.url), 301);
    }
  }

  return NextResponse.next();
}

export const config = {
  matcher: ["/blog/:path*", "/locations/:path*"],
};
