/**
 * `.eyebrow` contrast floor: known consumers only.
 *
 * Incident (see globals.css:209 comment above `.eyebrow`): the class was moved
 * into `@layer components` so a consumer's Tailwind utility (e.g. text-orange-400)
 * can win over the class's own `color`. That is correct, but it is latent-unsafe:
 * `.eyebrow`'s DEFAULT colour is --accent-strong (#c2410c), which measures 5.18
 * on white (PASS) but only ~3.43 on this site's dark ground (bg-neutral-900 =
 * #171717) -- below the 4.5:1 text floor. /about and /contact only pass because
 * their authors also hand-wrote `text-orange-400` (#ff8904, 7.54 on dark). Nothing
 * in the CSS enforces that pairing, so a bare `className="eyebrow"` dropped into
 * a new dark band would silently render at ~3.43 and nothing would warn anybody.
 *
 * What this test CAN decide from source, and what it can't: telling "is this JSX
 * on a dark ground" apart from "is it on a light ground" is not reliably
 * decidable by grepping one file (ground can come from a parent layout, a CSS
 * var, conditional classes, etc). So this test does NOT attempt that judgement.
 * Instead it pins the exact set of `.eyebrow` occurrences known-good today (2
 * dark-ground consumers with an explicit colour utility, 1 light-ground consumer
 * on the safe default). Any NEW occurrence -- found by the same regex used here,
 * not a re-implementation of it -- fails the test outright and must be assessed
 * by a human against the numbers above. It also re-checks the two known dark
 * consumers still carry a real colour utility, so an edit that strips
 * `text-orange-400` (or the -300/-400/-500 orange family) back to a bare
 * `.eyebrow` on dark also fails.
 *
 * This CANNOT catch: a brand-new dark-ground consumer that happens to also add
 * some colour utility (any `text-*` class satisfies the "has a colour" check
 * here, not just a WCAG-safe one) -- that still needs a human contrast check.
 * It also cannot catch ground changes to the three known files (e.g. /not-found
 * turning its background dark) since it does not parse ground at all.
 *
 * When this fails: do not edit this file to make it pass. Either (a) the new/
 * changed eyebrow is on a dark ground -- give it an explicit on-dark-safe colour
 * utility (text-orange-400 measures 7.54, known-safe) and add it to
 * KNOWN_EYEBROW_CONSUMERS below, or (b) it is on white/light -- the bare default
 * (5.18) is fine, add it to KNOWN_EYEBROW_CONSUMERS as-is.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { join } from "path";
import { execSync } from "child_process";

const SRC = join(__dirname, "..", "..");

/** Every known-good `.eyebrow` occurrence, verified against disk. */
const KNOWN_EYEBROW_CONSUMERS = [
  { file: "app/about/page.tsx", line: 16 },
  { file: "app/contact/page.tsx", line: 20 },
  { file: "app/not-found.tsx", line: 8 },
  // Phase 2 / WP-B1. The article header card's category eyebrow. LIGHT ground:
  // the card is bg-neutral-50 (#fafafa) inside a bg-white <article>, and the
  // bare default --accent-strong (#c2410c) measures 4.96 there, above the 4.5
  // text floor, so no colour utility is wanted. Renders on all 82 articles.
  { file: "components/blog/BlogPostRenderer.tsx", line: 108 },
  // Phase 2 / WP-B5. LeadCTAPanel's two variants, spelled out as two literal
  // classNames rather than one conditional so this guard can see both.
  // DARK (navy variant): carries text-orange-400 (#ff8904), 7.54 on #171717 and
  // 10.59 on the panel's own ground --dark (#0f172a). LIGHT (contained variant,
  // the one /blog renders): bare default --accent-strong (#c2410c) on
  // --hero-cream (#fafaf7) = 4.95, above the 4.5 text floor.
  { file: "components/marketing/LeadCTAPanel.tsx", line: 129 },
  { file: "components/marketing/LeadCTAPanel.tsx", line: 131 },
];

/** Same className match used to enumerate occurrences AND to check the pinned ones. */
const EYEBROW_CLASS_RE = /className="eyebrow(\s[^"]*)?"/;

function findAllEyebrowOccurrences(): { file: string; line: number; text: string }[] {
  // ripgrep the real shipped source under src/app and src/components -- never
  // a re-implementation of the class, the literal className string itself.
  const out = execSync(
    `grep -rn --include="*.tsx" "className=\\"eyebrow" "${join(SRC, "app")}" "${join(SRC, "components")}"`,
    { encoding: "utf8" }
  );
  return out
    .trim()
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      const m = line.match(/^(.*?):(\d+):(.*)$/)!;
      const abs = m[1].replace(/\\/g, "/");
      const srcNorm = SRC.replace(/\\/g, "/");
      return { file: abs.replace(srcNorm + "/", ""), line: Number(m[2]), text: m[3] };
    });
}

describe(".eyebrow occurrences are the known-good set (contrast floor guard)", () => {
  it("guard-the-guard: the search itself finds the known consumers", () => {
    // If this is 0, the regex/paths are broken and every other assertion below
    // would pass vacuously -- fail loudly instead of silently.
    const found = findAllEyebrowOccurrences();
    expect(found.length).toBeGreaterThan(0);
    expect(found.length).toBe(KNOWN_EYEBROW_CONSUMERS.length);
  });

  it("no NEW .eyebrow consumer exists beyond the assessed set", () => {
    const found = findAllEyebrowOccurrences();
    const foundKeys = found.map((f) => `${f.file}:${f.line}`).sort();
    const knownKeys = KNOWN_EYEBROW_CONSUMERS.map((k) => `${k.file}:${k.line}`).sort();

    expect(foundKeys, [
      "New or moved .eyebrow occurrence(s) detected that are not in the assessed set.",
      "The floor: .eyebrow's default colour (--accent-strong #c2410c) measures",
      "5.18:1 on white (PASS) but only ~3.43:1 on this site's dark ground",
      "(bg-neutral-900 = #171717), below the 4.5:1 text floor.",
      "Two safe choices for a NEW eyebrow:",
      "  - on a LIGHT ground: leave it bare (`className=\"eyebrow\"`), 5.18:1 is fine.",
      "  - on a DARK ground: add `text-orange-400` (#ff8904, 7.54:1 on #171717),",
      "    same as /about and /contact.",
      "Then add the file:line to KNOWN_EYEBROW_CONSUMERS in this test.",
      `Found: ${foundKeys.join(", ")}`,
      `Known: ${knownKeys.join(", ")}`,
    ].join("\n")).toEqual(knownKeys);
  });

  it("both dark-ground consumers still carry an explicit colour utility", () => {
    const darkConsumers = ["app/about/page.tsx", "app/contact/page.tsx"];
    for (const file of darkConsumers) {
      const contents = readFileSync(join(SRC, ...file.split("/")), "utf8");
      const line = contents
        .split("\n")
        .find((l) => EYEBROW_CLASS_RE.test(l) && l.includes("eyebrow"));
      expect(line, `${file}: eyebrow line not found`).toBeDefined();
      expect(
        /text-orange-(300|400|500)/.test(line!),
        `${file}: dark-ground .eyebrow lost its colour utility -- restores the ` +
          `~3.43:1 default on #171717, below the 4.5:1 floor. Re-add text-orange-400.`
      ).toBe(true);
    }
  });
});
