/**
 * Anonymised buyer teaser for the lead offer pipeline.
 *
 * A teaser is what a prospective buyer sees BEFORE claiming: structured facts
 * from the value score plus a one-line anonymised situation summary. It must
 * never contain PII. Defence in depth:
 *   1. Composed only from non-PII structured fields (tier, intent, role, site).
 *   2. The situation line is generated by Claude under a data-minimised prompt
 *      (message + role only, explicit no-PII instruction), mirroring
 *      value-score.ts.
 *   3. A final regex pass strips anything that still looks like an email,
 *      phone number or UK postcode; if the line trips the regex it is dropped
 *      entirely rather than partially redacted.
 *
 * If the AI layer is unconfigured the teaser degrades to structured facts only.
 */
import { z } from "zod";
import { generateJson, anthropicConfigured } from "@/lib/ai/anthropic";
import { roleLabel, surfaceLabel } from "@/lib/leads/role-labels";

export type TeaserJson = {
  site: string;
  tier: string;
  est_band: string;
  intent: string;
  work_type: string;
  role: string;
  surface: string;
  submitted_date: string; // day precision only
  situation?: string;
  backlog?: boolean;
};

type LeadLike = {
  id?: string;
  role?: string | null;
  message?: string | null;
  source?: string | null;
  submitted_at?: string | null;
  created_at?: string | null;
  extras?: Record<string, unknown> | null;
};

type ScoreLike = {
  tier: string;
  est_value_gbp?: number;
  intent?: string;
  work_type?: string;
};

const EMAIL_RE = /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/;
const PHONE_RE = /(?:\+?\d[\d\s().-]{8,}\d)/;
const POSTCODE_RE = /\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b/i;

const SituationSchema = z.object({
  situation: z.string().max(320),
});

const SITUATION_SYSTEM = `You write one-line anonymised summaries of inbound enquiries to UK
accountancy firms, for a buyer firm deciding whether to purchase the lead. The summary sells
the situation, never the person.

Rules, absolute:
- NEVER include names of people, firms, employers, streets, towns, postcodes, emails, phone
  numbers, usernames or any other identifier. Refer to the person only by their role.
- Keep every tax-relevant fact: amounts, property counts, deadlines, HMRC interactions,
  structures, dispute points.
- One or two sentences, plain British English, no em-dashes.
- If the message is too thin to summarise, return an empty situation string.`;

export function prettySource(source?: string): string {
  if (!source) return "";
  return source
    .split(/[-_]/)
    .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
    .join(" ");
}

function estBand(est?: number): string {
  if (typeof est !== "number" || est <= 0) return "";
  if (est >= 5000) return "£5,000+";
  if (est >= 3000) return "£3,000–£5,000";
  if (est >= 1000) return "£1,000–£3,000";
  if (est >= 300) return "£300–£1,500";
  return "under £300";
}

/** Final defensive pass: any residual PII pattern kills the whole line. */
export function scrubSituation(line: string): string {
  const s = (line || "").trim();
  if (!s) return "";
  if (EMAIL_RE.test(s) || PHONE_RE.test(s) || POSTCODE_RE.test(s)) return "";
  return s;
}

async function generateSituation(lead: LeadLike): Promise<string> {
  const message = (lead.message ?? "").trim();
  if (!message || !anthropicConfigured()) return "";
  const result = await generateJson({
    model: "sonnet",
    system: SITUATION_SYSTEM,
    prompt: JSON.stringify({
      role_selected: lead.role ?? null,
      message: message.slice(0, 4000),
    }),
    schema: SituationSchema,
    maxTokens: 256,
    cacheSystem: true,
  });
  if (!result) return "";
  return scrubSituation(result.situation);
}

export async function buildTeaser(lead: LeadLike, score: ScoreLike): Promise<TeaserJson> {
  const submitted = lead.submitted_at || lead.created_at || "";
  const fid = typeof lead.extras?.form_id === "string" ? lead.extras.form_id : "";
  const teaser: TeaserJson = {
    site: prettySource(lead.source ?? undefined),
    tier: score.tier,
    est_band: estBand(score.est_value_gbp),
    intent: score.intent ?? "unknown",
    work_type: score.work_type ?? "unknown",
    role: roleLabel(lead.role) || "",
    surface: (fid && surfaceLabel(fid)) || "",
    submitted_date: submitted ? submitted.slice(0, 10) : "",
  };
  const situation = await generateSituation(lead);
  if (situation) teaser.situation = situation;
  return teaser;
}

/** Buyer-facing tier labels (DB uses very_high underscore form). */
export function tierLabel(tier: string): string {
  if (tier === "very_high") return "Very high";
  return tier ? tier[0].toUpperCase() + tier.slice(1) : "";
}
