/**
 * Anonymised buyer teaser for the lead offer pipeline.
 *
 * A teaser is what a prospective buyer sees BEFORE claiming: structured facts,
 * a one-line situation summary, and the enquiry in the enquirer's own words with
 * the identifying parts removed. Owner decision 2026-08-14: a firm decides on the
 * enquiry itself rather than on a summary of it, and receives the unredacted
 * enquiry and the contact details only if it claims.
 *
 * It must never contain PII. Defence in depth:
 *   1. Composed only from non-PII structured fields (tier, intent, role, site).
 *   2. The redacted message is the enquirer's text with emails, phone numbers,
 *      postcodes, links and company names replaced by markers.
 *   3. The situation line is generated by Claude under a data-minimised prompt
 *      (message + role only, explicit no-PII instruction), mirroring
 *      value-score.ts.
 *   4. A final regex pass over the situation line strips anything that still
 *      looks like an email, phone number or UK postcode; if the line trips the
 *      regex it is dropped entirely rather than partially redacted.
 *
 * If the AI layer is unconfigured the teaser degrades to structured facts plus
 * the redacted message, which is the part that matters.
 */
import { z } from "zod";
import { generateJson, anthropicConfigured } from "@/lib/ai/anthropic";
import { roleLabel, surfaceLabel } from "@/lib/leads/role-labels";
import { offerTierFor } from "@/lib/leads/offer-config";
import { CASE_TIERS, LEGACY_TIER_MAP, type OfferTier } from "@/lib/leads/tiers";

export type TeaserJson = {
  site: string;
  tier: string;
  /** Retired 2026-08-14, kept optional so teasers stored before then still parse. */
  est_band?: string;
  intent: string;
  work_type: string;
  role: string;
  surface: string;
  submitted_date: string; // day precision only
  situation?: string;
  /** The enquiry in the enquirer's own words, identifiers removed. */
  redacted_message?: string;
  backlog?: boolean;
};

type LeadLike = {
  id?: string;
  role?: string | null;
  message?: string | null;
  source?: string | null;
  submitted_at?: string | null;
  created_at?: string | null;
  extras?: Record<string, unknown> | null;
};

type ScoreLike = {
  tier: string;
  case_tier?: string | null;
  est_value_gbp?: number;
  intent?: string;
  work_type?: string;
};

const EMAIL_RE = /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/;
const PHONE_RE = /(?:\+?\d[\d\s().-]{8,}\d)/;
const POSTCODE_RE = /\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b/i;

/**
 * Global counterparts used to redact the enquiry itself. Kept separate from the
 * single-match regexes above, which only need to detect. Mirrors tiers.redact()
 * in the dry-run engine, so a firm sees the same thing whichever path serves it.
 */
const REDACTIONS: [RegExp, string][] = [
  [/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g, "[EMAIL]"],
  [/(?<!\d)(?:\+44\s?|\(?0)\d[\d\s().-]{7,}\d/g, "[PHONE]"],
  [/\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b/gi, "[POSTCODE]"],
  [/\bhttps?:\/\/\S+|\bwww\.\S+/gi, "[LINK]"],
  [/\b(?:[A-Z][\w&'-]*\s+){1,4}(?:Ltd|Limited|LLP|PLC|Plc|plc)\b/gi, "[COMPANY]"],
];

/**
 * The enquiry with direct identifiers removed, for the pre-claim alert.
 *
 * Two layers, both required (2026-08-15 fix: the redaction patterns were
 * case-sensitive while the detection patterns were not, so "sw1a 1aa" passed
 * to buyers unredacted in an email claiming identifiers were removed):
 *   1. token substitution via REDACTIONS (now case-insensitive);
 *   2. a kill-switch mirroring scrubSituation: if any detection pattern still
 *      matches after substitution (e.g. a phone number written without a
 *      leading 0 or +44), the whole message is withheld rather than leaked.
 */
export function redactMessage(message?: string | null): string {
  let text = (message ?? "").trim();
  if (!text) return "";
  for (const [rx, token] of REDACTIONS) text = text.replace(rx, token);
  if (EMAIL_RE.test(text) || PHONE_RE.test(text) || POSTCODE_RE.test(text)) return "";
  return text.replace(/\s+/g, " ").slice(0, 2000);
}

const SituationSchema = z.object({
  situation: z.string().max(320),
});

const SITUATION_SYSTEM = `You write one-line anonymised summaries of inbound enquiries to UK
accountancy firms, for a buyer firm deciding whether to purchase the lead. The summary sells
the situation, never the person.

Rules, absolute:
- NEVER include names of people, firms, employers, streets, towns, postcodes, emails, phone
  numbers, usernames or any other identifier. Refer to the person only by their role.
- Keep every tax-relevant fact: amounts, property counts, deadlines, HMRC interactions,
  structures, dispute points.
- One or two sentences, plain British English, no em-dashes.
- If the message is too thin to summarise, return an empty situation string.`;

export function prettySource(source?: string): string {
  if (!source) return "";
  return source
    .split(/[-_]/)
    .map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w))
    .join(" ");
}

// estBand() removed 2026-08-14. The alert used to carry a banded estimate of what
// the enquirer might be worth. Nothing prices that way any more: the rubric grades
// on case type only and expressly keeps the internal value score out of anything
// buyer-facing (docs/CLASSIFY.md), and DSA Annex A does not list it as shared data.

/** Final defensive pass: any residual PII pattern kills the whole line. */
export function scrubSituation(line: string): string {
  const s = (line || "").trim();
  if (!s) return "";
  if (EMAIL_RE.test(s) || PHONE_RE.test(s) || POSTCODE_RE.test(s)) return "";
  return s;
}

async function generateSituation(lead: LeadLike): Promise<string> {
  const message = (lead.message ?? "").trim();
  if (!message || !anthropicConfigured()) return "";
  const result = await generateJson({
    model: "sonnet",
    system: SITUATION_SYSTEM,
    prompt: JSON.stringify({
      role_selected: lead.role ?? null,
      message: message.slice(0, 4000),
    }),
    schema: SituationSchema,
    maxTokens: 256,
    cacheSystem: true,
  });
  if (!result) return "";
  return scrubSituation(result.situation);
}

export async function buildTeaser(lead: LeadLike, score: ScoreLike): Promise<TeaserJson> {
  const submitted = lead.submitted_at || lead.created_at || "";
  const fid = typeof lead.extras?.form_id === "string" ? lead.extras.form_id : "";
  const teaser: TeaserJson = {
    site: prettySource(lead.source ?? undefined),
    // Buyer-facing tier is the case tier (legacy rows map via LEGACY_TIER_MAP);
    // the internal value-score tier never reaches a buyer.
    tier: offerTierFor(score) ?? "",
    intent: score.intent ?? "unknown",
    work_type: score.work_type ?? "unknown",
    role: roleLabel(lead.role) || "",
    surface: (fid && surfaceLabel(fid)) || "",
    submitted_date: submitted ? submitted.slice(0, 10) : "",
  };
  const redacted = redactMessage(lead.message);
  if (redacted) teaser.redacted_message = redacted;
  const situation = await generateSituation(lead);
  if (situation) teaser.situation = situation;
  return teaser;
}

/**
 * Buyer-facing tier labels. Legacy value-score ids (stored in old teaser
 * jsonb) map through to their case-tier label so an old id never renders.
 */
export function tierLabel(tier: string): string {
  const resolved: OfferTier | undefined =
    tier in CASE_TIERS ? (tier as OfferTier) : LEGACY_TIER_MAP[tier];
  return resolved ? CASE_TIERS[resolved].label : "";
}
