"""
contractors-ir35 blog_topics coverage reconciliation.
Matches unused topics against live site inventory and flips used=true where clearly covered.
Run: python scripts/_ir35_coverage_reconcile.py [--dry-run]
"""
import json, sys, httpx

TOKEN = __import__("os").environ.get("SUPABASE_ACCESS_TOKEN") or [l.split("=",1)[1].strip() for l in open(".env") if l.startswith("SUPABASE_ACCESS_TOKEN=")][0]
PROJECT_REF = "dhlxwmvmkrfnmcgjbntk"
URL = f"https://api.supabase.com/v1/projects/{PROJECT_REF}/database/query"
DRY = "--dry-run" in sys.argv


def run(q):
    r = httpx.post(URL, headers={"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"},
                   json={"query": q}, timeout=120)
    if r.status_code not in (200, 201):
        raise Exception(f"SQL {r.status_code}: {r.text[:400]}")
    return r.json()


# ── site inventory mapping: primary_keyword (lower) → covering page ──────────
# Conservative: only flip when primary intent is directly served.
# "JUNK" = noise query (wrong product, insecticide, pop-culture); flip to clear pool.
COVERAGE = {
    # umbrella company explained
    "umbrella company": "blog/umbrella-company-explained",
    "umbrella companies explained": "blog/umbrella-company-explained",
    "umbrella company explained": "blog/umbrella-company-explained",
    "umbrella company meaning": "blog/umbrella-company-explained",
    "umbrella company uk": "blog/umbrella-company-explained",
    "umbrella company meaning uk": "blog/umbrella-company-explained",
    "umbrella company meaning in english": "blog/umbrella-company-explained",
    "what does umbrella company do": "blog/umbrella-company-explained",
    "umbrella company rules": "blog/umbrella-company-explained",
    "umbrella company limited": "blog/umbrella-company-explained",
    "umbrella company uk ltd": "blog/umbrella-company-explained",
    "is umbrella company paye": "blog/umbrella-company-explained",
    "is umbrella company self employed": "blog/umbrella-company-explained",
    "is umbrella company outside ir35": "blog/umbrella-company-explained",
    "is umbrella company better than paye": "blog/umbrella-company-explained",
    "is umbrella company inside ir35": "blog/umbrella-company-explained",
    "are umbrella companies legal": "blog/umbrella-company-explained",
    "are umbrella companies legal uk": "blog/umbrella-company-explained",
    "new umbrella company rules": "blog/umbrella-company-explained",
    "umbrella company rule changes": "blog/umbrella-company-explained",
    "umbrella company law": "blog/umbrella-company-explained",
    "umbrella company law changes": "blog/umbrella-company-explained",
    "umbrella company tax rules": "blog/umbrella-company-explained",
    "umbrella company rules 2026": "blog/umbrella-company-explained",
    "umbrella company regulation": "blog/umbrella-company-explained",
    "umbrella companies budget 2025": "blog/umbrella-company-explained",
    "how to use umbrella company": "blog/umbrella-company-explained",
    "how many umbrella companies are there in the uk": "blog/umbrella-company-explained",
    "how many umbrella companies in the uk": "blog/umbrella-company-explained",
    # best umbrella
    "umbrella companies to avoid": "blog/best-umbrella-company-how-to-choose",
    "can i change umbrella company mid contract": "blog/best-umbrella-company-how-to-choose",
    "can i change umbrella company": "blog/best-umbrella-company-how-to-choose",
    "umbrella company uk reviews": "blog/best-umbrella-company-how-to-choose",
    # umbrella deductions
    "how much does umbrella company take": "blog/umbrella-company-deductions-explained",
    "how much do umbrella companies take": "blog/umbrella-company-deductions-explained",
    "how much umbrella company charge": "blog/umbrella-company-deductions-explained",
    "how much do umbrella companies deduct": "blog/umbrella-company-deductions-explained",
    "how much do umbrella companies take off you": "blog/umbrella-company-deductions-explained",
    "how much does an umbrella company charge uk": "blog/umbrella-company-deductions-explained",
    "how much do umbrella companies charge per month": "blog/umbrella-company-deductions-explained",
    "how much do umbrella companies charge uk": "blog/umbrella-company-deductions-explained",
    "how much tax umbrella company": "blog/umbrella-company-deductions-explained",
    "umbrella company expenses rules": "blog/umbrella-company-deductions-explained",
    "what expenses can i claim with umbrella company": "blog/umbrella-company-deductions-explained",
    "what expenses can i claim through umbrella company": "blog/umbrella-company-deductions-explained",
    "can i claim expenses through umbrella company": "blog/umbrella-company-deductions-explained",
    # umbrella vs limited
    "umbrella vs limited company calculator": "calc/umbrella-vs-limited-calculator",
    "umbrella company calculator": "calc/umbrella-vs-limited-calculator",
    "umbrella company uk calculator": "calc/umbrella-vs-limited-calculator",
    "umbrella vs ltd company": "calc/umbrella-vs-limited-calculator",
    "umbrella or limited company": "calc/umbrella-vs-limited-calculator",
    "umbrella vs limited company": "calc/umbrella-vs-limited-calculator",
    "umbrella company vs limited company": "calc/umbrella-vs-limited-calculator",
    "paye umbrella or limited company": "calc/umbrella-vs-limited-calculator",
    "contractor umbrella vs limited company calculator": "calc/umbrella-vs-limited-calculator",
    "inside ir35 umbrella calculator": "calc/umbrella-vs-limited-calculator",
    "umbrella company vs limited company ireland": "blog/limited-company-vs-umbrella-contractor",
    "umbrella company vs limited company uk": "blog/limited-company-vs-umbrella-contractor",
    "ir35 umbrella or limited company": "blog/limited-company-vs-umbrella-contractor",
    "contractor umbrella or limited company": "blog/limited-company-vs-umbrella-contractor",
    # calculators
    "inside ir35 calculator": "calc/inside-ir35-take-home-calculator",
    "inside ir35 calculator uk": "calc/inside-ir35-take-home-calculator",
    "inside ir35 tax calculator": "calc/inside-ir35-take-home-calculator",
    "inside ir35 day rate calculator": "calc/inside-ir35-take-home-calculator",
    "inside ir35 salary calculator": "calc/inside-ir35-take-home-calculator",
    "inside ir35 salary calculator uk": "calc/inside-ir35-take-home-calculator",
    "inside ir35 calculator 2025": "calc/inside-ir35-take-home-calculator",
    "inside ir35 calculator gov uk": "calc/inside-ir35-take-home-calculator",
    "ir35 calculator": "calc/inside-ir35-take-home-calculator",
    "ir35 calculator 2025": "calc/inside-ir35-take-home-calculator",
    "ir35 uk calculator": "calc/inside-ir35-take-home-calculator",
    "limited company contractor tax calculator": "calc/contractor-salary-dividend-calculator",
    "limited company contractor tax calculator uk": "calc/contractor-salary-dividend-calculator",
    "outside ir35 calculator": "calc/outside-ir35-take-home-calculator",
    "outside ir35 calculator uk": "calc/outside-ir35-take-home-calculator",
    "how much tax outside ir35": "calc/outside-ir35-take-home-calculator",
    "how much is 400 per day outside ir35": "calc/outside-ir35-take-home-calculator",
    "how much is 500 per day outside ir35": "calc/outside-ir35-take-home-calculator",
    "how much is 600 per day outside ir35": "calc/outside-ir35-take-home-calculator",
    "how much will i earn outside ir35": "calc/outside-ir35-take-home-calculator",
    # outside ir35 blog
    "outside ir35": "blog/outside-ir35",
    "outside ir35 meaning": "blog/outside-ir35",
    "outside ir35 meaning uk": "blog/outside-ir35",
    "what does outside ir35 mean": "blog/outside-ir35",
    "what does outside ir35 mean uk": "blog/outside-ir35",
    "what does outside ir35 mean for contractors": "blog/outside-ir35",
    "what does outside ir35": "blog/outside-ir35",
    "outside ir35 uk": "blog/outside-ir35",
    "outside ir35 uk meaning": "blog/outside-ir35",
    "what's outside ir35": "blog/outside-ir35",
    "what outside ir35 means": "blog/outside-ir35",
    "what determines outside ir35": "blog/outside-ir35",
    "is outside ir35 better": "blog/outside-ir35",
    "is outside ir35 still worth it": "blog/outside-ir35",
    "is outside ir35 worth it": "blog/outside-ir35",
    "is outside ir35 good": "blog/outside-ir35",
    "is outside ir35": "blog/outside-ir35",
    "is outside ir35 self employed": "blog/outside-ir35",
    "is outside ir35 paye": "blog/outside-ir35",
    "is outside ir35 better than inside": "blog/outside-ir35",
    "does outside ir35 mean self employed": "blog/outside-ir35",
    "outside ir35 new rules": "blog/outside-ir35",
    "outside ir35 tax rules": "blog/outside-ir35",
    "outside ir35 rules": "blog/outside-ir35",
    "outside ir35 gov uk": "blog/outside-ir35",
    "how to stay outside ir35": "blog/outside-ir35",
    "how to be outside ir35": "blog/outside-ir35",
    "how to get outside ir35": "blog/outside-ir35",
    "how to contract outside ir35": "blog/outside-ir35",
    "how to ensure outside ir35": "blog/outside-ir35",
    "how to operate outside ir35": "blog/outside-ir35",
    "how to prove outside ir35": "blog/outside-ir35",
    "how outside ir35 works": "blog/outside-ir35",
    "can i work outside ir35": "blog/outside-ir35",
    "can i work outside ir35 as a sole trader": "blog/outside-ir35",
    "what makes a contract outside ir35": "blog/outside-ir35",
    "what does outside ir35 contract mean": "blog/outside-ir35",
    "outside ir35 contracts": "blog/outside-ir35",
    "outside ir35 contract jobs": "blog/outside-ir35",
    "outside ir35 jobs": "blog/outside-ir35",
    "outside ir35 roles": "blog/outside-ir35",
    "outside ir35 jobs remote": "blog/outside-ir35",
    "outside ir35 jobs uk": "blog/outside-ir35",
    "outside ir35 jobs uk remote": "blog/outside-ir35",
    "outside ir35 roles uk": "blog/outside-ir35",
    "outside ir35 contracts uk": "blog/outside-ir35",
    "ir35 how to avoid": "blog/outside-ir35",
    "how can i avoid ir35": "blog/outside-ir35",
    "difference inside outside ir35": "blog/outside-ir35",
    "ir35 avoid": "blog/outside-ir35",
    # inside ir35 blog
    "inside ir35": "blog/inside-ir35",
    "inside ir35 meaning": "blog/inside-ir35",
    "inside ir35 meaning uk": "blog/inside-ir35",
    "what does inside ir35 mean": "blog/inside-ir35",
    "what does inside ir35 mean uk": "blog/inside-ir35",
    "what does inside ir35 mean for contractors": "blog/inside-ir35",
    "what does inside ir35": "blog/inside-ir35",
    "what does inside ir35 umbrella mean": "blog/inside-ir35",
    "inside ir35 uk": "blog/inside-ir35",
    "inside ir35 uk meaning": "blog/inside-ir35",
    "inside ir35 definition": "blog/inside-ir35",
    "inside ir35 rules": "blog/inside-ir35",
    "is inside ir35 worth it": "blog/inside-ir35",
    "is inside ir35 self employed": "blog/inside-ir35",
    "is inside ir35 the same as paye": "blog/inside-ir35",
    "is inside ir35 paye": "blog/inside-ir35",
    "is inside ir35 the same as umbrella": "blog/inside-ir35",
    "is inside ir35 good": "blog/inside-ir35",
    "is inside ir35 better than outside": "blog/inside-ir35",
    "is inside ir35 off payroll": "blog/inside-ir35",
    "inside ir35 contract": "blog/inside-ir35",
    "how does inside ir35 work": "blog/inside-ir35",
    "how inside ir35 works": "blog/inside-ir35",
    "how does inside ir35 tax work": "blog/inside-ir35",
    "how to calculate inside ir35": "blog/inside-ir35",
    "how to invoice inside ir35": "blog/inside-ir35",
    "how to contract inside ir35": "blog/inside-ir35",
    "am i inside ir35": "blog/inside-ir35",
    "do i fall inside ir35": "blog/inside-ir35",
    "can i use limited company inside ir35": "blog/inside-ir35",
    "can i work inside and outside ir35": "blog/inside-ir35",
    "can i do 2 inside ir35 contracts": "blog/inside-ir35",
    "inside ir35 jobs uk": "blog/inside-ir35",
    "inside ir35 vs outside ir35": "blog/inside-ir35",
    "what is inside and outside ir35": "blog/inside-ir35",
    "what can i claim inside ir35": "blog/travel-expenses-inside-ir35",
    "can i claim expenses inside ir35": "blog/travel-expenses-inside-ir35",
    "can i claim expenses under ir35": "blog/travel-expenses-inside-ir35",
    "what expenses can i claim inside ir35 umbrella": "blog/travel-expenses-inside-ir35",
    "what inside ir35 means": "blog/inside-ir35",
    "what's inside ir35": "blog/inside-ir35",
    # what-is-ir35
    "ir35 rules": "blog/what-is-ir35",
    "ir35 rules uk": "blog/what-is-ir35",
    "ir35 uk rules": "blog/what-is-ir35",
    "what are ir35 rules": "blog/what-is-ir35",
    "what ir35": "blog/what-is-ir35",
    "what ir35 means": "blog/what-is-ir35",
    "what ir35 means for contractors": "blog/what-is-ir35",
    "ir35 meaning": "blog/what-is-ir35",
    "ir35 uk meaning": "blog/what-is-ir35",
    "ir35 uk explained": "blog/what-is-ir35",
    "how ir35 works": "blog/what-is-ir35",
    "ir35 2025": "blog/what-is-ir35",
    "ir35 rules 2025": "blog/what-is-ir35",
    "ir35 rules 2024": "blog/what-is-ir35",
    "ir35 rules 2026": "blog/what-is-ir35",
    "ir35 changes 2024": "blog/what-is-ir35",
    "ir35 changes 2025": "blog/what-is-ir35",
    "ir35 changes 2025 gov uk": "blog/what-is-ir35",
    "ir35 update 2025": "blog/what-is-ir35",
    "ir35 april 2025": "blog/what-is-ir35",
    "ir35 news 2025": "blog/what-is-ir35",
    "ir35 budget 2025": "blog/what-is-ir35",
    "ir35 2025 changes": "blog/what-is-ir35",
    "is ir35 still a thing": "blog/what-is-ir35",
    "is ir35 still applicable": "blog/what-is-ir35",
    "is ir35 being scrapped": "blog/what-is-ir35",
    "is ir35 good or bad": "blog/what-is-ir35",
    "is ir35 relevant to sole traders": "blog/what-is-ir35",
    "is ir35 uk only": "blog/what-is-ir35",
    "ir35 uk law": "blog/what-is-ir35",
    "ir35 uk tax": "blog/what-is-ir35",
    "ir35 what does it stand for": "blog/what-is-ir35",
    "ir35 what does ir stand for": "blog/what-is-ir35",
    "are ir35 rules changing": "blog/what-is-ir35",
    "what are the new ir35 rules": "blog/what-is-ir35",
    "what are the current ir35 rules": "blog/what-is-ir35",
    "what does ir35 rules apply mean": "blog/what-is-ir35",
    "do ir35 rules still apply": "blog/what-is-ir35",
    "does ir35 apply to contractors outside the uk": "blog/what-is-ir35",
    "can ir35 be backdated": "blog/what-is-ir35",
    "ir35 cases 2024": "blog/what-is-ir35",
    "ir35 rules for freelancers": "blog/what-is-ir35",
    "ir35 rules for self-employed": "blog/what-is-ir35",
    "ir35 rules for sole traders": "blog/what-is-ir35",
    "ir35 rules for limited companies": "blog/what-is-ir35",
    "ir35 rules for overseas contractors": "blog/what-is-ir35",
    "ir35 what is an office holder": "blog/what-is-ir35",
    "do ir35 rules apply to sole traders": "blog/what-is-ir35",
    "ir35 rules summary 2025": "blog/what-is-ir35",
    "what are ir35 tax rules": "blog/what-is-ir35",
    "ir35 rules 2025 summary": "blog/what-is-ir35",
    # ir35 status / assessment
    "ir35 assessment": "page/ir35-status",
    "ir35 check": "page/ir35-status",
    "ir35 status check": "page/ir35-status",
    "ir35 determination": "page/ir35-status",
    "ir35 uk check": "page/ir35-status",
    "ir35 how to determine status": "page/ir35-status",
    "ir35 what's status": "page/ir35-status",
    # small company exemption
    "ir35 small business exemption": "blog/ir35-small-company-exemption",
    "ir35 small company exemption": "blog/ir35-small-company-exemption",
    "ir35 rules small company": "blog/ir35-small-company-exemption",
    "ir35 rules for small companies": "blog/ir35-small-company-exemption",
    "are small companies exempt from ir35": "blog/ir35-small-company-exemption",
    "do ir35 rules apply to small companies": "blog/ir35-small-company-exemption",
    "ir35 what is a small company": "blog/ir35-small-company-exemption",
    "ir35 small business exemption hmrc": "blog/ir35-small-company-exemption",
    # SDS
    "ir35 sds determination": "blog/sds-status-determination-statement",
    "ir35 sds": "blog/sds-status-determination-statement",
    "sds ir35": "blog/sds-status-determination-statement",
    "what is sds ir35": "blog/sds-status-determination-statement",
    "what is an sds ir35": "blog/sds-status-determination-statement",
    "ir35 sds example": "blog/sds-status-determination-statement",
    "ir35 sds hmrc": "blog/sds-status-determination-statement",
    "ir35 sds tool": "blog/how-to-use-cest-tool",
    "ir35 sds responsibility": "blog/sds-status-determination-statement",
    "ir35 sds form": "blog/sds-status-determination-statement",
    "sds ir35 meaning": "blog/sds-status-determination-statement",
    "sds ir35 template": "blog/sds-status-determination-statement",
    "what is sds ir35": "blog/sds-status-determination-statement",
    "ir3535 sds": "JUNK",
    # off-payroll
    "off-payroll working rules": "blog/off-payroll-working-rules-private-sector",
    "off payroll working rules uk": "blog/off-payroll-working-rules-private-sector",
    "off payroll working rules meaning": "blog/off-payroll-working-rules-private-sector",
    "what is off payroll working rules": "blog/off-payroll-working-rules-private-sector",
    "what is off payroll working legislation": "blog/off-payroll-working-rules-private-sector",
    "what are off payroll working rules": "blog/off-payroll-working-rules-private-sector",
    "what does off payroll working rules apply mean": "blog/off-payroll-working-rules-private-sector",
    "what does off payroll working rules mean": "blog/off-payroll-working-rules-private-sector",
    "off payroll working rules apply meaning": "blog/off-payroll-working-rules-private-sector",
    "what does off payroll working rules ir35 apply mean": "blog/off-payroll-working-rules-private-sector",
    "what does off payroll working rules ir35 apply": "blog/off-payroll-working-rules-private-sector",
    "what does off payroll working rules ir35 mean": "blog/off-payroll-working-rules-private-sector",
    "what is off payroll working rules ir35": "blog/off-payroll-working-rules-private-sector",
    "off-payroll working rules do not apply": "blog/off-payroll-working-rules-private-sector",
    "off-payroll working rules apply": "blog/off-payroll-working-rules-private-sector",
    "off payroll working rules apply": "blog/off-payroll-working-rules-private-sector",
    "off-payroll working rules (ir35)": "blog/off-payroll-working-rules-private-sector",
    "off-payroll working rules (ir35) apply": "blog/off-payroll-working-rules-private-sector",
    "off-payroll working rules (ir35) do not apply": "blog/off-payroll-working-rules-private-sector",
    "off-payroll working rules (ir35) apply meaning": "blog/off-payroll-working-rules-private-sector",
    "what does off payroll working rules apply": "blog/off-payroll-working-rules-private-sector",
    "off-payroll working rules (ir35) apply meaning": "blog/off-payroll-working-rules-private-sector",
    "off payroll working rules uk": "blog/off-payroll-working-rules-private-sector",
    "ir35 rules for employers": "blog/off-payroll-working-rules-private-sector",
    # PSC
    "psc limited company": "blog/psc-limited-company-contractor-tax",
    "PSC limited company": "blog/psc-limited-company-contractor-tax",
    "psc limited company meaning": "blog/psc-limited-company-contractor-tax",
    "what is a psc limited company": "blog/psc-limited-company-contractor-tax",
    "is a psc the same as a limited company": "blog/psc-limited-company-contractor-tax",
    "psc vs limited company": "blog/psc-limited-company-contractor-tax",
    "psc service company limited": "blog/psc-limited-company-contractor-tax",
    "psc company limited by guarantee": "blog/psc-limited-company-contractor-tax",
    "psc private limited company": "blog/psc-limited-company-contractor-tax",
    "psc trading company limited": "blog/psc-limited-company-contractor-tax",
    "can a limited company be a psc": "blog/psc-limited-company-contractor-tax",
    "does a limited company have to have a psc": "blog/psc-limited-company-contractor-tax",
    # ltd co tax
    "taxes for limited company": "blog/psc-limited-company-contractor-tax",
    "limited company tax benefits": "blog/psc-limited-company-contractor-tax",
    "how much tax does a limited company pay uk": "blog/corporation-tax-contractor-limited-company",
    "how do limited companies pay tax": "blog/psc-limited-company-contractor-tax",
    "how ltd company tax works": "blog/psc-limited-company-contractor-tax",
    "do you pay tax on ltd company": "blog/psc-limited-company-contractor-tax",
    "how much tax as a contractor": "blog/psc-limited-company-contractor-tax",
    "how much tax do i pay if i have a limited company": "blog/corporation-tax-contractor-limited-company",
    "do contractors have to pay taxes": "blog/psc-limited-company-contractor-tax",
    "how much is ir35 tax": "blog/inside-ir35-take-home-explained",
    "how much does ir35 cost": "blog/inside-ir35-take-home-explained",
    "how much is ir35 insurance": "blog/ir35-contract-review-checklist",
    "how do i do my taxes as a contractor": "blog/contractor-self-assessment-guide",
    "can i do my own limited company tax return": "blog/contractor-self-assessment-guide",
    # contractor accountants
    "contractor accountants": "blog/what-is-a-contractor-accountant",
    "contractor accountant uk": "blog/what-is-a-contractor-accountant",
    "contractor accountants uk": "blog/what-is-a-contractor-accountant",
    "contractor accountants london": "blog/what-is-a-contractor-accountant",
    "contractor accountants ireland": "blog/what-is-a-contractor-accountant",
    "best contractor accountants uk": "blog/how-to-choose-contractor-accountant",
    "contractor accountant reviews": "blog/how-to-choose-contractor-accountant",
    "contractor accountants manchester": "blog/what-is-a-contractor-accountant",
    "accountants for limited company contractors": "blog/what-is-a-contractor-accountant",
    "what is a contractor accountant": "blog/what-is-a-contractor-accountant",
    "how to become a contractor accountant": "blog/what-is-a-contractor-accountant",
    "are accountants contractors": "blog/what-is-a-contractor-accountant",
    "contractor accountants near me": "blog/how-to-choose-contractor-accountant",
    # contractor expenses
    "contractor expenses": "blog/contractor-expenses-allowable-guide",
    "contracting expenses": "blog/contractor-expenses-allowable-guide",
    "what are contractor expenses": "blog/contractor-expenses-allowable-guide",
    "what is contractor expenses": "blog/contractor-expenses-allowable-guide",
    "contractor expenses list": "blog/contractor-expenses-allowable-guide",
    "contractor expenses meaning": "blog/contractor-expenses-allowable-guide",
    "as a contractor what expenses can i claim": "blog/contractor-expenses-allowable-guide",
    "what expenses can i claim as a contractor": "blog/contractor-expenses-allowable-guide",
    "what expenses can an independent contractor claim": "blog/contractor-expenses-allowable-guide",
    "what expenses can i claim outside ir35": "blog/contractor-expenses-allowable-guide",
    "can contractors claim expenses": "blog/contractor-expenses-allowable-guide",
    "are contractor expenses tax deductible": "blog/contractor-expenses-allowable-guide",
    "contractor expenses tax deductible": "blog/contractor-expenses-allowable-guide",
    "contractor expenses spreadsheet template": "blog/contractor-expenses-allowable-guide",
    "independent contractor expenses": "blog/contractor-expenses-allowable-guide",
    "contractor expenses non salary": "blog/contractor-expenses-allowable-guide",
    "what is contractor expenses non salary": "blog/contractor-expenses-allowable-guide",
    "can you reimburse independent contractors for expenses": "blog/contractor-expenses-allowable-guide",
    "can i claim travel expenses outside ir35": "blog/contractor-expenses-allowable-guide",
    # pension
    "contractor pension": "blog/contractor-pension-employer-contributions",
    "uk contractor pension": "blog/contractor-pension-employer-contributions",
    "contractor pension contributions": "blog/contractor-pension-employer-contributions",
    "employer pension contributions psc": "blog/contractor-pension-employer-contributions",
    "do contractors get pension": "blog/contractor-pension-employer-contributions",
    "paye contractor pension": "blog/contractor-pension-employer-contributions",
    "contractor umbrella pension": "blog/contractor-pension-employer-contributions",
    "contractor uk pension contributions": "blog/contractor-pension-employer-contributions",
    "government contractor pension": "blog/contractor-pension-employer-contributions",
    "contractor pension calculator": "blog/contractor-pension-schemes-sipp",
    "what is a contracting out certificate for pensions": "blog/contractor-pension-schemes-sipp",
    # travel / mileage
    "travel expenses contractor": "blog/mileage-claims-contractor-limited-company",
    "travel expenses independent contractor": "blog/mileage-claims-contractor-limited-company",
    "travel expenses construction worker": "blog/mileage-claims-contractor-limited-company",
    "contractor travel expenses 24 month rule": "blog/mileage-claims-contractor-limited-company",
    "travel charges for contractors": "blog/mileage-claims-contractor-limited-company",
    "how do contractors charge for travel": "blog/mileage-claims-contractor-limited-company",
    # deemed employer
    "deemed employer meaning": "blog/deemed-employment-payment-explained",
    "deemed employee uk": "blog/deemed-employment-payment-explained",
    "deemed employee rules": "blog/deemed-employment-payment-explained",
    "deemed occupation rules": "blog/deemed-employment-payment-explained",
    "what is a deemed worker uk": "blog/deemed-employment-payment-explained",
    # JUNK — ir3535 is an insecticide; pop-culture umbrella corporation
    "ir3535 sds": "JUNK",
    "is ir3535 safe": "JUNK",
    "is ir3535 toxic": "JUNK",
    "is ir3535 safe for dogs": "JUNK",
    "is ir3535 the same as picaridin": "JUNK",
    "where can i buy ir3535": "JUNK",
    "umbrella corporation 2025": "JUNK",
    "is umbrella corporation real": "JUNK",
    "is umbrella corporation still active": "JUNK",
    "is umbrella corporation evil": "JUNK",
    "how much is umbrella corporation worth": "JUNK",
    "what's umbrella corporation": "JUNK",
    "umbrella corporation explained": "JUNK",
    "umbrella company resident evil": "JUNK",
    "umbrella company movie": "JUNK",
    "umbrella company in india": "JUNK",
    "umbrella company ireland": "JUNK",
    "umbrella company examples": "JUNK",
    "psc co ltd mongolia": "JUNK",
    "psc corporation limited": "JUNK",
    "ir35 uk visa": "JUNK",
    "pension construction 2024": "JUNK",
    "pension construction 2025": "JUNK",
    "pension construction 2025 km": "JUNK",
    "contractor charges 2024": "JUNK",
    "contractor charges 2025": "JUNK",
    "contractor charges 2025 pdf": "JUNK",
    "contractor charges 2025 ireland": "JUNK",
    "contractor charges 2024 calculator": "JUNK",
    "contractor charges 2024 hedge cutting": "JUNK",
    "how much contractor cost": "JUNK",
    "how much are contractor fees": "JUNK",
    "how much contractor insurance cost": "JUNK",
    "are contractor expenses included in 1099": "JUNK",
    "contractor expenses quickbooks": "JUNK",
    "contractor expenses cra": "JUNK",
    "how much a contractor charges": "JUNK",
    "how much do umbrella companies charge uk": "blog/umbrella-company-deductions-explained",
    # misc small volume covered
    "can i be my own umbrella company": "blog/umbrella-company-explained",
    "how to set up umbrella company": "blog/umbrella-company-explained",
    "how to set up umbrella company uk": "blog/umbrella-company-explained",
    "how to create umbrella company": "blog/umbrella-company-explained",
    "how to create an umbrella company uk": "blog/umbrella-company-explained",
    "how to register an umbrella company uk": "blog/umbrella-company-explained",
    "how to start umbrella company": "blog/umbrella-company-explained",
    "can i create my own umbrella company": "blog/umbrella-company-explained",
    "can i set up my own umbrella company uk": "blog/umbrella-company-explained",
    "can i use an llc as an umbrella company": "JUNK",
    "umbrella company name": "JUNK",
    "umbrella policy company": "JUNK",
    "umbrella company uk address": "JUNK",
    "umbrella company uk contact number": "JUNK",
    "umbrella company uk trustpilot": "JUNK",
    "umbrella company uk reddit": "JUNK",
    "is umbrella company": "blog/umbrella-company-explained",
    "what umbrella company": "blog/umbrella-company-explained",
    # how much contractor charges - genuine
    "contractor charges 2025 pdf": "JUNK",
    "outside ir35 jobs uk in the last 3 days": "JUNK",
    "outside ir35 jobs uk since yesterday": "JUNK",
    "pension contractor jobs": "JUNK",
    "contractor accountant jobs": "JUNK",
    "contractor accountant salary": "blog/what-is-a-contractor-accountant",
}


def covered_by(kw):
    kw_lower = kw.lower().strip()
    if kw_lower in COVERAGE:
        dest = COVERAGE[kw_lower]
        return True, dest
    return False, None


rows = run(
    "SELECT id, primary_keyword, topic, search_volume FROM blog_topics "
    "WHERE site_key='contractors-ir35' AND used=false"
)

to_flip = []
not_covered = []

for row in rows:
    kw = row["primary_keyword"]
    covered, reason = covered_by(kw)
    if covered:
        to_flip.append((row["id"], kw, row["search_volume"] or 0, reason))
    else:
        not_covered.append((kw, row["search_volume"] or 0))

print(f"Pool (unused): {len(rows)}")
print(f"To flip:       {len(to_flip)}")
print(f"Remaining:     {len(not_covered)}")

if DRY:
    print("\n[DRY RUN] would flip:")
    for id_, kw, vol, dest in sorted(to_flip, key=lambda x: -x[2])[:30]:
        print(f"  vol={vol:4d}  {kw!r} -> {dest}")
else:
    ids = [t[0] for t in to_flip]
    placeholders = ", ".join(f"'{i}'" for i in ids)
    sql = (
        f"UPDATE blog_topics SET used=true, "
        f"notes=COALESCE(notes,'')||' coverage-reconcile-2026-07-14' "
        f"WHERE id IN ({placeholders}) AND site_key='contractors-ir35'"
    )
    result = run(sql)
    print(f"\nUPDATE result: {result}")

# top 20 remaining by volume
remaining_sorted = sorted(not_covered, key=lambda x: -x[1])
print("\nTop 20 verified-unwritten by search_volume:")
for kw, vol in remaining_sorted[:20]:
    print(f"  vol={vol:4d}  {kw!r}")

with_vol = [(kw, vol) for kw, vol in not_covered if vol > 0]
print(f"\nRemaining with volume>0: {len(with_vol)}")
print(f"Remaining total: {len(not_covered)}")
