"""
Build the Property site content matrix.

Generates Admin/property_content_matrix.json with every topic across 3 streams:
  - Stream 1: Substantive blog posts (including city posts)
  - Stream 2: Expense spoke posts (hub-spoke off deductions pillar)
  - Stream 3: Tool/calculator pages

Also lists ~20 existing posts for FAQ schema enrichment.

Usage:
    python scripts/build_content_matrix.py
"""

import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BLOG_DIR = REPO_ROOT / "Property" / "web" / "content" / "blog"
OUTPUT_PATH = REPO_ROOT / "Admin" / "property_content_matrix.json"


def slugify(text: str) -> str:
    s = text.lower()
    s = re.sub(r"[()£%]", "", s)
    s = s.replace("&", "and")
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s


def get_existing_slugs() -> set:
    slugs = set()
    for f in BLOG_DIR.glob("*.md"):
        slugs.add(f.stem)
    return slugs


def topic(
    title: str,
    primary_keyword: str,
    category: str,
    *,
    secondary_keywords: list = None,
    search_intent: str = "informational",
    content_stream: str = "substantive",
    content_tier: str = "cluster",
    priority: int = 3,
    title_format: str = "question",
    target_word_count: int = 2000,
    related_existing: str = "",
    differentiation: str = "",
    slug_override: str = None,
):
    slug = slug_override or slugify(title)
    risk = "low"
    if related_existing:
        risk = "medium" if "guide" in related_existing or "complete" in related_existing else "low"

    return {
        "title": title,
        "slug": slug,
        "primary_keyword": primary_keyword,
        "secondary_keywords": secondary_keywords or [],
        "search_intent": search_intent,
        "content_stream": content_stream,
        "content_tier": content_tier,
        "priority": priority,
        "title_format": title_format,
        "target_word_count": target_word_count,
        "cannibalization_check": {
            "risk": risk,
            "related_existing": related_existing,
            "differentiation": differentiation,
        },
        "action": "generate",
    }


# ---------------------------------------------------------------------------
# CATEGORY TOPIC DEFINITIONS
# ---------------------------------------------------------------------------

SECTION_24_TOPICS = [
    topic("How Will 2027 Property Tax Rates Affect Section 24 Relief?",
          "2027 property tax rates section 24", "Section 24 & Tax Relief",
          secondary_keywords=["22% basic rate property", "separate property income tax rates 2027"],
          priority=5, differentiation="2027-specific vs current year guides"),
    topic("Section 24 Tax Credit: How the 20% Basic Rate Relief Actually Works",
          "section 24 tax credit 20%", "Section 24 & Tax Relief",
          secondary_keywords=["20 tax credit mortgage interest", "section 24 basic rate credit"],
          priority=4, related_existing="section-24-tax-relief-complete-guide",
          differentiation="focuses on credit mechanics vs complete overview"),
    topic("Is Mortgage Interest Deductible for UK Landlords in 2026?",
          "mortgage interest deductible landlords uk 2026", "Section 24 & Tax Relief",
          secondary_keywords=["can landlords claim mortgage interest", "mortgage interest tax relief"],
          priority=5, related_existing="section-24-mortgage-interest-restriction-uk-landlords",
          differentiation="question-format entry point vs deep restriction guide"),
    topic("Can You Claim Mortgage Interest on Rental Property UK?",
          "claim mortgage interest rental property", "Section 24 & Tax Relief",
          secondary_keywords=["mortgage interest rental income", "mortgage costs tax deductible"],
          priority=4, differentiation="beginner question format vs technical guide"),
    topic("Section 24 and Joint Property Ownership: How Is Tax Split?",
          "section 24 joint ownership", "Section 24 & Tax Relief",
          secondary_keywords=["joint landlords section 24", "couples rental income tax split"],
          priority=3),
    topic("Section 24 Impact When You Cross the Higher Rate Threshold",
          "section 24 higher rate threshold", "Section 24 & Tax Relief",
          secondary_keywords=["pushed into higher rate by section 24", "threshold effect landlords"],
          priority=4, related_existing="section-24-higher-rate-taxpayers-2026",
          differentiation="threshold-crossing scenario vs general higher rate impact"),
    topic("Section 24 and Multiple Rental Properties: Cumulative Impact",
          "section 24 multiple properties", "Section 24 & Tax Relief",
          secondary_keywords=["section 24 portfolio impact", "mortgage interest restriction multiple BTL"],
          priority=3),
    topic("How Does Section 24 Affect Landlords with Employment Income?",
          "section 24 employment income", "Section 24 & Tax Relief",
          secondary_keywords=["PAYE landlord section 24", "salary plus rental income tax"],
          priority=3),
    topic("Section 24 and Remortgaging: Tax Implications for Landlords",
          "section 24 remortgaging", "Section 24 & Tax Relief",
          secondary_keywords=["remortgage BTL section 24", "increased mortgage section 24 impact"],
          priority=3, related_existing="buy-to-let-refinancing-when-does-it-make-sense",
          differentiation="Section 24 angle vs general refinancing decision"),
    topic("Section 24 for Higher Rate Taxpayers: What Changes in 2027?",
          "section 24 higher rate 2027", "Section 24 & Tax Relief",
          secondary_keywords=["42% property tax rate", "higher rate landlord 2027"],
          priority=5, differentiation="2027 forward-looking vs current year"),
    topic("What Counts as Finance Costs Under Section 24?",
          "finance costs section 24", "Section 24 & Tax Relief",
          secondary_keywords=["loan arrangement fees section 24", "overdraft interest landlord"],
          priority=3, title_format="definition"),
    topic("Section 24 and Interest-Only Mortgages: Tax Planning Guide",
          "section 24 interest only mortgage", "Section 24 & Tax Relief",
          secondary_keywords=["interest only BTL tax", "repayment vs interest only landlord"],
          priority=3),
    topic("Section 24 and Loss of Personal Allowance: The Hidden Tax Trap",
          "section 24 personal allowance", "Section 24 & Tax Relief",
          secondary_keywords=["£100k income personal allowance", "60% marginal rate landlord"],
          priority=4),
    topic("Can Section 24 Push You Into Higher Rate Tax?",
          "section 24 push higher rate", "Section 24 & Tax Relief",
          secondary_keywords=["phantom income section 24", "tax on income you don't receive"],
          priority=4, title_format="question"),
    topic("Section 24 and Child Benefit: High Income Charge Impact",
          "section 24 child benefit", "Section 24 & Tax Relief",
          secondary_keywords=["HICBC landlord", "child benefit clawback rental income"],
          priority=3),
    topic("How to Calculate Your Section 24 Tax Credit Step by Step",
          "calculate section 24 tax credit", "Section 24 & Tax Relief",
          secondary_keywords=["section 24 calculation example", "work out section 24 impact"],
          priority=4, related_existing="section-24-calculator",
          differentiation="manual walkthrough vs calculator tool"),
    topic("Tax Relief on Mortgage Interest for Rented Property: Full Guide",
          "tax relief mortgage interest rented property", "Section 24 & Tax Relief",
          secondary_keywords=["mortgage interest tax relief rental", "landlord mortgage relief 2026"],
          priority=4),
    topic("Section 24 and Commercial Property: Does It Apply?",
          "section 24 commercial property", "Section 24 & Tax Relief",
          secondary_keywords=["commercial landlord mortgage interest", "business property section 24"],
          priority=3),
    topic("Section 24 and Student Loan Repayments: The Double Hit",
          "section 24 student loan", "Section 24 & Tax Relief",
          secondary_keywords=["plan 2 student loan landlord", "rental income student loan repayment"],
          priority=2),
    topic("What Repairs Can Landlords Deduct From Rental Income?",
          "landlord repairs tax deduction", "Section 24 & Tax Relief",
          secondary_keywords=["repairs vs improvements landlord", "capital expenditure rental property"],
          priority=4, related_existing="landlord-tax-deductions-uk-2026-complete-list",
          differentiation="deep dive on repairs boundary vs broad deductions list"),
    topic("Capital vs Revenue Expenditure for Landlords: How to Tell",
          "capital vs revenue expenditure landlord", "Section 24 & Tax Relief",
          secondary_keywords=["improvement vs repair landlord", "HMRC capital expenditure property"],
          priority=4),
    topic("Pre-Letting Expenses: What Can Landlords Claim Before First Tenant?",
          "pre-letting expenses landlord", "Section 24 & Tax Relief",
          secondary_keywords=["costs before first tenant", "deductible expenses before letting"],
          priority=3),
    topic("Can Landlords Deduct Mortgage Arrangement Fees?",
          "mortgage arrangement fees deductible landlord", "Section 24 & Tax Relief",
          secondary_keywords=["broker fees tax deductible BTL", "loan setup costs landlord"],
          priority=3),
    topic("Rent-a-Room Relief: How the £7,500 Tax-Free Allowance Works",
          "rent a room relief", "Section 24 & Tax Relief",
          secondary_keywords=["rent a room scheme landlord", "£7500 tax free lodger"],
          priority=3, title_format="how-to"),
    topic("Replacement Domestic Items Relief: What Landlords Can Claim",
          "replacement domestic items relief", "Section 24 & Tax Relief",
          secondary_keywords=["furniture replacement relief", "replace sofa rental property tax"],
          priority=3, related_existing="landlord-tax-deductions-uk-2026-complete-list",
          differentiation="detailed relief rules vs list entry"),
    topic("Section 24 Worked Example: £50k Rental Income Portfolio",
          "section 24 worked example 50k", "Section 24 & Tax Relief",
          secondary_keywords=["section 24 calculation 50000", "realistic section 24 example"],
          priority=3, title_format="scenario",
          related_existing="section-24-case-study-100k-rental-income-portfolio",
          differentiation="£50k mid-range vs £100k high-end case study"),
    topic("How Section 24 Affects Your Self Assessment Tax Return",
          "section 24 self assessment", "Section 24 & Tax Relief",
          secondary_keywords=["SA105 section 24", "section 24 box on tax return"],
          priority=3),
    topic("Section 24 and the 2027 Tax Year: Planning Ahead",
          "section 24 2027 tax year planning", "Section 24 & Tax Relief",
          secondary_keywords=["section 24 future changes", "property tax 2027/28"],
          priority=5),
]

INCORPORATION_TOPICS = [
    topic("Should I Incorporate My Buy-to-Let Portfolio in 2026?",
          "incorporate buy to let portfolio 2026", "Incorporation & Company Structures",
          secondary_keywords=["when to incorporate BTL", "incorporation vs personal ownership"],
          priority=4, related_existing="incorporation-timing-when-to-incorporate-property-portfolio",
          differentiation="2026-specific decision guide vs general timing analysis"),
    topic("What Is a Special Purpose Vehicle (SPV) for Property Investment?",
          "SPV property investment", "Incorporation & Company Structures",
          secondary_keywords=["special purpose vehicle landlord", "SPV company structure"],
          priority=4, title_format="definition"),
    topic("How to Set Up a Property Investment Company: Step-by-Step",
          "set up property investment company", "Incorporation & Company Structures",
          secondary_keywords=["register property company", "companies house property company"],
          priority=4, title_format="how-to",
          related_existing="property-investment-company-structure-planning",
          differentiation="practical setup steps vs strategic planning"),
    topic("Property Holding Company Structure: When Does It Make Sense?",
          "property holding company structure", "Incorporation & Company Structures",
          secondary_keywords=["holding company landlord", "parent company rental property"],
          priority=3),
    topic("LLP for Property Investment: Is It Worth Considering?",
          "LLP property investment", "Incorporation & Company Structures",
          secondary_keywords=["limited liability partnership property", "LLP vs SPV property"],
          priority=3),
    topic("Property Company Running Costs: What to Expect Annually",
          "property company running costs", "Incorporation & Company Structures",
          secondary_keywords=["annual costs limited company landlord", "accountancy fees property company"],
          priority=4),
    topic("Property Company Accounting Requirements: What HMRC Expects",
          "property company accounting requirements", "Incorporation & Company Structures",
          secondary_keywords=["corporation tax return property company", "CT600 rental company"],
          priority=3),
    topic("Corporation Tax for Property Companies: Rates and Reliefs 2026/27",
          "corporation tax property companies 2026", "Incorporation & Company Structures",
          secondary_keywords=["19% small profits rate", "corporation tax rates landlord"],
          priority=4, related_existing="accountant-corporation-tax-property-companies",
          differentiation="rate-focused guide vs general service description"),
    topic("How 2027 Tax Rates Change the Incorporation Decision",
          "2027 tax rates incorporation decision", "Incorporation & Company Structures",
          secondary_keywords=["22% basic rate vs corporation tax", "incorporate before 2027"],
          priority=5, differentiation="2027 forward-looking analysis"),
    topic("Incorporation Relief Under Section 162: Does It Apply to Landlords?",
          "incorporation relief section 162 landlords", "Incorporation & Company Structures",
          secondary_keywords=["section 162 property", "CGT relief incorporating property business"],
          priority=4, related_existing="incorporate-rental-property-without-cgt",
          differentiation="legal relief mechanism vs practical avoidance guide"),
    topic("Smart Property Company Structure: Choosing the Right Setup",
          "smart property company structure", "Incorporation & Company Structures",
          secondary_keywords=["property company structure options", "best structure for BTL company"],
          priority=4, related_existing="property-investment-company-structure-planning",
          differentiation="decision framework vs planning overview"),
    topic("Types of Property Company Structure: Which Is Right for You?",
          "types of property company structure", "Incorporation & Company Structures",
          secondary_keywords=["SPV vs holding company", "trading company vs investment company"],
          priority=4),
    topic("Tax-Efficient Property Investment Structure: A Complete Guide",
          "tax efficient property investment structure", "Incorporation & Company Structures",
          secondary_keywords=["optimal property structure", "tax efficient landlord structure"],
          priority=4),
    topic("Incorporating a Rental Business: When Does HMRC Accept It?",
          "incorporating rental business HMRC", "Incorporation & Company Structures",
          secondary_keywords=["rental business vs investment", "HMRC property business test"],
          priority=3),
    topic("SDLT on Transferring Property to a Company: How Much Will I Pay?",
          "SDLT transfer property company", "Incorporation & Company Structures",
          secondary_keywords=["stamp duty incorporation cost", "SDLT 5% surcharge company"],
          priority=4, related_existing="sdlt-incorporation-stamp-duty-twice",
          differentiation="cost calculation vs double-charge question"),
    topic("Retained Profits in a Property Company: Tax Advantages",
          "retained profits property company", "Incorporation & Company Structures",
          secondary_keywords=["reinvesting profits property company", "compound growth company structure"],
          priority=3, related_existing="property-company-profit-extraction-salary-vs-dividends",
          differentiation="retaining vs extracting profits"),
    topic("Family Investment Company for Property: Is It Worth It?",
          "family investment company property", "Incorporation & Company Structures",
          secondary_keywords=["FIC property", "family company estate planning property"],
          priority=3),
    topic("Property Company and Pension Contributions: Employer Contributions",
          "property company pension contributions", "Incorporation & Company Structures",
          secondary_keywords=["SSAS property company", "employer pension contribution landlord"],
          priority=3, related_existing="section-24-pension-contributions-tax-planning",
          differentiation="company contributions vs personal planning"),
    topic("Winding Up a Property Company: CGT and Distribution Rules",
          "winding up property company", "Incorporation & Company Structures",
          secondary_keywords=["close property company", "MVL property company", "entrepreneurs relief"],
          priority=2),
    topic("Property Company Directors: Responsibilities and Compliance",
          "property company directors responsibilities", "Incorporation & Company Structures",
          secondary_keywords=["director duties landlord", "Companies House filing property"],
          priority=2),
    topic("Converting Personal Properties to Company: Phased Transfer Guide",
          "transfer properties to company phased", "Incorporation & Company Structures",
          secondary_keywords=["gradual incorporation", "move one property at a time"],
          priority=3, related_existing="incorporation-existing-portfolios-phased-approach",
          differentiation="practical conversion steps vs strategic approach guide"),
    topic("Corporation Tax vs Income Tax for Landlords: 2027 Comparison",
          "corporation tax vs income tax landlords 2027", "Incorporation & Company Structures",
          secondary_keywords=["19% vs 22% property tax", "company vs personal 2027"],
          priority=5, related_existing="limited-company-vs-personal-ownership-tax-comparison-2026",
          differentiation="2027 rates vs 2026 comparison"),
    topic("Incorporation Case Study: 10-Property Portfolio with £200k Mortgage",
          "incorporation case study 10 properties", "Incorporation & Company Structures",
          secondary_keywords=["large portfolio incorporation", "10 BTL incorporation cost"],
          priority=3, title_format="scenario",
          related_existing="incorporation-case-study-5-property-portfolio-analysis",
          differentiation="larger portfolio scale"),
    topic("Buy-to-Let Limited Company Mortgage Rates: 2026 Market Guide",
          "buy to let limited company mortgage rates 2026", "Incorporation & Company Structures",
          secondary_keywords=["SPV mortgage rates", "company BTL mortgage best rates"],
          priority=4, related_existing="buy-to-let-limited-company-mortgage-options",
          differentiation="current rate guide vs general options overview"),
    topic("Property Company Bank Account: Best Options for Landlords",
          "property company bank account", "Incorporation & Company Structures",
          secondary_keywords=["SPV bank account", "business account property company"],
          priority=2),
]

MTD_TOPICS = [
    topic("Making Tax Digital for Property Income: Complete 2026 Guide",
          "making tax digital property income 2026", "Making Tax Digital (MTD)",
          secondary_keywords=["MTD ITSA landlord", "MTD property quarterly reporting"],
          priority=5, related_existing="making-tax-digital-landlords-april-2026-deadline",
          differentiation="comprehensive how-to vs deadline-focused overview"),
    topic("MTD Quarterly Reporting for Landlords: Step-by-Step Guide",
          "MTD quarterly reporting landlords", "Making Tax Digital (MTD)",
          secondary_keywords=["quarterly submission landlord", "MTD quarterly deadlines"],
          priority=5, title_format="how-to"),
    topic("MTD Penalties for Landlords: What Happens If You Miss a Deadline?",
          "MTD penalties landlords", "Making Tax Digital (MTD)",
          secondary_keywords=["late submission penalty MTD", "points-based penalty system"],
          priority=4),
    topic("MTD for Joint Property Owners: Who Needs to Report?",
          "MTD joint property owners", "Making Tax Digital (MTD)",
          secondary_keywords=["joint ownership MTD reporting", "married couple MTD property"],
          priority=3),
    topic("MTD for Property Partnerships: Reporting Requirements",
          "MTD property partnerships", "Making Tax Digital (MTD)",
          secondary_keywords=["partnership quarterly reporting", "SA800 MTD"],
          priority=3),
    topic("MTD Software for Landlords: Free vs Paid Options Compared",
          "MTD software landlords free vs paid", "Making Tax Digital (MTD)",
          secondary_keywords=["free MTD software landlord", "cheap MTD compatible software"],
          priority=4, related_existing="best-mtd-software-landlords-2026",
          differentiation="free vs paid comparison vs best overall"),
    topic("How to Register for MTD as a Landlord: Step-by-Step",
          "register MTD landlord", "Making Tax Digital (MTD)",
          secondary_keywords=["sign up MTD property", "HMRC MTD registration"],
          priority=5, title_format="how-to"),
    topic("MTD Record Keeping for Landlords: What You Need to Store",
          "MTD record keeping landlords", "Making Tax Digital (MTD)",
          secondary_keywords=["digital records landlord", "MTD receipts requirements"],
          priority=4),
    topic("MTD and the £10,000 Threshold: When Does It Apply?",
          "MTD £10000 threshold", "Making Tax Digital (MTD)",
          secondary_keywords=["MTD income threshold", "gross rental income MTD"],
          priority=4, related_existing="mtd-rental-income-threshold-exemptions",
          differentiation="threshold calculation focus vs broad exemptions overview"),
    topic("MTD End of Period Statement: What Landlords Need to Know",
          "MTD end of period statement landlord", "Making Tax Digital (MTD)",
          secondary_keywords=["EOPS MTD", "year-end MTD submission"],
          priority=3),
    topic("MTD Final Declaration: Replacing the Self Assessment Return",
          "MTD final declaration", "Making Tax Digital (MTD)",
          secondary_keywords=["MTD vs self assessment", "annual MTD submission"],
          priority=3),
    topic("MTD for Landlords with Both Property and Self-Employment",
          "MTD property and self employment", "Making Tax Digital (MTD)",
          secondary_keywords=["multiple income sources MTD", "combined MTD reporting"],
          priority=3),
    topic("SA105 Property Income Form 2026: How to Complete It",
          "SA105 2026 property income", "Making Tax Digital (MTD)",
          secondary_keywords=["SA105 guide landlord", "property pages tax return 2026"],
          priority=4, title_format="how-to"),
    topic("MTD Exemptions for Landlords: Who Doesn't Need to Comply?",
          "MTD exemptions landlords", "Making Tax Digital (MTD)",
          secondary_keywords=["MTD exempt rental income", "below threshold MTD"],
          priority=3, related_existing="mtd-rental-income-threshold-exemptions",
          differentiation="exemption-focused vs broader threshold overview"),
    topic("How to Switch from Self Assessment to MTD for Property Income",
          "switch self assessment MTD property", "Making Tax Digital (MTD)",
          secondary_keywords=["transition to MTD", "move from SA to MTD landlord"],
          priority=4, title_format="how-to"),
    topic("MTD Compatible Spreadsheets for Landlords: Do They Work?",
          "MTD compatible spreadsheet landlord", "Making Tax Digital (MTD)",
          secondary_keywords=["Excel MTD landlord", "spreadsheet quarterly reporting"],
          priority=3),
    topic("MTD for Property Companies: Are Limited Companies Affected?",
          "MTD property companies limited company", "Making Tax Digital (MTD)",
          secondary_keywords=["MTD corporation tax", "limited company MTD landlord"],
          priority=3),
    topic("MTD Quarterly Deadlines 2026/27: Key Dates for Landlords",
          "MTD quarterly deadlines 2026 2027", "Making Tax Digital (MTD)",
          secondary_keywords=["MTD submission dates", "when to file MTD return"],
          priority=5),
    topic("MTD Bridging Software for Landlords: What Is It and Do You Need It?",
          "MTD bridging software landlord", "Making Tax Digital (MTD)",
          secondary_keywords=["bridging software property", "MTD digital link spreadsheet"],
          priority=2),
    topic("What Happens to Self Assessment After MTD for Landlords?",
          "self assessment after MTD landlords", "Making Tax Digital (MTD)",
          secondary_keywords=["MTD replace self assessment", "SA105 after MTD"],
          priority=3),
]

CGT_TOPICS = [
    topic("How Is CGT Calculated on an Inherited Rental Property?",
          "CGT inherited rental property", "Capital Gains Tax",
          secondary_keywords=["probate value CGT", "inherited buy to let tax"],
          priority=4),
    topic("The 60-Day CGT Reporting Rule for Property Sales: Complete Guide",
          "60 day CGT reporting property", "Capital Gains Tax",
          secondary_keywords=["capital gains tax 60 days", "report property sale HMRC"],
          priority=5, title_format="how-to"),
    topic("Non-Resident CGT on UK Property: Rates and Reporting Requirements",
          "non resident CGT UK property", "Capital Gains Tax",
          secondary_keywords=["overseas landlord CGT", "non resident capital gains tax"],
          priority=4),
    topic("CGT on Selling a Buy-to-Let Property: Step-by-Step Calculation",
          "CGT selling buy to let property", "Capital Gains Tax",
          secondary_keywords=["sell BTL capital gains", "CGT calculation example"],
          priority=5, title_format="how-to"),
    topic("Letting Relief for Landlords: What's Left After the Changes?",
          "letting relief landlords", "Capital Gains Tax",
          secondary_keywords=["letting relief 2026", "£40,000 letting relief"],
          priority=3, related_existing="principal-private-residence-relief-landlords",
          differentiation="letting relief focus vs broader PPR guide"),
    topic("CGT Annual Exempt Amount 2026/27: How to Use Your £3,000 Allowance",
          "CGT annual exempt amount 2026", "Capital Gains Tax",
          secondary_keywords=["CGT allowance £3000", "annual exemption capital gains"],
          priority=4),
    topic("How to Report a Property Sale to HMRC Within 60 Days",
          "report property sale HMRC 60 days", "Capital Gains Tax",
          secondary_keywords=["CGT online reporting", "HMRC property disposal form"],
          priority=5, title_format="how-to"),
    topic("Capital Gains Tax Rates for Property 2026/27: Current Rates Explained",
          "CGT rates property 2026", "Capital Gains Tax",
          secondary_keywords=["18% 24% CGT rate", "property CGT rates"],
          priority=4, related_existing="capital-gains-tax-property-sale-uk-2026-rates-allowances",
          differentiation="concise rate reference vs comprehensive sale guide"),
    topic("How 2027 Property Tax Rates Affect Capital Gains Tax",
          "2027 property tax rates CGT", "Capital Gains Tax",
          secondary_keywords=["CGT 2027 changes", "capital gains tax property 2027"],
          priority=5),
    topic("Using Capital Losses to Reduce CGT on Property",
          "capital losses reduce CGT property", "Capital Gains Tax",
          secondary_keywords=["offset losses CGT", "carry forward capital losses"],
          priority=3, related_existing="reduce-cgt-property-disposal-uk",
          differentiation="losses-specific vs broad reduction strategies"),
    topic("CGT on Property Sold at a Loss: Can You Claim the Loss?",
          "CGT property sold loss", "Capital Gains Tax",
          secondary_keywords=["capital loss rental property", "selling BTL at a loss"],
          priority=3),
    topic("CGT on Commercial Property: How Is It Different?",
          "CGT commercial property", "Capital Gains Tax",
          secondary_keywords=["capital gains commercial premises", "business property CGT"],
          priority=3),
    topic("Rollover Relief for Property: When Can Landlords Use It?",
          "rollover relief property", "Capital Gains Tax",
          secondary_keywords=["CGT rollover property business", "reinvestment relief"],
          priority=3),
    topic("PPR Relief Calculation: How to Work Out Your Exempt Period",
          "PPR relief calculation", "Capital Gains Tax",
          secondary_keywords=["principal private residence calculation", "time apportioned PPR"],
          priority=4, title_format="how-to",
          related_existing="principal-private-residence-relief-landlords",
          differentiation="calculation method vs comprehensive relief guide"),
    topic("CGT on Gifting Property to Family Members",
          "CGT gifting property family", "Capital Gains Tax",
          secondary_keywords=["gift property to children CGT", "market value disposal"],
          priority=3),
    topic("CGT and Divorce: Property Transfer Tax Implications",
          "CGT divorce property transfer", "Capital Gains Tax",
          secondary_keywords=["divorce settlement property CGT", "transfer property ex-spouse"],
          priority=3, related_existing="cgt-property-transfer-spouse",
          differentiation="divorce-specific vs general spousal transfer"),
    topic("CGT on Selling Multiple Properties in the Same Year",
          "CGT selling multiple properties same year", "Capital Gains Tax",
          secondary_keywords=["portfolio disposal CGT", "annual allowance multiple sales"],
          priority=3, title_format="scenario"),
    topic("CGT Deferral Strategies for UK Property Investors",
          "CGT deferral strategies property", "Capital Gains Tax",
          secondary_keywords=["defer capital gains tax", "EIS deferral property"],
          priority=3),
    topic("Inheritance Tax on Rental Property: What Landlords Need to Know",
          "inheritance tax rental property", "Capital Gains Tax",
          secondary_keywords=["IHT buy to let", "estate planning landlord"],
          priority=4),
    topic("Business Property Relief and Rental Property: Does It Apply?",
          "business property relief rental property", "Capital Gains Tax",
          secondary_keywords=["BPR landlord", "IHT relief investment property"],
          priority=3),
    topic("CGT on Property: 2027 Rate Changes and What They Mean",
          "CGT property 2027 rate changes", "Capital Gains Tax",
          secondary_keywords=["capital gains tax 2027", "CGT rate increase property"],
          priority=5),
    topic("Property Capital Gains Tax Record Keeping: What to Save and for How Long",
          "CGT record keeping property", "Capital Gains Tax",
          secondary_keywords=["CGT records HMRC", "property sale documentation"],
          priority=3),
    topic("Enhancement Expenditure and CGT: What Improvements Reduce Your Gain?",
          "enhancement expenditure CGT property", "Capital Gains Tax",
          secondary_keywords=["improvements reduce CGT", "capital expenditure base cost"],
          priority=3),
    topic("CGT Main Residence Election for Landlords with Two Properties",
          "CGT main residence election two properties", "Capital Gains Tax",
          secondary_keywords=["nominate main residence CGT", "two homes CGT election"],
          priority=3),
]

PORTFOLIO_MANAGEMENT_TOPICS = [
    topic("How to Track Rental Property Profitability: Per-Property P&L Guide",
          "track rental property profitability", "Portfolio Management",
          secondary_keywords=["property P&L", "rental property profit tracking"],
          priority=4, title_format="how-to",
          related_existing="property-portfolio-accounting-tracking-profitability",
          differentiation="practical tracking method vs overview of accounting services"),
    topic("Rental Yield vs Return on Investment: What's the Difference?",
          "rental yield vs ROI", "Portfolio Management",
          secondary_keywords=["yield vs return landlord", "ROI rental property"],
          priority=3, related_existing="rental-yield-calculator-guide-uk-landlords",
          differentiation="yield vs ROI comparison vs calculator guide"),
    topic("When to Sell a Rental Property: Key Indicators for Landlords",
          "when to sell rental property", "Portfolio Management",
          secondary_keywords=["exit strategy landlord", "sell BTL property timing"],
          priority=3),
    topic("How to Scale a Buy-to-Let Portfolio from 1 to 10 Properties",
          "scale buy to let portfolio", "Portfolio Management",
          secondary_keywords=["grow property portfolio", "buying second BTL property"],
          priority=4, title_format="how-to"),
    topic("Property Portfolio Review: Annual Checklist for Landlords",
          "property portfolio review checklist", "Portfolio Management",
          secondary_keywords=["annual review landlord", "property investment health check"],
          priority=3),
    topic("Refinancing a Rental Property: When Does It Make Financial Sense?",
          "refinancing rental property", "Portfolio Management",
          secondary_keywords=["remortgage BTL equity", "release equity rental property"],
          priority=3, related_existing="buy-to-let-refinancing-when-does-it-make-sense",
          differentiation="portfolio management angle vs tax/timing angle"),
    topic("Managing Rental Property Cash Flow: Budgeting for Voids and Repairs",
          "rental property cash flow management", "Portfolio Management",
          secondary_keywords=["void periods budget", "maintenance fund landlord"],
          priority=3),
    topic("Property Investment Benchmarks UK: What's a Good Yield in 2026?",
          "property investment benchmarks UK 2026", "Portfolio Management",
          secondary_keywords=["average rental yield UK", "BTL benchmark returns"],
          priority=4),
    topic("Record Keeping for Landlords: What to Track and How Long to Keep It",
          "record keeping landlords", "Portfolio Management",
          secondary_keywords=["landlord records HMRC", "how long keep rental records"],
          priority=4, title_format="how-to"),
    topic("Multi-Property Landlord Tax Planning: Strategies for 5+ Properties",
          "multi property landlord tax planning", "Portfolio Management",
          secondary_keywords=["large portfolio tax strategy", "5 plus properties tax"],
          priority=3),
    topic("Landlord Accounting Spreadsheet: Free Template and Guide",
          "landlord accounting spreadsheet template", "Portfolio Management",
          secondary_keywords=["rental property spreadsheet", "Excel template landlord"],
          priority=4, title_format="how-to"),
    topic("Property Investment vs Stocks and Shares: Tax Comparison",
          "property investment vs stocks tax comparison", "Portfolio Management",
          secondary_keywords=["BTL vs ISA tax", "property vs equities tax"],
          priority=3, title_format="comparison"),
    topic("How to Value a Rental Property Portfolio for Tax Purposes",
          "value rental property portfolio tax", "Portfolio Management",
          secondary_keywords=["portfolio valuation landlord", "market value property tax"],
          priority=3),
    topic("Rental Property Due Diligence: Tax Checks Before You Buy",
          "rental property due diligence tax", "Portfolio Management",
          secondary_keywords=["tax checks before buying BTL", "BTL purchase checklist"],
          priority=3),
    topic("Landlord Tax Calendar 2026/27: Every Key Date You Need",
          "landlord tax calendar 2026", "Portfolio Management",
          secondary_keywords=["tax deadlines landlord", "self assessment dates 2026"],
          priority=5),
    topic("Property Company vs Personal: When to Split Your Portfolio",
          "property company vs personal split portfolio", "Portfolio Management",
          secondary_keywords=["hybrid structure landlord", "some properties in company"],
          priority=3, related_existing="limited-company-vs-personal-ownership-tax-comparison-2026",
          differentiation="hybrid/split strategy vs binary comparison"),
    topic("How to Calculate Net Rental Income After All Costs",
          "calculate net rental income", "Portfolio Management",
          secondary_keywords=["net rental profit", "rental income after expenses"],
          priority=4, title_format="how-to"),
    topic("Property Portfolio Diversification: Residential, Commercial, and HMO",
          "property portfolio diversification", "Portfolio Management",
          secondary_keywords=["diversify property investments", "mix of property types"],
          priority=3),
    topic("End of Tax Year Checklist for Landlords: April 2026",
          "end of tax year checklist landlords 2026", "Portfolio Management",
          secondary_keywords=["year end landlord tasks", "5 April landlord checklist"],
          priority=4),
    topic("What Is a Good Gross Yield for a Buy-to-Let Property?",
          "good gross yield buy to let", "Portfolio Management",
          secondary_keywords=["average BTL yield UK", "minimum acceptable yield"],
          priority=3),
    topic("How to Reduce Void Periods on Rental Properties",
          "reduce void periods rental", "Portfolio Management",
          secondary_keywords=["minimise voids landlord", "avoid empty rental property"],
          priority=3, title_format="how-to"),
    topic("Landlord Insurance Guide: Types, Costs, and Tax Deductibility",
          "landlord insurance guide types costs", "Portfolio Management",
          secondary_keywords=["BTL insurance types", "landlord insurance comparison"],
          priority=3, related_existing="landlord-insurance-tax-deductible",
          differentiation="broad insurance guide vs tax deductibility focus"),
    topic("Property Investment Exit Strategy: Planning Your Long-Term Goals",
          "property investment exit strategy", "Portfolio Management",
          secondary_keywords=["sell portfolio plan", "landlord retirement strategy"],
          priority=3),
    topic("How Much Deposit Do You Need for a Buy-to-Let in 2026?",
          "deposit buy to let 2026", "Portfolio Management",
          secondary_keywords=["BTL mortgage deposit", "minimum deposit buy to let"],
          priority=4),
    topic("Landlord Tax Return Penalties: What Happens If You're Late?",
          "landlord tax return penalties late", "Portfolio Management",
          secondary_keywords=["HMRC penalty late tax return", "self assessment late filing"],
          priority=4, related_existing="landlord-tax-return-deadline-2026",
          differentiation="penalty detail vs deadline overview"),
]

PROPERTY_ACCOUNTANT_SERVICES_TOPICS = []

UK_CITIES = [
    "Edinburgh", "Liverpool", "Newcastle", "Sheffield", "Nottingham",
    "Cardiff", "Southampton", "Brighton", "Cambridge", "Oxford",
    "Reading", "Plymouth", "York", "Bath", "Norwich",
    "Exeter", "Derby", "Wolverhampton", "Portsmouth", "Aberdeen",
    "Dundee", "Swansea", "Belfast", "Milton Keynes", "Northampton",
    "Bournemouth", "Cheltenham", "Ipswich", "Preston", "Middlesbrough",
    "Swindon", "Warrington", "Peterborough", "Luton", "Slough",
    "Stockport", "Sunderland", "Leeds",
]

for city in UK_CITIES:
    slug = f"{slugify(city)}-property-accountant"
    PROPERTY_ACCOUNTANT_SERVICES_TOPICS.append(
        topic(
            f"{city} Property Accountant: Expert Tax Services for Local Landlords",
            f"property accountant {city.lower()}", "Property Accountant Services",
            secondary_keywords=[f"buy to let accountant {city.lower()}", f"landlord tax advice {city.lower()}"],
            priority=3 if city not in ("Edinburgh", "Liverpool", "Newcastle", "Sheffield", "Leeds") else 4,
            title_format="location",
            slug_override=slug,
            differentiation=f"city-specific content for {city}",
        )
    )

PROPERTY_ACCOUNTANT_SERVICES_TOPICS.extend([
    topic("Buy-to-Let Accountant: What Services Do You Need?",
          "buy to let accountant", "Property Accountant Services",
          secondary_keywords=["BTL accountant services", "accountants for buy to let"],
          priority=4, related_existing="what-does-a-property-accountant-do",
          differentiation="BTL-specific framing vs general property accountant"),
    topic("Accountants for Property Investors: What to Expect",
          "accountants property investors", "Property Accountant Services",
          secondary_keywords=["property investment accountant", "specialist accountant landlord"],
          priority=4, related_existing="what-does-a-property-accountant-do",
          differentiation="investor framing vs general service overview"),
    topic("Online Property Accountant: Is Remote Accounting Right for You?",
          "online property accountant", "Property Accountant Services",
          secondary_keywords=["remote property accountant", "virtual accountant landlord"],
          priority=3, related_existing="property-accountant-near-me",
          differentiation="online/remote focus vs local search guide"),
])

LANDLORD_TAX_ESSENTIALS_TOPICS = [
    topic("Income Tax Rates for Landlords 2026/27: Complete Band Guide",
          "income tax rates landlords 2026", "Landlord Tax Essentials",
          secondary_keywords=["rental income tax bands", "landlord tax brackets 2026"],
          priority=5, related_existing="property-investment-tax-uk-complete-guide-2026",
          differentiation="focused rate reference vs broad investment tax guide"),
    topic("2027 Property Income Tax Rates: What the Separate Rates Mean for Landlords",
          "2027 property income tax rates landlords", "Landlord Tax Essentials",
          secondary_keywords=["22% basic rate property income", "separate property tax bands 2027"],
          priority=5, differentiation="2027 landmark change, no existing coverage"),
    topic("How Much Tax Do I Pay on Rental Income UK?",
          "how much tax rental income UK", "Landlord Tax Essentials",
          secondary_keywords=["tax on rent received", "rental income tax bill"],
          priority=5, title_format="question",
          related_existing="rental-income-tax-uk-complete-guide-landlords",
          differentiation="quick answer format vs comprehensive guide"),
    topic("SDLT for Buy-to-Let Purchases: Rates, Surcharge, and Exemptions",
          "SDLT buy to let rates surcharge", "Landlord Tax Essentials",
          secondary_keywords=["stamp duty additional property", "5% SDLT surcharge BTL"],
          priority=4, related_existing="stamp-duty-buy-to-let-surcharge",
          differentiation="expanded guide with exemptions vs surcharge explainer"),
    topic("First-Time Landlord Tax Guide: Everything You Need to Know",
          "first time landlord tax guide", "Landlord Tax Essentials",
          secondary_keywords=["new landlord tax obligations", "buying first BTL tax"],
          priority=5, title_format="how-to"),
    topic("What Is the Property Income Allowance and Can Landlords Use It?",
          "property income allowance landlord", "Landlord Tax Essentials",
          secondary_keywords=["£1000 property allowance", "property income allowance HMRC"],
          priority=3),
    topic("Landlord Self Assessment: Step-by-Step Filing Guide",
          "landlord self assessment filing guide", "Landlord Tax Essentials",
          secondary_keywords=["file tax return landlord", "SA105 step by step"],
          priority=4, title_format="how-to",
          related_existing="landlord-tax-return-complete-guide-2026",
          differentiation="practical filing steps vs comprehensive guide overview"),
    topic("Overseas Rental Income: How Is It Taxed in the UK?",
          "overseas rental income UK tax", "Landlord Tax Essentials",
          secondary_keywords=["foreign property rental income", "tax on overseas property UK"],
          priority=3),
    topic("Penalties for Not Declaring Rental Income UK",
          "penalties not declaring rental income", "Landlord Tax Essentials",
          secondary_keywords=["HMRC undeclared rental income", "let property campaign"],
          priority=4),
    topic("What Is the Let Property Campaign and Should You Use It?",
          "let property campaign", "Landlord Tax Essentials",
          secondary_keywords=["HMRC voluntary disclosure", "undeclared rent HMRC"],
          priority=3),
    topic("Landlord Tax Changes 2026: Every Change You Need to Know",
          "landlord tax changes 2026", "Landlord Tax Essentials",
          secondary_keywords=["tax changes April 2026 landlord", "new tax rules landlords"],
          priority=5),
    topic("Council Tax vs Business Rates for Landlords: Which Applies?",
          "council tax vs business rates landlord", "Landlord Tax Essentials",
          secondary_keywords=["HMO business rates", "when is property business rated"],
          priority=3, related_existing="property-business-rates-council-tax-landlords",
          differentiation="decision guide vs information overview"),
    topic("Can Landlords Claim Wear and Tear Allowance in 2026?",
          "wear and tear allowance landlords 2026", "Landlord Tax Essentials",
          secondary_keywords=["replacement domestic items relief", "furniture replacement deduction"],
          priority=3),
    topic("What Tax Do I Pay When I Sell My Rental Property?",
          "tax sell rental property UK", "Landlord Tax Essentials",
          secondary_keywords=["selling BTL tax implications", "tax on property sale landlord"],
          priority=5, title_format="question"),
    topic("SDLT Non-Resident Surcharge: 2% Extra for Overseas Buyers",
          "SDLT non resident surcharge", "Landlord Tax Essentials",
          secondary_keywords=["overseas buyer stamp duty", "2% non resident surcharge SDLT"],
          priority=3),
    topic("Rental Losses: How to Carry Forward and Use Them",
          "rental losses carry forward", "Landlord Tax Essentials",
          secondary_keywords=["property loss relief", "set off rental losses"],
          priority=3),
    topic("Mixed-Use Property Tax: How Is It Different?",
          "mixed use property tax", "Landlord Tax Essentials",
          secondary_keywords=["shop with flat above tax", "commercial residential mixed"],
          priority=3),
    topic("Renters' Rights Act 2026: Tax Implications for Landlords",
          "renters rights act 2026 tax implications landlords", "Landlord Tax Essentials",
          secondary_keywords=["section 21 abolished tax", "renters reform bill landlord"],
          priority=4),
    topic("EPC Requirements for Landlords: Costs and Tax Deductibility",
          "EPC requirements landlords tax deductible", "Landlord Tax Essentials",
          secondary_keywords=["EPC minimum C landlord", "energy performance certificate cost"],
          priority=3),
    topic("ATED for Property Companies: Annual Tax on Enveloped Dwellings",
          "ATED property companies", "Landlord Tax Essentials",
          secondary_keywords=["annual tax enveloped dwellings", "ATED return property company"],
          priority=3),
    topic("Tax Planning for Landlords with Multiple Income Sources",
          "tax planning landlords multiple income", "Landlord Tax Essentials",
          secondary_keywords=["PAYE and rental income", "self employment plus rental"],
          priority=3),
    topic("How to Amend a Landlord Tax Return: Mistakes and Corrections",
          "amend landlord tax return", "Landlord Tax Essentials",
          secondary_keywords=["correct self assessment", "amend SA105"],
          priority=3, title_format="how-to"),
]

PROPERTY_TYPES_TOPICS = [
    topic("HMO Tax Guide: Multi-Tenant Property Income and Deductions",
          "HMO tax guide", "Property Types & Specialist Tax",
          secondary_keywords=["HMO rental income tax", "multi-tenant property deductions"],
          priority=5, related_existing="hmo-landlord-accounting-multi-tenant-property-tax",
          differentiation="comprehensive tax guide vs accounting overview"),
    topic("HMO Licensing Costs: Are They Tax Deductible?",
          "HMO licensing costs tax deductible", "Property Types & Specialist Tax",
          secondary_keywords=["selective licensing fee deduction", "HMO license expense"],
          priority=4, content_stream="expense_spoke"),
    topic("HMO Capital Allowances: What Can Multi-Tenant Landlords Claim?",
          "HMO capital allowances", "Property Types & Specialist Tax",
          secondary_keywords=["communal area allowances", "HMO furniture replacement"],
          priority=3),
    topic("Room-by-Room Accounting for HMOs: How to Track Individual Rooms",
          "room by room accounting HMO", "Property Types & Specialist Tax",
          secondary_keywords=["HMO room profitability", "multi-tenant record keeping"],
          priority=3, title_format="how-to"),
    topic("HMO vs Standard Buy-to-Let: Tax Comparison",
          "HMO vs standard buy to let tax", "Property Types & Specialist Tax",
          secondary_keywords=["HMO tax advantages", "multi-let vs single let tax"],
          priority=4, title_format="comparison"),
    topic("Student Accommodation Tax: What Landlords Need to Know",
          "student accommodation tax landlord", "Property Types & Specialist Tax",
          secondary_keywords=["student let tax", "university property tax"],
          priority=3),
    topic("Student Let Business Rates Exemption: When Does It Apply?",
          "student let business rates exemption", "Property Types & Specialist Tax",
          secondary_keywords=["council tax student property", "exempt from business rates"],
          priority=3),
    topic("Commercial Property Tax for Landlords: Rates, Reliefs, and Allowances",
          "commercial property tax landlords", "Property Types & Specialist Tax",
          secondary_keywords=["commercial landlord tax", "business premises tax"],
          priority=4),
    topic("Capital Allowances on Commercial Property: What Can You Claim?",
          "capital allowances commercial property", "Property Types & Specialist Tax",
          secondary_keywords=["plant and machinery allowances", "structures and buildings allowance"],
          priority=4),
    topic("Business Rates for Commercial Property: How They Work",
          "business rates commercial property", "Property Types & Specialist Tax",
          secondary_keywords=["rateable value", "business rates revaluation 2026"],
          priority=3),
    topic("VAT on Commercial Property: Option to Tax Explained",
          "VAT commercial property option to tax", "Property Types & Specialist Tax",
          secondary_keywords=["commercial rent VAT", "option to tax 20 years"],
          priority=3),
    topic("Serviced Accommodation Tax After FHL Abolition: What's Changed",
          "serviced accommodation tax FHL abolition", "Property Types & Specialist Tax",
          secondary_keywords=["Airbnb tax after April 2025", "holiday let tax changes"],
          priority=5, related_existing="furnished-holiday-let-tax-rules-exemptions",
          differentiation="post-abolition serviced accommodation vs abolition overview"),
    topic("Airbnb Tax UK: How Is Short-Term Rental Income Taxed?",
          "Airbnb tax UK", "Property Types & Specialist Tax",
          secondary_keywords=["short term rental tax", "holiday rental income tax"],
          priority=5),
    topic("Serviced Accommodation vs Buy-to-Let: Tax Comparison 2026",
          "serviced accommodation vs buy to let tax", "Property Types & Specialist Tax",
          secondary_keywords=["SA vs BTL", "short term vs long term rental tax"],
          priority=4, title_format="comparison"),
    topic("Holiday Let Tax Calculator: Work Out Your Tax Bill After FHL Changes",
          "holiday let tax calculator", "Property Types & Specialist Tax",
          secondary_keywords=["FHL calculator 2026", "holiday lettings tax"],
          priority=4),
    topic("Property Development Tax: Trading vs Investment Income",
          "property development tax trading vs investment", "Property Types & Specialist Tax",
          secondary_keywords=["developer tax treatment", "badges of trade property"],
          priority=4, related_existing="residential-property-developer-tax-uk",
          differentiation="trading classification focus vs comprehensive developer guide"),
    topic("What Are the Badges of Trade for Property Developers?",
          "badges of trade property developers", "Property Types & Specialist Tax",
          secondary_keywords=["HMRC property trading test", "developer or investor"],
          priority=3, title_format="definition"),
    topic("Construction Industry Scheme (CIS) for Property Developers",
          "CIS property developers", "Property Types & Specialist Tax",
          secondary_keywords=["construction industry scheme property", "CIS deductions developer"],
          priority=3),
    topic("VAT for Property Developers: Registration and Recovery",
          "VAT property developers", "Property Types & Specialist Tax",
          secondary_keywords=["developer VAT registration", "input VAT recovery property"],
          priority=3),
    topic("Stamp Duty on Furnished Holiday Lets: Post-2025 Rules",
          "stamp duty furnished holiday lets", "Property Types & Specialist Tax",
          secondary_keywords=["SDLT holiday let", "stamp duty short term rental"],
          priority=3, related_existing="furnished-holiday-let-tax-rules-exemptions",
          differentiation="SDLT-specific vs broad FHL rule changes"),
    topic("Garage and Parking Space Rental: Tax Treatment for Landlords",
          "garage parking space rental tax", "Property Types & Specialist Tax",
          secondary_keywords=["rent out garage tax", "parking space income tax"],
          priority=2),
    topic("Are Mortgage Payments on a Holiday Let Tax Deductible?",
          "mortgage payments holiday let tax deductible", "Property Types & Specialist Tax",
          secondary_keywords=["holiday rental mortgage interest", "FHL mortgage deduction"],
          priority=3),
    topic("How Much Tax Do You Pay on a Holiday Let Property?",
          "how much tax holiday let property", "Property Types & Specialist Tax",
          secondary_keywords=["holiday let income tax", "tax on holiday rental"],
          priority=4, title_format="question"),
]

NRL_TOPICS = [
    topic("Non-Resident Landlord Scheme: Complete UK Guide",
          "non resident landlord scheme UK", "Non-Resident Landlord Tax",
          secondary_keywords=["NRL scheme", "overseas landlord UK property"],
          priority=5, content_tier="pillar"),
    topic("NRL Withholding Tax: How the 20% Deduction Works",
          "NRL withholding tax 20%", "Non-Resident Landlord Tax",
          secondary_keywords=["letting agent withhold tax", "basic rate deduction NRL"],
          priority=4),
    topic("How to Apply for NRL Approval to Receive Rent Gross",
          "NRL approval receive rent gross", "Non-Resident Landlord Tax",
          secondary_keywords=["HMRC NRL1 form", "self assessment NRL"],
          priority=4, title_format="how-to"),
    topic("Non-Resident CGT: Selling UK Property from Overseas",
          "non resident CGT UK property", "Non-Resident Landlord Tax",
          secondary_keywords=["overseas landlord selling property CGT", "non resident capital gains"],
          priority=4),
    topic("Double Taxation Relief for UK Rental Income: Country-by-Country Guide",
          "double taxation relief UK rental income", "Non-Resident Landlord Tax",
          secondary_keywords=["tax treaty rental income", "avoid paying tax twice property"],
          priority=3),
    topic("Non-Resident Landlord Self Assessment: Filing Requirements",
          "non resident landlord self assessment", "Non-Resident Landlord Tax",
          secondary_keywords=["overseas landlord tax return UK", "NRL self assessment filing"],
          priority=4, title_format="how-to"),
    topic("Non-Resident Company Owning UK Property: Tax Implications",
          "non resident company UK property tax", "Non-Resident Landlord Tax",
          secondary_keywords=["overseas company rental income UK", "corporation tax non resident"],
          priority=3),
    topic("SDLT Non-Resident Surcharge: The 2% Extra Charge Explained",
          "SDLT non resident surcharge 2%", "Non-Resident Landlord Tax",
          secondary_keywords=["overseas buyer stamp duty", "non resident SDLT rates"],
          priority=3),
    topic("Register of Overseas Entities: Compliance for Non-Resident Landlords",
          "register overseas entities property", "Non-Resident Landlord Tax",
          secondary_keywords=["ROE Companies House", "overseas entity register property"],
          priority=3),
    topic("ATED for Non-Resident Property Companies",
          "ATED non resident property company", "Non-Resident Landlord Tax",
          secondary_keywords=["annual tax enveloped dwellings overseas", "ATED non resident"],
          priority=3),
    topic("Non-Resident Landlord Tax Planning: Structure Options",
          "non resident landlord tax planning", "Non-Resident Landlord Tax",
          secondary_keywords=["overseas landlord structure UK", "NRL company vs personal"],
          priority=3),
    topic("UK Property Income for Expats: Tax Obligations Explained",
          "UK property income expats tax", "Non-Resident Landlord Tax",
          secondary_keywords=["expat landlord UK tax", "British expat rental income"],
          priority=4),
    topic("Non-Resident Landlord Letting Agent Obligations: What You Must Do",
          "non resident landlord letting agent obligations", "Non-Resident Landlord Tax",
          secondary_keywords=["NRL agent tax deduction", "letting agent withhold tax overseas"],
          priority=3),
    topic("Returning to the UK: Tax Implications for Non-Resident Landlords",
          "returning UK tax implications non resident landlord", "Non-Resident Landlord Tax",
          secondary_keywords=["become UK resident again property", "re-domicile landlord"],
          priority=2),
    topic("Non-Resident Landlord and MTD: Do Overseas Landlords Need to Comply?",
          "non resident landlord MTD", "Non-Resident Landlord Tax",
          secondary_keywords=["overseas landlord making tax digital", "NRL quarterly reporting"],
          priority=3),
]

EXPENSE_SPOKE_TOPICS = [
    topic("Are HMO Licensing Fees Tax Deductible for Landlords?",
          "HMO licensing fees tax deductible", "Landlord Tax Essentials",
          secondary_keywords=["selective licensing deduction", "HMO license cost tax"],
          priority=4, content_stream="expense_spoke", target_word_count=1200),
    topic("Can Landlords Claim Home Office Costs If Self-Managing?",
          "landlord home office costs self managing", "Landlord Tax Essentials",
          secondary_keywords=["home office deduction landlord", "self managing property expenses"],
          priority=3, content_stream="expense_spoke", target_word_count=1200),
    topic("Are EPC Assessment Costs Tax Deductible for Landlords?",
          "EPC assessment costs tax deductible landlord", "Landlord Tax Essentials",
          secondary_keywords=["energy performance certificate deduction", "EPC cost claim"],
          priority=3, content_stream="expense_spoke", target_word_count=1200),
    topic("Can Landlords Claim for Pest Control at a Rental Property?",
          "pest control rental property tax deductible", "Landlord Tax Essentials",
          secondary_keywords=["pest control landlord expense", "vermin treatment deduction"],
          priority=2, content_stream="expense_spoke", target_word_count=1000),
    topic("Are Inventory Check Costs Tax Deductible for Landlords?",
          "inventory check costs tax deductible landlord", "Landlord Tax Essentials",
          secondary_keywords=["check-in check-out deduction", "inventory service landlord"],
          priority=2, content_stream="expense_spoke", target_word_count=1000),
    topic("Is Tenant Referencing a Deductible Landlord Expense?",
          "tenant referencing deductible landlord", "Landlord Tax Essentials",
          secondary_keywords=["tenant screening cost tax", "reference check deduction"],
          priority=2, content_stream="expense_spoke", target_word_count=1000),
    topic("Can Landlords Claim for Fire Safety Compliance Costs?",
          "fire safety compliance costs landlord deductible", "Landlord Tax Essentials",
          secondary_keywords=["smoke alarm cost landlord", "fire door deduction"],
          priority=3, content_stream="expense_spoke", target_word_count=1200),
    topic("Are Landlord Selective Licensing Fees Tax Deductible?",
          "selective licensing fees tax deductible landlord", "Landlord Tax Essentials",
          secondary_keywords=["council selective licensing cost", "property licensing deduction"],
          priority=3, content_stream="expense_spoke", target_word_count=1200),
    topic("Can Landlords Deduct Energy Efficiency Improvement Costs?",
          "energy efficiency improvement costs landlord deductible", "Landlord Tax Essentials",
          secondary_keywords=["insulation cost deduction", "EPC upgrade tax relief"],
          priority=3, content_stream="expense_spoke", target_word_count=1200),
    topic("Are Property Company Formation Costs Tax Deductible?",
          "property company formation costs tax deductible", "Landlord Tax Essentials",
          secondary_keywords=["SPV setup costs deduction", "company registration fee tax"],
          priority=3, content_stream="expense_spoke", target_word_count=1200),
    topic("Can Landlords Claim for Damp and Mould Remediation?",
          "damp mould remediation landlord tax deductible", "Landlord Tax Essentials",
          secondary_keywords=["damp treatment deduction", "mould repair landlord expense"],
          priority=3, content_stream="expense_spoke", target_word_count=1200),
    topic("Are Right to Rent Check Costs Tax Deductible?",
          "right to rent check costs tax deductible", "Landlord Tax Essentials",
          secondary_keywords=["immigration check landlord", "right to rent expense"],
          priority=2, content_stream="expense_spoke", target_word_count=1000),
]

TOOL_TOPICS = [
    {"title": "Stamp Duty Calculator for Buy-to-Let", "slug": "stamp-duty-calculator-buy-to-let",
     "type": "calculator", "priority": 5, "action": "create"},
    {"title": "CGT on Property Sale Calculator", "slug": "cgt-property-sale-calculator",
     "type": "calculator", "priority": 5, "action": "create"},
    {"title": "Rental Yield Calculator", "slug": "rental-yield-calculator",
     "type": "calculator", "priority": 4, "action": "create"},
    {"title": "BTL Mortgage Affordability Calculator", "slug": "btl-mortgage-affordability-calculator",
     "type": "calculator", "priority": 3, "action": "create"},
    {"title": "Property Company Profit Extraction Calculator", "slug": "profit-extraction-calculator",
     "type": "calculator", "priority": 3, "action": "create"},
    {"title": "SDLT Surcharge Calculator", "slug": "sdlt-surcharge-calculator",
     "type": "calculator", "priority": 3, "action": "create"},
    {"title": "Section 24 Impact Calculator", "slug": "section-24-impact-calculator",
     "type": "calculator", "priority": 4, "action": "enhance"},
    {"title": "Rental Income Tax Calculator", "slug": "rental-income-tax-calculator-tool",
     "type": "calculator", "priority": 4, "action": "enhance"},
    {"title": "Incorporation Savings Calculator", "slug": "incorporation-savings-calculator",
     "type": "calculator", "priority": 4, "action": "enhance"},
    {"title": "MTD Quarterly Deadline Calculator", "slug": "mtd-quarterly-deadline-calculator",
     "type": "calculator", "priority": 3, "action": "create"},
    {"title": "IHT Property Estate Calculator", "slug": "iht-property-estate-calculator",
     "type": "calculator", "priority": 2, "action": "create"},
]

FAQ_SCHEMA_TARGETS = [
    {"slug": "section-24-tax-relief-complete-guide", "faq_angle": "What is Section 24?"},
    {"slug": "section-24-mortgage-interest-restriction-uk-landlords", "faq_angle": "What is the mortgage interest restriction?"},
    {"slug": "capital-gains-tax-property-complete-guide-uk", "faq_angle": "What is CGT on property?"},
    {"slug": "making-tax-digital-landlords-april-2026-deadline", "faq_angle": "What is MTD for landlords?"},
    {"slug": "principal-private-residence-relief-landlords", "faq_angle": "What is PPR relief?"},
    {"slug": "incorporation-holdover-relief-property", "faq_angle": "What is holdover relief?"},
    {"slug": "landlord-tax-deductions-uk-2026-complete-list", "faq_angle": "What expenses can landlords deduct?"},
    {"slug": "furnished-holiday-let-tax-rules-exemptions", "faq_angle": "What are FHL tax rules?"},
    {"slug": "hmo-landlord-accounting-multi-tenant-property-tax", "faq_angle": "What is HMO accounting?"},
    {"slug": "stamp-duty-buy-to-let-surcharge", "faq_angle": "What is the BTL stamp duty surcharge?"},
    {"slug": "buy-to-let-limited-company-complete-guide-uk", "faq_angle": "What is a BTL limited company?"},
    {"slug": "landlord-capital-allowances-tax-relief", "faq_angle": "What are landlord capital allowances?"},
    {"slug": "property-company-dividend-tax", "faq_angle": "How is dividend tax calculated?"},
    {"slug": "rental-income-tax-uk-complete-guide-landlords", "faq_angle": "How is rental income taxed?"},
    {"slug": "sdlt-incorporation-stamp-duty-twice", "faq_angle": "Do you pay stamp duty twice?"},
    {"slug": "section-24-vs-incorporation-which-saves-more-tax", "faq_angle": "Section 24 vs incorporation?"},
    {"slug": "property-company-profit-extraction-salary-vs-dividends", "faq_angle": "Salary vs dividends?"},
    {"slug": "cgt-property-transfer-spouse", "faq_angle": "CGT on property transfer to spouse?"},
    {"slug": "director-loan-property-company", "faq_angle": "What is a director loan?"},
    {"slug": "landlord-vat-registration-when-required", "faq_angle": "When do landlords need VAT registration?"},
]


def build_matrix():
    existing_slugs = get_existing_slugs()

    all_substantive = (
        SECTION_24_TOPICS + INCORPORATION_TOPICS + MTD_TOPICS +
        CGT_TOPICS + PORTFOLIO_MANAGEMENT_TOPICS +
        PROPERTY_ACCOUNTANT_SERVICES_TOPICS + LANDLORD_TAX_ESSENTIALS_TOPICS +
        PROPERTY_TYPES_TOPICS + NRL_TOPICS
    )

    # Deduplicate against existing posts
    new_substantive = [t for t in all_substantive if t["slug"] not in existing_slugs]
    skipped = [t for t in all_substantive if t["slug"] in existing_slugs]

    new_expense = [t for t in EXPENSE_SPOKE_TOPICS if t["slug"] not in existing_slugs]

    pillar_counts = {}
    for t in new_substantive + new_expense:
        cat = t.get("cannibalization_check", {}).get("related_existing", "") or "none"
        cat_name = t.get("primary_keyword", "unknown")
        # Actually group by category from the topic function - find it in title context
        pass

    # Group by category
    pillars = {}
    for t in new_substantive:
        cat = "Unknown"
        for cat_list, cat_name in [
            (SECTION_24_TOPICS, "Section 24 & Tax Relief"),
            (INCORPORATION_TOPICS, "Incorporation & Company Structures"),
            (MTD_TOPICS, "Making Tax Digital (MTD)"),
            (CGT_TOPICS, "Capital Gains Tax"),
            (PORTFOLIO_MANAGEMENT_TOPICS, "Portfolio Management"),
            (PROPERTY_ACCOUNTANT_SERVICES_TOPICS, "Property Accountant Services"),
            (LANDLORD_TAX_ESSENTIALS_TOPICS, "Landlord Tax Essentials"),
            (PROPERTY_TYPES_TOPICS, "Property Types & Specialist Tax"),
            (NRL_TOPICS, "Non-Resident Landlord Tax"),
        ]:
            if t in cat_list:
                cat = cat_name
                break
        if cat not in pillars:
            pillars[cat] = {"name": cat, "slug": slugify(cat), "is_new": cat in ("Property Types & Specialist Tax", "Non-Resident Landlord Tax"), "existing_count": 0, "new_count": 0, "topics": []}
        pillars[cat]["topics"].append(t)
        pillars[cat]["new_count"] += 1

    # Count existing per category
    existing_categories = {}
    for s in existing_slugs:
        pass  # would need to read front matter; use known counts
    known_existing = {
        "Capital Gains Tax": 8, "Incorporation & Company Structures": 19,
        "Landlord Tax Essentials": 7, "Making Tax Digital (MTD)": 5,
        "Portfolio Management": 1, "Property Accountant Services": 19,
        "Section 24 & Tax Relief": 16,
        "Property Types & Specialist Tax": 0, "Non-Resident Landlord Tax": 0,
    }
    for cat, count in known_existing.items():
        if cat in pillars:
            pillars[cat]["existing_count"] = count

    matrix = {
        "generated_at": datetime.now().strftime("%Y-%m-%d"),
        "existing_posts": len(existing_slugs),
        "cannibalization_audit": {
            "locations": "blog-posts-only, /locations/ redirects to blog",
            "expenses": "hub-spoke, 10-15 niche spokes only",
            "glossary": "dropped, FAQ schema on existing guides",
        },
        "streams": {
            "substantive": {"new": len(new_substantive), "categories": len(pillars)},
            "expense_spokes": {"new": len(new_expense), "hub": "landlord-tax-deductions-uk-2026-complete-list"},
            "tools": {"new": len(TOOL_TOPICS), "type": "manual"},
        },
        "faq_schema_updates": len(FAQ_SCHEMA_TARGETS),
        "total_new": len(new_substantive) + len(new_expense) + len(TOOL_TOPICS),
        "total_pages": len(existing_slugs) + len(new_substantive) + len(new_expense) + len(TOOL_TOPICS),
        "skipped_existing_slugs": [t["slug"] for t in skipped],
        "pillars": sorted(pillars.values(), key=lambda p: -p["new_count"]),
        "expense_spoke_topics": new_expense,
        "tool_topics": TOOL_TOPICS,
        "faq_schema_targets": FAQ_SCHEMA_TARGETS,
    }
    return matrix


def main():
    matrix = build_matrix()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(matrix, f, indent=2, ensure_ascii=False)
    print(f"Content matrix written to {OUTPUT_PATH}")
    print(f"  Existing posts: {matrix['existing_posts']}")
    print(f"  New substantive: {matrix['streams']['substantive']['new']}")
    print(f"  New expense spokes: {matrix['streams']['expense_spokes']['new']}")
    print(f"  New tools: {matrix['streams']['tools']['new']}")
    print(f"  FAQ schema updates: {matrix['faq_schema_updates']}")
    print(f"  Total new: {matrix['total_new']}")
    print(f"  Total pages: {matrix['total_pages']}")


if __name__ == "__main__":
    main()
