"""Full verification suite for Dentists site after Phase 2 workspace migration.

Run after deploy to confirm:
1. All major route categories return 200 with reasonable content
2. JSON-LD on /locations/[slug] (the workspace-package-driven path) is valid
   and contains the AccountingService schema generated by
   @accounting-network/web-shared/lib/local-business-schema
3. Lead form submission path still works end-to-end (POSTs a test lead via the
   site's anon key, verifies it landed in Supabase `leads` table, cleans up)
4. Sitemap + robots.txt + 404 behaviour intact
5. No obvious regression in response sizes vs reasonable thresholds

Read-only against production except for the lead-form test (which inserts +
deletes one row tagged for cleanup).
"""
from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent.parent))

import requests  # noqa: E402

BASE = "https://www.dentalfinancepartners.co.uk"

# Load NEXT_PUBLIC_SUPABASE_* the same way the deployed site does (browser fetch)
try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).parent.parent / ".env")
except ImportError:
    pass

SUPABASE_URL = os.getenv("NEXT_PUBLIC_SUPABASE_URL") or os.getenv("SUPABASE_URL")
SUPABASE_ANON_KEY = os.getenv("NEXT_PUBLIC_SUPABASE_ANON_KEY") or os.getenv("SUPABASE_KEY")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_KEY")  # service role for the cleanup delete


ROUTES = [
    # (path, min_bytes, max_bytes, must_contain_substrings, description)
    ("/", 30_000, 250_000, ["Dental Finance Partners"], "Homepage"),
    ("/about", 20_000, 200_000, [], "About"),
    ("/contact", 20_000, 200_000, [], "Contact"),
    ("/services", 20_000, 200_000, [], "Services index"),
    ("/services/dental-accountants", 20_000, 200_000, [], "Service detail (dental-accountants)"),
    ("/services/associate-tax", 20_000, 200_000, [], "Service detail (associate-tax)"),
    ("/locations", 20_000, 200_000, [], "Locations index"),
    ("/locations/london", 30_000, 200_000, ['"@type":"AccountingService"', "London"], "London (workspace JSON-LD)"),
    ("/locations/manchester", 30_000, 200_000, ['"@type":"AccountingService"', "Manchester"], "Manchester (workspace JSON-LD)"),
    ("/calculators", 20_000, 200_000, [], "Calculators index"),
    ("/calculators/associate-take-home", 30_000, 300_000, [], "Associate take-home calculator"),
    ("/calculators/practice-valuation", 30_000, 300_000, [], "Practice valuation calculator"),
    ("/dental-guides", 20_000, 200_000, [], "Dental guides index"),
    ("/blog", 20_000, 5_000_000, [], "Blog index (~2.5MB known; renders all posts)"),
    ("/for-associates", 20_000, 200_000, [], "For Associates"),
    ("/for-practice-buyers", 20_000, 200_000, [], "For Practice Buyers"),
    ("/free-practice-health-check", 20_000, 200_000, [], "Free Practice Health Check"),
    ("/privacy-policy", 10_000, 100_000, [], "Privacy policy"),
    ("/terms", 10_000, 100_000, [], "Terms"),
    ("/cookie-policy", 10_000, 100_000, [], "Cookie policy"),
    ("/thank-you", 10_000, 100_000, [], "Thank you"),
    ("/sitemap.xml", 1000, 5_000_000, ["<urlset", "<url>"], "Sitemap"),
    ("/robots.txt", 50, 5000, ["User-Agent"], "robots.txt"),
]

# Sample blog posts (random selection across categories)
BLOG_POSTS = [
    "/blog/associate-tax/salary-vs-associate-fees-which-uk-dentist-tax",
    "/blog/practice-accounting/payment-on-account-uk-dentists-guide",
    "/blog/buying-a-practice/dental-practice-purchase-financial-due-diligence-checklist",
    "/blog/practice-finance/band-1-band-2-band-3-uda-treatment-explained",
    "/blog/vat-and-compliance/writing-down-allowance-cars-dentists",
]


def check_route(path: str, min_bytes: int, max_bytes: int, must_contain: list[str], desc: str) -> dict[str, Any]:
    url = f"{BASE}{path}"
    try:
        r = requests.get(url, timeout=20, allow_redirects=True)
    except requests.exceptions.RequestException as e:
        return {"path": path, "desc": desc, "ok": False, "error": str(e)}

    size = len(r.content)
    ok = r.status_code == 200 and min_bytes <= size <= max_bytes
    missing = [s for s in must_contain if s.encode() not in r.content]
    if missing:
        ok = False

    return {
        "path": path,
        "desc": desc,
        "status": r.status_code,
        "size": size,
        "ok": ok,
        "missing_substrings": missing,
    }


def test_lead_form() -> dict[str, Any]:
    """Submit a test lead via the same path as the site's LeadForm.tsx, verify
    it landed, then delete it via service role."""
    if not SUPABASE_URL or not SUPABASE_ANON_KEY:
        return {"ok": False, "error": "NEXT_PUBLIC_SUPABASE_* env vars missing"}

    test_email = f"verification-test-{int(time.time())}@example.com"
    payload = {
        "full_name": "Phase 2 Verification Test",
        "email": test_email,
        "phone": "+44 7000 000000",
        "role": "Associate",
        "practice_name": "Test Practice",
        "message": "Automated Phase 2 deployment verification — safe to delete.",
        "source": "dentists",
        "source_url": "https://www.dentalfinancepartners.co.uk/__verification_test",
        "submitted_at": time.strftime("%Y-%m-%dT%H:%M:%S+00:00", time.gmtime()),
    }

    headers_insert = {
        "Content-Type": "application/json",
        "apikey": SUPABASE_ANON_KEY,
        "Authorization": f"Bearer {SUPABASE_ANON_KEY}",
        "Prefer": "return=minimal",
    }

    # Step 1: submit as if from the public form (uses anon key)
    insert = requests.post(
        f"{SUPABASE_URL}/rest/v1/leads",
        headers=headers_insert,
        json=payload,
        timeout=15,
    )
    if insert.status_code not in (200, 201, 204):
        return {
            "ok": False,
            "error": f"Insert failed: status={insert.status_code} body={insert.text[:300]}",
        }

    # Step 2: verify via service role (anon can't read leads)
    headers_read = {
        "apikey": SUPABASE_SERVICE_KEY,
        "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}",
    }
    read = requests.get(
        f"{SUPABASE_URL}/rest/v1/leads?email=eq.{test_email}&select=*",
        headers=headers_read,
        timeout=15,
    )
    if read.status_code != 200 or not read.json():
        return {
            "ok": False,
            "error": f"Verification read failed: status={read.status_code} body={read.text[:300]}",
        }

    found = read.json()[0]

    # Step 3: cleanup — delete the test lead
    delete = requests.delete(
        f"{SUPABASE_URL}/rest/v1/leads?email=eq.{test_email}",
        headers=headers_read,
        timeout=15,
    )
    cleanup_ok = delete.status_code in (200, 204)

    return {
        "ok": True,
        "test_email": test_email,
        "verified_id": found.get("id"),
        "source": found.get("source"),
        "cleanup_ok": cleanup_ok,
    }


def test_404() -> dict[str, Any]:
    """A non-existent URL should 404 (not 200, not 500)."""
    r = requests.get(f"{BASE}/this-page-definitely-does-not-exist-9999", timeout=15)
    return {
        "ok": r.status_code == 404,
        "status": r.status_code,
    }


def test_json_ld_parses(path: str) -> dict[str, Any]:
    """Pull JSON-LD blocks from a page and verify each is valid JSON."""
    r = requests.get(f"{BASE}{path}", timeout=15)
    if r.status_code != 200:
        return {"ok": False, "error": f"status {r.status_code}"}

    import re
    blocks = re.findall(
        r'<script[^>]*type="application/ld\+json"[^>]*>([^<]+)</script>',
        r.text,
    )
    if not blocks:
        return {"ok": False, "error": "no JSON-LD blocks found"}

    parsed = []
    for i, block in enumerate(blocks):
        try:
            data = json.loads(block)
        except json.JSONDecodeError as e:
            return {"ok": False, "error": f"block {i} invalid JSON: {e}"}
        # JSON-LD blocks can be a single object OR an array of objects
        items = data if isinstance(data, list) else [data]
        for j, item in enumerate(items):
            if not isinstance(item, dict):
                continue
            parsed.append({"block": i, "item": j, "type": item.get("@type", "?")})

    return {"ok": True, "block_count": len(blocks), "types": parsed}


def main() -> None:
    print("=" * 78)
    print("PHASE 2 DENTISTS POST-DEPLOY VERIFICATION")
    print(f"Target: {BASE}")
    print("=" * 78)

    # Section 1: route checks
    print("\n[1/5] Route checks (HTTP status + size + content markers)\n")
    results = []
    for path, mn, mx, must, desc in ROUTES:
        r = check_route(path, mn, mx, must, desc)
        results.append(r)
        marker = "[OK]" if r.get("ok") else "[FAIL]"
        if "error" in r:
            print(f"  {marker} {r['path']:<40} {desc}: ERROR {r['error']}")
        else:
            extra = ""
            if r.get("missing_substrings"):
                extra = f" missing={r['missing_substrings']}"
            print(f"  {marker} {r['path']:<40} {r['status']} | {r['size']:>7} bytes | {desc}{extra}")

    # Section 2: blog posts
    print("\n[2/5] Sample blog post checks\n")
    for path in BLOG_POSTS:
        r = check_route(path, 20_000, 500_000, [], "Blog post")
        results.append(r)
        marker = "[OK]" if r.get("ok") else "[FAIL]"
        if "error" in r:
            print(f"  {marker} {path}: ERROR {r['error']}")
        else:
            print(f"  {marker} {path}: {r['status']} | {r['size']:>7} bytes")

    # Section 3: 404
    print("\n[3/5] 404 page behaviour\n")
    nf = test_404()
    print(f"  {'[OK]' if nf['ok'] else '[FAIL]'} Non-existent URL returns 404 (got {nf['status']})")

    # Section 4: JSON-LD parses cleanly
    print("\n[4/5] JSON-LD validity (workspace package output)\n")
    for p in ["/locations/london", "/locations/manchester", "/services/dental-accountants"]:
        j = test_json_ld_parses(p)
        if j["ok"]:
            types = [t["type"] for t in j["types"]]
            print(f"  [OK] {p}: {j['block_count']} JSON-LD blocks valid, types={types}")
        else:
            print(f"  [FAIL] {p}: {j.get('error')}")

    # Section 5: end-to-end lead form submission
    print("\n[5/5] Lead form end-to-end (POST + verify + cleanup)\n")
    lf = test_lead_form()
    if lf["ok"]:
        print(f"  [OK] Lead submitted via anon key, verified by service role, deleted.")
        print(f"       Test email: {lf['test_email']}")
        print(f"       Lead id: {lf['verified_id']}")
        print(f"       Source field: {lf['source']!r}")
        print(f"       Cleanup deleted: {lf['cleanup_ok']}")
    else:
        print(f"  [FAIL] {lf.get('error')}")

    # Summary
    print("\n" + "=" * 78)
    n_routes = len(results)
    n_route_ok = sum(1 for r in results if r.get("ok"))
    print(f"SUMMARY: {n_route_ok}/{n_routes} routes pass | 404 {'OK' if nf['ok'] else 'FAIL'} | Lead-form {'OK' if lf['ok'] else 'FAIL'}")
    overall_ok = n_route_ok == n_routes and nf["ok"] and lf["ok"]
    print(f"OVERALL: {'PASS' if overall_ok else 'FAIL'}")
    print("=" * 78)
    if not overall_ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
