"""
Database Setup - Generate Supabase migration and seed topic tree.
Creates blog_topics_{niche} table and populates with initial topics.
"""
import json
import os
import subprocess
from datetime import datetime
from typing import Dict, List


class DatabaseSetup:
    def __init__(self, supabase_project_dir: str):
        self.project_dir = supabase_project_dir
        self.migrations_dir = os.path.join(supabase_project_dir, "supabase", "migrations")
    
    def setup_database(self, niche_id: str, config: Dict, topic_tree: List[Dict]) -> Dict[str, str]:
        """
        Create migration and seed topic tree.
        
        Returns dict with:
        - migration_file: Path to migration SQL
        - topics_seeded: Count of topics seeded
        """
        
        print(f"\n=== Database Setup: {niche_id} ===")
        
        # 1. Generate migration
        print("\n[1/2] Generating migration...")
        migration_path = self._generate_migration(niche_id)
        print(f"  ✓ Created migration: {migration_path}")
        
        # 2. Seed topic tree
        print("\n[2/2] Seeding topic tree...")
        topics_count = self._seed_topics(niche_id, topic_tree)
        print(f"  ✓ Seeded {topics_count} topics")
        
        return {
            "migration_file": migration_path,
            "topics_seeded": str(topics_count)
        }
    
    def _generate_migration(self, niche_id: str) -> str:
        """Generate SQL migration for blog_topics_{niche} table."""
        
        os.makedirs(self.migrations_dir, exist_ok=True)
        
        # Generate timestamp-based filename
        timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
        filename = f"{timestamp}_create_blog_topics_{niche_id}.sql"
        filepath = os.path.join(self.migrations_dir, filename)
        
        table_name = f"blog_topics_{niche_id}"
        
        sql = f"""-- Create blog topics table for {niche_id} niche
CREATE TABLE IF NOT EXISTS public.{table_name} (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Topic details
    keyword TEXT NOT NULL,
    category TEXT NOT NULL,
    search_volume INTEGER,
    difficulty INTEGER,
    intent TEXT,
    
    -- Publishing status
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'published', 'skipped')),
    published_at TIMESTAMP WITH TIME ZONE,
    slug TEXT UNIQUE,
    
    -- Metadata
    notes TEXT,
    priority INTEGER DEFAULT 50,
    
    -- Indexes
    CONSTRAINT {table_name}_keyword_unique UNIQUE (keyword)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS {table_name}_status_idx ON public.{table_name}(status);
CREATE INDEX IF NOT EXISTS {table_name}_category_idx ON public.{table_name}(category);
CREATE INDEX IF NOT EXISTS {table_name}_priority_idx ON public.{table_name}(priority DESC);
CREATE INDEX IF NOT EXISTS {table_name}_published_at_idx ON public.{table_name}(published_at DESC);

-- Enable RLS
ALTER TABLE public.{table_name} ENABLE ROW LEVEL SECURITY;

-- Create RLS policies (read-only for anon, full access for authenticated)
CREATE POLICY "Enable read access for all users" ON public.{table_name}
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON public.{table_name}
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users only" ON public.{table_name}
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Add comment
COMMENT ON TABLE public.{table_name} IS 'Blog topic tree for {niche_id} niche - generated by niche generator';
"""
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(sql)
        
        return filepath
    
    def _seed_topics(self, niche_id: str, topic_tree: List[Dict]) -> int:
        """
        Seed topic tree into database.
        Generates a separate seed migration.
        """
        
        if not topic_tree:
            print("  Warning: No topics to seed")
            return 0
        
        # Generate seed migration
        timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
        filename = f"{timestamp}_seed_blog_topics_{niche_id}.sql"
        filepath = os.path.join(self.migrations_dir, filename)
        
        table_name = f"blog_topics_{niche_id}"
        
        # Build INSERT statements
        inserts = []
        for topic in topic_tree:
            keyword = topic.get("keyword", "").replace("'", "''")  # Escape quotes
            category = topic.get("category", "General").replace("'", "''")
            search_volume = topic.get("search_volume", 0)
            difficulty = topic.get("difficulty", 50)
            intent = topic.get("intent", "informational").replace("'", "''")
            notes = topic.get("notes", "").replace("'", "''")
            
            # Calculate priority (higher volume + lower difficulty = higher priority)
            priority = min(100, max(0, search_volume // 10 - difficulty))
            
            insert = f"""INSERT INTO public.{table_name} (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('{keyword}', '{category}', {search_volume}, {difficulty}, '{intent}', '{notes}', {priority}, 'pending')
ON CONFLICT (keyword) DO NOTHING;"""
            
            inserts.append(insert)
        
        sql = f"""-- Seed initial topic tree for {niche_id} niche
-- Generated by niche generator

{chr(10).join(inserts)}
"""
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(sql)
        
        print(f"  ✓ Created seed migration: {filepath}")
        
        return len(topic_tree)
    
    def apply_migrations(self) -> bool:
        """
        Apply migrations using Supabase CLI.
        Returns True if successful.
        """
        
        print("\n[3/3] Applying migrations with Supabase CLI...")
        
        try:
            # Run supabase db push
            result = subprocess.run(
                ["supabase", "db", "push"],
                cwd=self.project_dir,
                capture_output=True,
                text=True,
                timeout=60
            )
            
            if result.returncode == 0:
                print("  ✓ Migrations applied successfully")
                return True
            else:
                print(f"  ✗ Migration failed: {result.stderr}")
                return False
        
        except subprocess.TimeoutExpired:
            print("  ✗ Migration timed out")
            return False
        except FileNotFoundError:
            print("  ✗ Supabase CLI not found - migrations created but not applied")
            print("  Run manually: cd {self.project_dir} && supabase db push")
            return False
        except Exception as e:
            print(f"  ✗ Migration error: {e}")
            return False


def main():
    """Test the database setup."""
    import argparse
    import csv
    
    parser = argparse.ArgumentParser(description="Setup database for a niche")
    parser.add_argument("--niche-id", required=True, help="Niche ID")
    parser.add_argument("--config", required=True, help="Path to niche.config.json")
    parser.add_argument("--keywords-csv", required=True, help="Path to keywords CSV (topic tree)")
    parser.add_argument("--project-dir", default=".", help="Supabase project directory")
    parser.add_argument("--apply", action="store_true", help="Apply migrations immediately")
    
    args = parser.parse_args()
    
    # Load config
    with open(args.config, "r", encoding="utf-8") as f:
        config = json.load(f)
    
    # Load topic tree (keywords CSV)
    topic_tree = []
    with open(args.keywords_csv, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        topic_tree = list(reader)
    
    print(f"Loaded config and {len(topic_tree)} topics")
    
    # Setup database
    db_setup = DatabaseSetup(args.project_dir)
    result = db_setup.setup_database(args.niche_id, config, topic_tree)
    
    print(f"\n✓ SUCCESS: Database setup complete")
    print(f"  Migration: {result['migration_file']}")
    print(f"  Topics seeded: {result['topics_seeded']}")
    
    # Apply migrations if requested
    if args.apply:
        db_setup.apply_migrations()


if __name__ == "__main__":
    main()
