# Non-circular UK property-tax topic taxonomy (first-principles, NOT seeded from our GSC footprint).
# Each entry is a canonical topic/search intent a complete property-tax site should cover.
TAXONOMY = {
"SDLT_England": [
 "sdlt buy to let rates 2026","sdlt 5 percent additional dwelling surcharge","sdlt higher rate refund replacement main residence",
 "sdlt first time buyer relief","mdr abolished what now alternative","sdlt mixed use property claim","sdlt six or more dwellings non residential rate",
 "sdlt linked transactions rules","sdlt subsale relief","sdlt partnership transfer schedule 15","sdlt on incorporation connected company market value",
 "sdlt 17 percent higher rate corporate envelope","sdlt uninhabitable derelict dwelling non residential claim","sdlt annexe granny flat","sdlt garden grounds",
 "sdlt chattels fixtures apportionment","sdlt overpayment reclaim how","sdlt transfer between spouses","sdlt on divorce property transfer",
 "sdlt contingent consideration deferral","sdlt lease premium net present value","sdlt commercial to residential conversion","sdlt overage clawback",
 "sdlt non resident 2 percent surcharge","sdlt multiple dwellings relief replacement claim","sdlt holiday let rate"],
"LBTT_Scotland": ["lbtt rates 2026","lbtt additional dwelling supplement ads","lbtt first time buyer relief","lbtt six dwellings","lbtt non resident","lbtt ads refund"],
"LTT_Wales": ["ltt rates 2026","ltt higher rates buy to let","ltt multiple dwellings relief wales","ltt refund higher rate"],
"CGT_Property": [
 "cgt rates residential property 2026 18 24","cgt on second home","cgt on buy to let sale","private residence relief explained","ppr final period 9 months",
 "ppr lettings relief restriction","ppr garden and grounds","ppr periods of absence deemed occupation","60 day cgt return property","60 day cgt return penalties",
 "cgt annual exempt amount 3000","cgt on gifted property","cgt base cost uplift on death inherited property","gift holdover relief property","rollover relief property",
 "incorporation relief section 162 cgt","cgt transfer to spouse no gain no loss","cgt on divorce property","main residence election two homes nomination",
 "cgt part disposal property","cgt enhancement expenditure allowable","non resident cgt uk property nrcgt","cgt rebasing 2015 2019 non resident",
 "cgt on selling overseas property uk resident","cgt mixed use apportionment","cgt loss on property relief"],
"IncomeTax_Rental": [
 "rental income tax bands","section 24 mortgage interest relief 20 percent credit","section 24 worked example landlord","finance cost restriction carry forward",
 "allowable expenses landlord full list","repairs vs improvements capital revenue","replacement of domestic items relief","pre letting expenses landlord",
 "mortgage arrangement fees deductible landlord","landlord travel expenses 45p mileage","use of home as office landlord","ground rent service charge deductible",
 "void period rent arrears bad debt relief","jointly owned property income split","form 17 declaration unequal beneficial shares","beneficial interest declaration of trust income",
 "transfer rental income to lower earning spouse","property income allowance 1000","rent a room scheme 7500","cash basis vs accruals property income","property losses carry forward"],
"Incorporation_Structures": [
 "should i incorporate my property portfolio","section 162 incorporation relief conditions partnership","spv limited company buy to let setup","property spv sic codes",
 "limited company buy to let mortgage","directors loan account property company","extracting profit property company dividends","corporation tax property investment company",
 "family investment company property","fic vs discretionary trust","property partnership vs limited company tax","llp for property investment",
 "mixed member partnership rules property","gifting property to children tax efficiently","alphabet shares property company","property holding company group structure"],
"IHT_Property": [
 "inheritance tax on buy to let portfolio","iht on second home","iht residence nil rate band property","gift with reservation of benefit property",
 "iht 7 year rule property gift","iht on jointly owned property","deed of variation property inheritance","discretionary trust property iht charges",
 "life interest trust property iht","iht on furnished holiday lets business relief"],
"MTD": ["mtd for landlords april 2026","mtd itsa thresholds 50k 30k 20k","mtd quarterly updates landlord","mtd software for landlords",
 "mtd jointly owned property","mtd for non resident landlords","mtd itsa exemptions","mtd digital record keeping landlord","mtd late submission penalty points"],
"VAT_Property": ["vat on commercial property","option to tax commercial property","vat residential conversion 5 percent reduced rate","vat new build zero rate",
 "vat on serviced accommodation furnished holiday let","vat diy housebuilder scheme reclaim","transfer of going concern property togc","vat capital goods scheme property"],
"ATED": ["ated charges 2026","ated relief rental property business","ated return filing","ated related cgt","ated company owned dwelling 500000"],
"NonResident": ["non resident landlord scheme nrl1","non resident landlord tax return","nrcgt return non resident","non resident company uk property corporation tax 2020",
 "double tax treaty rental income","expat landlord uk property tax"],
"LettingTypes": ["fhl abolition april 2026 changes","fhl transitional rules 2025 26","fhl capital allowances loss after abolition","holiday let tax rules uk",
 "airbnb tax uk landlord","serviced accommodation tax structure","rent to rent tax treatment","rent to rent limited company","hmo landlord tax",
 "hmo capital allowances common parts","build to rent tax","student accommodation let tax","guaranteed rent company arrangement tax"],
"CapitalAllowances": ["capital allowances on property explained","capital allowances furnished holiday let","capital allowances hmo communal areas",
 "structures and buildings allowance sba","annual investment allowance property business","integral features capital allowances","embedded fixtures capital allowances claim"],
"Development_Trading": ["property development tax overview","badges of trade property","transactions in land anti avoidance ita part 9a","property trading company corporation tax",
 "buying renovating selling property tax flipping","joint venture property development tax","slice of the action overage tax"],
"Compliance": ["let property campaign disclosure how to","let property campaign penalties","landlord tax investigation hmrc","discovery assessment property tax",
 "self assessment landlord sa105","when to register self assessment landlord","cis construction industry scheme landlord","paying tax on rental income first time"],
"Leasehold_Freehold": ["ground rent tax treatment landlord","service charge accounting tax","lease extension cgt tax","freehold purchase by leaseholders tax","premium on grant of lease tax"],
"Service_Location": ["property accountant cost fees","buy to let accountant","specialist property tax accountant","switching to a property accountant","landlord accountant services"],
}
