-- Seed initial topic tree for medical niche
-- Generated by niche generator

INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what is gp in accounting', 'GP Tax', 400, 25, 'informational', 'Educational content opportunity', 15, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant advice', 'GP Tax', 300, 35, 'transactional', 'High intent service inquiry', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant newcastle', 'Location Services', 200, 30, 'transactional', 'Location-specific service targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('manchester gp accountant', 'Location Services', 350, 32, 'transactional', 'Major city targeting', 3, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting services', 'GP Tax', 600, 40, 'transactional', 'Core service-focused query', 20, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant leeds', 'Location Services', 180, 28, 'transactional', 'City-specific tax services', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('can an accountant become a doctor', 'Career Information', 50, 20, 'informational', 'Low relevance to core niche', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax planning', 'GP Tax', 450, 42, 'transactional', 'Strategic tax service focus', 3, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant uk', 'Medical Accounting', 800, 45, 'transactional', 'Broad UK medical accounting', 35, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant bradford', 'Location Services', 120, 28, 'transactional', 'Smaller city targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax return', 'Tax Services', 2200, 55, 'transactional', 'High volume but competitive', 100, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting meaning', 'GP Tax', 250, 22, 'informational', 'Educational content opportunity', 3, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp bookkeeping', 'Bookkeeping Services', 320, 35, 'transactional', 'Specific service offering', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('do i need a gp accountant', 'GP Tax', 400, 25, 'informational', 'Decision-stage query', 15, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in cardiff', 'Non-relevant', 30, 15, 'informational', 'Medical registration, not accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant bookkeeping', 'Bookkeeping Services', 1500, 50, 'transactional', 'Generic but high volume', 100, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('average accountant salary manchester', 'Career Information', 100, 20, 'informational', 'Not directly relevant to services', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant leeds', 'Location Services', 280, 32, 'transactional', 'City-specific targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant london', 'Location Services', 650, 48, 'transactional', 'High-value London market', 17, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp corporation tax', 'GP Tax', 300, 38, 'transactional', 'Specific tax service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant self assessment', 'Tax Services', 1800, 52, 'transactional', 'Seasonal high-volume query', 100, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant sheffield', 'Location Services', 160, 30, 'transactional', 'Regional market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('glasgow gp near me', 'Non-relevant', 40, 15, 'navigational', 'Medical practice search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('birmingham gp accountant', 'Location Services', 220, 32, 'transactional', 'Major city targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('glasgow gp jobs', 'Non-relevant', 80, 18, 'navigational', 'Medical job search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to choose a gp accountant', 'GP Tax', 150, 22, 'informational', 'Decision-making content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant london', 'Location Services', 180, 35, 'transactional', 'Comparison-focused London search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant birmingham', 'Location Services', 200, 32, 'transactional', 'Birmingham market targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('liverpool gp accountant', 'Location Services', 160, 30, 'transactional', 'Liverpool regional targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant liverpool', 'Location Services', 90, 28, 'transactional', 'Medical-specific Liverpool', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant manchester', 'Location Services', 120, 33, 'transactional', 'Comparison Manchester search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant leicester', 'Location Services', 80, 28, 'transactional', 'Smaller city opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant jobs near me', 'Career Information', 200, 25, 'navigational', 'Job search query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant bristol', 'Location Services', 100, 28, 'transactional', 'Bristol tax specialization', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant glasgow', 'Location Services', 140, 30, 'transactional', 'Scottish market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant help', 'GP Tax', 250, 32, 'transactional', 'Problem-solving intent', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('london gp accountant', 'Location Services', 580, 45, 'transactional', 'High-value London market', 13, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant bristol', 'Location Services', 120, 30, 'transactional', 'Bristol market targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax return', 'GP Tax', 400, 38, 'transactional', 'Seasonal tax service', 2, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('experienced gp accountant', 'GP Tax', 180, 32, 'transactional', 'Quality-focused search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp glasgow', 'Non-relevant', 25, 15, 'informational', 'Medical registration query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('specialist gp accountant', 'GP Tax', 220, 35, 'transactional', 'Specialization-focused', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax advice', 'GP Tax', 350, 38, 'transactional', 'Advisory service focus', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant manchester', 'Location Services', 320, 35, 'transactional', 'Manchester market targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('newcastle gp accountant', 'Location Services', 90, 28, 'transactional', 'Newcastle regional market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how much is a gp accountant', 'GP Tax', 200, 25, 'informational', 'Pricing inquiry', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('affordable gp accountant', 'GP Tax', 150, 30, 'transactional', 'Cost-conscious search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountants adviseurs', 'GP Tax', 20, 25, 'transactional', 'Dutch/international term', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant near me', 'Location Services', 450, 35, 'transactional', 'Local search intent', 10, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in bristol', 'Non-relevant', 30, 15, 'informational', 'Medical registration query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('edinburgh gp accountant', 'Location Services', 100, 28, 'transactional', 'Edinburgh Scottish market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant coventry', 'Location Services', 60, 28, 'transactional', 'Smaller city targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant access', 'GP Tax', 80, 30, 'transactional', 'Service accessibility focus', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant nottingham', 'Location Services', 90, 28, 'transactional', 'Nottingham regional market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant', 'GP Tax', 1800, 38, 'transactional', 'Core high-volume query', 100, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('cardiff gp accountant', 'Location Services', 80, 28, 'transactional', 'Welsh market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax planning', 'Tax Services', 800, 48, 'transactional', 'Generic but high volume', 32, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('coventry gp accountant', 'Location Services', 50, 28, 'transactional', 'Smaller city targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant edinburgh', 'Location Services', 110, 28, 'transactional', 'Edinburgh market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what is the best gp accountant', 'GP Tax', 120, 25, 'informational', 'Comparison research', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('when to hire a gp accountant', 'GP Tax', 100, 22, 'informational', 'Decision-timing content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant cardiff', 'Location Services', 70, 28, 'transactional', 'Cardiff Welsh market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp self assessment', 'GP Tax', 600, 40, 'transactional', 'Key tax service', 20, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant payroll services', 'Payroll Services', 1200, 50, 'transactional', 'Generic payroll service', 70, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant financial planning', 'Financial Planning', 900, 48, 'transactional', 'Broader financial service', 42, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp financial planning', 'Financial Planning', 280, 38, 'transactional', 'GP-specific planning', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant manchester', 'Location Services', 120, 30, 'transactional', 'Medical-specific Manchester', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('bristol gp accountant', 'Location Services', 100, 28, 'transactional', 'Bristol market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant birmingham', 'Location Services', 80, 32, 'transactional', 'Birmingham comparison search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant manchester', 'Location Services', 90, 28, 'transactional', 'Manchester tax specialization', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('nottingham gp accountant', 'Location Services', 70, 28, 'transactional', 'Nottingham regional', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how much does a gp accountant cost', 'GP Tax', 180, 22, 'informational', 'Detailed pricing inquiry', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant cost', 'GP Tax', 220, 32, 'informational', 'Cost consideration', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp boyle accountants newry', 'Location Services', 15, 20, 'navigational', 'Specific firm search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp payroll services', 'Payroll Services', 200, 38, 'transactional', 'GP-specific payroll', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('local gp accountant', 'Location Services', 300, 32, 'transactional', 'Local service preference', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what does a gp accountant do', 'GP Tax', 250, 22, 'informational', 'Service explanation content', 3, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in liverpool', 'Non-relevant', 20, 15, 'informational', 'Medical registration', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant nottingham', 'Location Services', 40, 28, 'transactional', 'Medical-specific Nottingham', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('sheffield gp accountant', 'Location Services', 80, 28, 'transactional', 'Sheffield regional market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant cardiff', 'Location Services', 35, 28, 'transactional', 'Medical-specific Cardiff', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in sheffield', 'Non-relevant', 15, 15, 'informational', 'Medical registration', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant accounting services', 'General Accounting', 1500, 55, 'transactional', 'Generic high-volume', 95, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting system', 'GP Tax', 150, 35, 'transactional', 'System/software focus', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant birmingham', 'Location Services', 60, 28, 'transactional', 'Birmingham tax specialization', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant corporation tax', 'Tax Services', 800, 48, 'transactional', 'Generic corp tax service', 32, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant fees', 'GP Tax', 180, 32, 'informational', 'Fee structure inquiry', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant london', 'Location Services', 120, 35, 'transactional', 'London tax specialization', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountants schagen', 'Location Services', 10, 20, 'navigational', 'Dutch location reference', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant liverpool', 'Location Services', 140, 28, 'transactional', 'Liverpool market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant glasgow', 'Location Services', 50, 28, 'transactional', 'Medical-specific Glasgow', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant leeds', 'Location Services', 70, 28, 'transactional', 'Medical-specific Leeds', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant near me', 'Location Services', 400, 35, 'transactional', 'Local medical accounting', 5, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant newcastle', 'Location Services', 80, 28, 'transactional', 'Newcastle regional', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('bradford gp accountant', 'Location Services', 60, 28, 'transactional', 'Bradford market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant sheffield', 'Location Services', 30, 28, 'transactional', 'Medical-specific Sheffield', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp audit examples', 'GP Tax', 80, 30, 'informational', 'Audit-related content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant', 'GP Tax', 320, 35, 'transactional', 'Quality-focused search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what qualifications do i need to become an accountant in the uk', 'Career Information', 150, 18, 'informational', 'Career guidance content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in manchester', 'Non-relevant', 25, 15, 'informational', 'Medical registration', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('glasgow gp accountant', 'Location Services', 100, 28, 'transactional', 'Glasgow market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('leicester gp accountant', 'Location Services', 50, 28, 'transactional', 'Leicester regional', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to find a gp accountant', 'GP Tax', 180, 22, 'informational', 'Selection guidance content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting & tax services', 'GP Tax', 150, 35, 'transactional', 'Combined service offering', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant uk', 'GP Tax', 450, 40, 'transactional', 'UK-wide service', 5, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax advice', 'Tax Services', 1100, 48, 'transactional', 'Generic tax advice', 62, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('leeds gp accountant', 'Location Services', 140, 28, 'transactional', 'Leeds market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('find the gp near me', 'Non-relevant', 100, 20, 'navigational', 'Medical practice search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant jobs', 'Career Information', 200, 32, 'navigational', 'Job search query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant bristol', 'Location Services', 45, 28, 'transactional', 'Medical-specific Bristol', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp vat registration', 'GP Tax', 120, 35, 'transactional', 'VAT service for GPs', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant vat registration', 'Tax Services', 600, 45, 'transactional', 'Generic VAT service', 15, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting software', 'GP Tax', 180, 38, 'transactional', 'Software solution focus', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting', 'GP Tax', 800, 42, 'transactional', 'Core service category', 38, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('why use a gp accountant', 'GP Tax', 120, 22, 'informational', 'Benefits explanation', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant london', 'Location Services', 200, 35, 'transactional', 'Medical-specific London', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant services', 'GP Tax', 400, 38, 'transactional', 'Service-focused query', 2, 'pending')
ON CONFLICT (keyword) DO NOTHING;
