-- Migration: 20260715000001_add_tranche_3_to_sites.sql
-- Tranche: 3 | new site keys: ecommerce
-- Generated by optimisation_engine.ops.spinup_site.
--
-- ROLLBACK / previous constraint definition (repo-known as of generation;
-- RE-READ THE LIVE DEF before applying, constraint names/contents have
-- drifted from repo files before):
--   SELECT conname, pg_get_constraintdef(oid)
--   FROM pg_constraint WHERE conname LIKE '%site_key%';
--   sites_site_key_check: CHECK ((site_key = ANY (ARRAY['property', 'dentists', 'medical', 'solicitors', 'agency', 'generalist', 'contractors-ir35', 'construction-cis', 'charities'])))
--
-- Rows insert active=false (site stays out of the console until domain-ready).
-- Strictly additive. Run manually via Supabase SQL (Management API).

BEGIN;

ALTER TABLE sites DROP CONSTRAINT IF EXISTS sites_site_key_check;

ALTER TABLE sites ADD CONSTRAINT sites_site_key_check
  CHECK (
    site_key = ANY (ARRAY[
      'property'::text,
      'dentists'::text,
      'medical'::text,
      'solicitors'::text,
      'agency'::text,
      'generalist'::text,
      'contractors-ir35'::text,
      'construction-cis'::text,
      'charities'::text,
      -- HAND-EDITED 2026-07-15: generator omitted the tranche-1/2 sites; the
      -- union below preserves them (banked lesson: spinup migrations drop
      -- sibling tranches). RE-READ THE LIVE DEF before applying regardless.
      'hospitality'::text,
      'crypto'::text,
      'pharmacies'::text,
      'startups-tech'::text,
      'care'::text,
      'ecommerce'::text
    ])
  );

INSERT INTO sites (
  site_key, display_name, domain, gsc_property_url, bing_property_url,
  niche, target_buyer_persona, brand_voice_notes,
  content_dir, git_repo_path, blog_topics_table, active
) VALUES (
  'ecommerce',
  'Ecommerce Tax Partners',
  'www.ecommercetaxpartners.co.uk',
  'sc-domain:ecommercetaxpartners.co.uk',
  NULL,
  'UK ecommerce and marketplace sellers (Amazon, eBay, Etsy, Shopify): tax, VAT, platform reporting and seller accounts',
  'UK ecommerce and marketplace sellers (Amazon, eBay, Etsy, Shopify): tax, VAT, platform reporting and seller accounts',
  'plain-English specialist authority; UK English; no em-dashes',
  'ecommerce/web/content/blog',
  'ecommerce/web',
  'blog_topics',
  false
)
ON CONFLICT (site_key) DO NOTHING;

COMMIT;

-- Verify after applying:
--   SELECT conname, pg_get_constraintdef(oid)
--   FROM pg_constraint WHERE conname = 'sites_site_key_check';
