-- Seed initial topic tree for medical niche
-- Generated by niche generator

INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant', 'GP Accounting Services', 1800, 42, 'transactional', 'Core high-volume query', 100, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant uk', 'Medical Accounting Services', 1200, 38, 'transactional', 'Strong UK-focused keyword', 82, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant near me', 'Local GP Services', 950, 32, 'transactional', 'Local search with buying intent', 63, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax return', 'GP Tax', 850, 35, 'transactional', 'Specific service need', 50, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp self assessment', 'GP Tax', 750, 36, 'transactional', 'High-value tax service', 39, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant london', 'Local GP Services', 650, 34, 'transactional', 'Location-specific opportunity', 31, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant near me', 'Local Medical Services', 580, 30, 'transactional', 'Local medical accounting search', 28, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting', 'GP Accounting Services', 520, 40, 'informational', 'General service category', 12, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant cost', 'GP Accounting Services', 480, 28, 'transactional', 'Price comparison intent', 20, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant services', 'GP Accounting Services', 420, 33, 'transactional', 'Service discovery query', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax planning', 'GP Tax', 380, 37, 'transactional', 'Strategic tax service', 1, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting services', 'GP Accounting Services', 350, 35, 'transactional', 'Comprehensive service search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant', 'GP Accounting Services', 320, 29, 'transactional', 'Quality-focused search', 3, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant uk', 'GP Accounting Services', 280, 36, 'transactional', 'UK-specific GP accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('specialist gp accountant', 'GP Accounting Services', 260, 27, 'transactional', 'Specialization emphasis', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp vat registration', 'GP Tax', 240, 34, 'transactional', 'VAT compliance service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant london', 'Local Medical Services', 220, 33, 'transactional', 'London medical accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp corporation tax', 'GP Tax', 200, 38, 'transactional', 'Corporate structure tax', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('affordable gp accountant', 'GP Accounting Services', 180, 25, 'transactional', 'Budget-conscious search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('local gp accountant', 'Local GP Services', 160, 26, 'transactional', 'Local service preference', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant help', 'GP Accounting Services', 150, 24, 'transactional', 'Help-seeking query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax advice', 'GP Tax', 140, 32, 'transactional', 'Advisory service need', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('experienced gp accountant', 'GP Accounting Services', 130, 23, 'transactional', 'Experience-focused search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant fees', 'GP Accounting Services', 120, 25, 'transactional', 'Fee structure inquiry', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp financial planning', 'GP Financial Planning', 110, 36, 'transactional', 'Wealth management service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant advice', 'GP Accounting Services', 95, 22, 'transactional', 'Advisory consultation', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting software', 'GP Practice Management', 90, 39, 'informational', 'Software solution search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp bookkeeping', 'GP Bookkeeping', 85, 31, 'transactional', 'Basic accounting service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp payroll services', 'GP Practice Management', 80, 35, 'transactional', 'Staff payroll management', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting system', 'GP Practice Management', 75, 37, 'informational', 'System implementation', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting meaning', 'GP Accounting Services', 70, 18, 'informational', 'Educational query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what is gp in accounting', 'GP Accounting Services', 65, 16, 'informational', 'Definition search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting & tax services', 'GP Accounting Services', 60, 20, 'transactional', 'Combined service offering', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp audit examples', 'GP Practice Management', 55, 22, 'informational', 'Audit guidance search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant jobs', 'GP Accounting Services', 50, 34, 'navigational', 'Employment search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant access', 'GP Accounting Services', 45, 21, 'transactional', 'Service accessibility', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant jobs near me', 'Local Medical Services', 40, 19, 'navigational', 'Employment opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant payroll services', 'General Accounting', 35, 55, 'transactional', 'Broad payroll service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant vat registration', 'General Accounting', 30, 52, 'transactional', 'General VAT service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant self assessment', 'General Accounting', 25, 58, 'transactional', 'Broad tax service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax advice', 'General Accounting', 20, 56, 'transactional', 'General tax advisory', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant bookkeeping', 'General Accounting', 18, 54, 'transactional', 'General bookkeeping', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant accounting services', 'General Accounting', 15, 59, 'transactional', 'Broad accounting services', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant corporation tax', 'General Accounting', 12, 57, 'transactional', 'General corporation tax', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax return', 'General Accounting', 10, 53, 'transactional', 'General tax returns', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax planning', 'General Accounting', 8, 55, 'transactional', 'General tax planning', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant financial planning', 'General Accounting', 6, 58, 'transactional', 'General financial planning', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('find the gp near me', 'Local GP Services', 5, 15, 'navigational', 'Medical practice search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp boyle accountants newry', 'Local GP Services', 3, 12, 'navigational', 'Specific firm search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountants adviseurs', 'GP Accounting Services', 2, 10, 'navigational', 'Foreign language variant', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountants schagen', 'Local GP Services', 1, 8, 'navigational', 'Specific location firm', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what qualifications do i need to become an accountant in the uk', 'General Accounting', 95, 24, 'informational', 'Career guidance query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
