-- Seed initial topic tree for medical niche
-- Generated by niche generator

INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('average accountant salary manchester', 'Career Information', 200, 25, 'informational', 'Informational query about accounting salaries', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp financial planning', 'GP Financial Services', 400, 42, 'transactional', 'High-value financial planning services', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp payroll services', 'GP Payroll', 300, 40, 'transactional', 'Specific service offering', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('specialist gp accountant', 'GP Tax', 250, 35, 'transactional', 'Emphasizes specialization', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('can an accountant become a doctor', 'Career Information', 150, 22, 'informational', 'Career transition query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant manchester', 'Location-Based Services', 180, 30, 'transactional', 'Local search with quality modifier', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('leicester gp accountant', 'Location-Based Services', 90, 28, 'transactional', 'Local Leicester market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('why use a gp accountant', 'GP Tax', 120, 25, 'informational', 'Educational content opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant jobs near me', 'Career Information', 200, 32, 'navigational', 'Job seeking intent', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant near me', 'Location-Based Services', 800, 35, 'transactional', 'High local search volume', 45, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('liverpool gp accountant', 'Location-Based Services', 120, 28, 'transactional', 'Liverpool market targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('affordable gp accountant', 'GP Tax', 200, 35, 'transactional', 'Price-conscious searchers', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in cardiff', 'NHS Services', 80, 20, 'informational', 'NHS registration query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to find a gp accountant', 'GP Tax', 150, 25, 'informational', 'How-to guide opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant manchester', 'Location-Based Services', 400, 32, 'transactional', 'Major city targeting', 8, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to choose a gp accountant', 'GP Tax', 110, 25, 'informational', 'Decision-making content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant birmingham', 'Location-Based Services', 140, 30, 'transactional', 'Birmingham market with quality focus', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant manchester', 'Location-Based Services', 160, 32, 'transactional', 'Tax specialization in Manchester', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what is gp in accounting', 'GP Tax', 300, 28, 'informational', 'Educational definition query', 2, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax return', 'GP Tax', 600, 38, 'transactional', 'Core tax service', 22, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant uk', 'GP Tax', 500, 35, 'transactional', 'National level targeting', 15, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('glasgow gp accountant', 'Location-Based Services', 130, 28, 'transactional', 'Scottish market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp self assessment', 'GP Tax', 450, 40, 'transactional', 'Core self-assessment service', 5, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant', 'GP Tax', 1800, 38, 'transactional', 'Core high-volume query', 100, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in liverpool', 'NHS Services', 70, 18, 'informational', 'NHS registration guidance', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('when to hire a gp accountant', 'GP Tax', 90, 25, 'informational', 'Timing guidance content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant access', 'GP Software', 80, 30, 'navigational', 'Software access query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant accounting services', 'General Accounting', 400, 55, 'transactional', 'Broad competitive term', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting software', 'GP Software', 200, 35, 'transactional', 'Software solution seeking', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('leeds gp accountant', 'Location-Based Services', 110, 28, 'transactional', 'Leeds market targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant cardiff', 'Location-Based Services', 90, 28, 'transactional', 'Welsh market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant newcastle', 'Location-Based Services', 70, 28, 'transactional', 'Newcastle medical market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant nottingham', 'Location-Based Services', 60, 28, 'transactional', 'Nottingham medical market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting meaning', 'GP Tax', 150, 25, 'informational', 'Definition and explanation content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how much is a gp accountant', 'GP Tax', 180, 30, 'informational', 'Pricing information query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant near me', 'Location-Based Services', 600, 35, 'transactional', 'Broad medical accounting search', 25, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant bookkeeping', 'General Accounting', 800, 50, 'transactional', 'General bookkeeping services', 30, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant liverpool', 'Location-Based Services', 80, 28, 'transactional', 'Liverpool medical accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in bristol', 'NHS Services', 65, 18, 'informational', 'Bristol NHS registration', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('bradford gp accountant', 'Location-Based Services', 50, 28, 'transactional', 'Bradford local market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant cost', 'GP Tax', 250, 32, 'informational', 'Cost comparison content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what is the best gp accountant', 'GP Tax', 90, 25, 'informational', 'Comparison and recommendation content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant glasgow', 'Location-Based Services', 120, 28, 'transactional', 'Glasgow market targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('manchester gp accountant', 'Location-Based Services', 350, 32, 'transactional', 'Manchester market focus', 3, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant fees', 'GP Tax', 200, 32, 'informational', 'Fee structure information', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant financial planning', 'General Accounting', 500, 50, 'transactional', 'Broad financial planning', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant london', 'Location-Based Services', 300, 35, 'transactional', 'London medical market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp corporation tax', 'GP Tax', 150, 38, 'transactional', 'Corporate tax for GPs', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('birmingham gp accountant', 'Location-Based Services', 140, 30, 'transactional', 'Birmingham market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant self assessment', 'General Accounting', 1200, 52, 'transactional', 'General self assessment', 68, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('nottingham gp accountant', 'Location-Based Services', 70, 28, 'transactional', 'Nottingham local market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting', 'GP Tax', 800, 40, 'transactional', 'Broad GP accounting services', 40, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what does a gp accountant do', 'GP Tax', 180, 25, 'informational', 'Service explanation content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant london', 'Location-Based Services', 200, 35, 'transactional', 'London tax specialization', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant jobs', 'Career Information', 150, 35, 'navigational', 'Employment opportunities', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountants schagen', 'Location-Based Services', 20, 25, 'navigational', 'Specific firm reference', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax planning', 'General Accounting', 400, 48, 'transactional', 'General tax planning', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting services', 'GP Tax', 300, 38, 'transactional', 'Comprehensive GP services', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant payroll services', 'General Accounting', 600, 48, 'transactional', 'General payroll services', 12, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax advice', 'General Accounting', 700, 50, 'transactional', 'General tax advisory', 20, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('coventry gp accountant', 'Location-Based Services', 60, 28, 'transactional', 'Coventry market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant manchester', 'Location-Based Services', 120, 32, 'transactional', 'Manchester medical accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp audit examples', 'GP Compliance', 80, 30, 'informational', 'Audit guidance content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('find the gp near me', 'NHS Services', 200, 25, 'navigational', 'GP practice finder', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting system', 'GP Software', 100, 35, 'transactional', 'Accounting system needs', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant birmingham', 'Location-Based Services', 90, 32, 'transactional', 'Birmingham tax specialization', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax advice', 'GP Tax', 250, 35, 'transactional', 'Tax advisory services', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in manchester', 'NHS Services', 60, 18, 'informational', 'Manchester NHS registration', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what qualifications do i need to become an accountant in the uk', 'Career Information', 100, 15, 'informational', 'Career qualification information', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in sheffield', 'NHS Services', 50, 18, 'informational', 'Sheffield NHS registration', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant bristol', 'Location-Based Services', 80, 28, 'transactional', 'Bristol market targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting & tax services', 'GP Tax', 120, 30, 'transactional', 'Combined services offering', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp boyle accountants newry', 'Location-Based Services', 30, 20, 'navigational', 'Specific firm in Northern Ireland', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant glasgow', 'Location-Based Services', 70, 28, 'transactional', 'Glasgow medical accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant services', 'GP Tax', 200, 35, 'transactional', 'Service overview content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant help', 'GP Tax', 150, 32, 'transactional', 'Help and support seeking', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant birmingham', 'Location-Based Services', 140, 30, 'transactional', 'Birmingham GP accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant bristol', 'Location-Based Services', 60, 28, 'transactional', 'Bristol tax specialization', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant leicester', 'Location-Based Services', 70, 28, 'transactional', 'Leicester market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('glasgow gp jobs', 'Career Information', 120, 35, 'navigational', 'GP employment in Glasgow', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant edinburgh', 'Location-Based Services', 100, 28, 'transactional', 'Edinburgh Scottish market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant leeds', 'Location-Based Services', 70, 28, 'transactional', 'Leeds tax specialization', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant vat registration', 'General Accounting', 300, 42, 'transactional', 'VAT registration services', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant advice', 'GP Tax', 120, 32, 'informational', 'Advisory content opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant sheffield', 'Location-Based Services', 60, 28, 'transactional', 'Sheffield market targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant leeds', 'Location-Based Services', 60, 28, 'transactional', 'Leeds medical accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant london', 'Location-Based Services', 500, 35, 'transactional', 'High-value London market', 15, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('london gp accountant', 'Location-Based Services', 450, 35, 'transactional', 'London market variation', 10, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant newcastle', 'Location-Based Services', 50, 28, 'transactional', 'Newcastle market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant london', 'Location-Based Services', 200, 32, 'transactional', 'Quality-focused London search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant coventry', 'Location-Based Services', 50, 28, 'transactional', 'Coventry market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax planning', 'GP Tax', 200, 38, 'transactional', 'Strategic tax planning', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('sheffield gp accountant', 'Location-Based Services', 60, 28, 'transactional', 'Sheffield market variation', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant cardiff', 'Location-Based Services', 50, 28, 'transactional', 'Cardiff Welsh market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp glasgow', 'NHS Services', 40, 18, 'informational', 'Glasgow NHS registration', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('glasgow gp near me', 'NHS Services', 80, 25, 'navigational', 'Local GP practice search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('cardiff gp accountant', 'Location-Based Services', 60, 28, 'transactional', 'Cardiff accounting services', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountants adviseurs', 'Location-Based Services', 20, 25, 'navigational', 'Possible Dutch/international firm', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('local gp accountant', 'Location-Based Services', 300, 32, 'transactional', 'Local service preference', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant', 'GP Tax', 250, 35, 'transactional', 'Quality-focused search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant uk', 'GP Tax', 400, 38, 'transactional', 'National medical accounting', 2, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('do i need a gp accountant', 'GP Tax', 120, 25, 'informational', 'Decision-making content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant sheffield', 'Location-Based Services', 40, 28, 'transactional', 'Sheffield medical market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('edinburgh gp accountant', 'Location-Based Services', 80, 28, 'transactional', 'Edinburgh market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp vat registration', 'GP Compliance', 100, 35, 'transactional', 'VAT registration for GPs', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant nottingham', 'Location-Based Services', 60, 28, 'transactional', 'Nottingham market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax return', 'General Accounting', 1000, 52, 'transactional', 'General tax return services', 48, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('experienced gp accountant', 'GP Tax', 80, 32, 'transactional', 'Experience-focused search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant bristol', 'Location-Based Services', 50, 28, 'transactional', 'Bristol medical accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('newcastle gp accountant', 'Location-Based Services', 50, 28, 'transactional', 'Newcastle market', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant bradford', 'Location-Based Services', 40, 28, 'transactional', 'Bradford market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant corporation tax', 'General Accounting', 500, 50, 'transactional', 'General corporation tax', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('bristol gp accountant', 'Location-Based Services', 70, 28, 'transactional', 'Bristol market variation', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how much does a gp accountant cost', 'GP Tax', 150, 28, 'informational', 'Detailed cost information', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp bookkeeping', 'GP Financial Services', 200, 38, 'transactional', 'Bookkeeping services for GPs', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant liverpool', 'Location-Based Services', 100, 28, 'transactional', 'Liverpool market variation', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant leeds', 'Location-Based Services', 90, 28, 'transactional', 'Leeds market variation', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
