-- Migration: 20260712000001_add_tranche_1_to_sites.sql
-- Tranche: 1 | new site keys: hospitality, care, startups-tech
-- Generated by optimisation_engine.ops.spinup_site.
--
-- ROLLBACK / previous constraint definition (repo-known as of generation;
-- RE-READ THE LIVE DEF before applying, constraint names/contents have
-- drifted from repo files before):
--   SELECT conname, pg_get_constraintdef(oid)
--   FROM pg_constraint WHERE conname LIKE '%site_key%';
--   sites_site_key_check: CHECK ((site_key = ANY (ARRAY['property', 'dentists', 'medical', 'solicitors', 'agency', 'generalist', 'contractors-ir35', 'construction-cis'])))
--
-- Rows insert active=false (site stays out of the console until domain-ready).
-- Strictly additive. Run manually via Supabase SQL (Management API).

BEGIN;

ALTER TABLE sites DROP CONSTRAINT IF EXISTS sites_site_key_check;

ALTER TABLE sites ADD CONSTRAINT sites_site_key_check
  CHECK (
    site_key = ANY (ARRAY[
      'property'::text,
      'dentists'::text,
      'medical'::text,
      'solicitors'::text,
      'agency'::text,
      'generalist'::text,
      'contractors-ir35'::text,
      'construction-cis'::text,
      'charities'::text,
      'hospitality'::text,
      'care'::text,
      'startups-tech'::text
    ])
  );

INSERT INTO sites (
  site_key, display_name, domain, gsc_property_url, bing_property_url,
  niche, target_buyer_persona, brand_voice_notes,
  content_dir, git_repo_path, blog_topics_table, active
) VALUES (
  'hospitality',
  'BRAND_TBD Hospitality Accountancy',
  'www.brand-tbd-hospitality.invalid',
  'sc-domain:brand-tbd-hospitality.invalid',
  NULL,
  'UK hospitality businesses (pubs, restaurants, hotels, cafes, takeaways): accounts, tronc and tips compliance, VAT and payroll',
  'UK hospitality businesses (pubs, restaurants, hotels, cafes, takeaways): accounts, tronc and tips compliance, VAT and payroll',
  'plain-English specialist authority; UK English; no em-dashes',
  'hospitality/web/content/blog',
  'hospitality/web',
  'blog_topics',
  false
)
ON CONFLICT (site_key) DO NOTHING;

INSERT INTO sites (
  site_key, display_name, domain, gsc_property_url, bing_property_url,
  niche, target_buyer_persona, brand_voice_notes,
  content_dir, git_repo_path, blog_topics_table, active
) VALUES (
  'care',
  'TODO_care',
  'TODO.care.co.uk',
  'sc-domain:TODO.care.co.uk',
  NULL,
  'TODO',
  'TODO',
  'plain-English specialist authority; UK English; no em-dashes',
  'care/web/content/blog',
  'care/web',
  'blog_topics',
  false
)
ON CONFLICT (site_key) DO NOTHING;

INSERT INTO sites (
  site_key, display_name, domain, gsc_property_url, bing_property_url,
  niche, target_buyer_persona, brand_voice_notes,
  content_dir, git_repo_path, blog_topics_table, active
) VALUES (
  'startups-tech',
  'TODO_startups-tech',
  'TODO.startups-tech.co.uk',
  'sc-domain:TODO.startups-tech.co.uk',
  NULL,
  'TODO',
  'TODO',
  'plain-English specialist authority; UK English; no em-dashes',
  'startups-tech/web/content/blog',
  'startups-tech/web',
  'blog_topics',
  false
)
ON CONFLICT (site_key) DO NOTHING;

COMMIT;

-- Verify after applying:
--   SELECT conname, pg_get_constraintdef(oid)
--   FROM pg_constraint WHERE conname = 'sites_site_key_check';
