-- Migration: 20260714000002_add_tranche_2_to_leads_source.sql
-- Tranche: 2 | new source keys: crypto, pharmacies
-- Generated by optimisation_engine.ops.spinup_site.
--
-- ROLLBACK / previous constraint definition (repo-known as of generation;
-- RE-READ THE LIVE DEF before applying):
--   SELECT conname, pg_get_constraintdef(oid)
--   FROM pg_constraint WHERE conname LIKE '%source%' AND conrelid = 'leads'::regclass;
--   leads_source_valid: CHECK ((source = ANY (ARRAY['dentists', 'property', 'medical', 'solicitors', 'generalist', 'general', 'agency', 'agency-founder-finance', 'contractors-ir35', 'construction-cis', 'test', 'charities'])) OR source IS NULL)
--
-- Strictly additive. Run manually via Supabase SQL (Management API).

BEGIN;

ALTER TABLE leads DROP CONSTRAINT IF EXISTS leads_source_valid;

ALTER TABLE leads ADD CONSTRAINT leads_source_valid
  CHECK (
    source IN (
      'dentists',
      'property',
      'medical',
      'solicitors',
      'generalist',
      'general',
      'agency',
      'agency-founder-finance',
      'contractors-ir35',
      'construction-cis',
      'test',
      'charities',
      -- HAND-EDITED 2026-07-15: generator omitted the sibling tranche-1 keys
      -- (hospitality, startups-tech, care are LIVE in the constraint); the
      -- union below preserves them. RE-READ THE LIVE DEF before applying.
      'hospitality',
      'startups-tech',
      'care',
      'crypto',
      'pharmacies'
    )
    OR source IS NULL
  );

COMMIT;

-- Verify after applying:
--   SELECT conname, pg_get_constraintdef(oid)
--   FROM pg_constraint WHERE conname = 'leads_source_valid';
