-- Seed initial topic tree for medical niche
-- Generated by niche generator

INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax advice', 'GP Tax', 560, 40, 'transactional', 'Core tax service for GPs', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting software', 'Medical Expenses', 560, 40, 'transactional', 'Software solution for practice management', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant corporation tax', 'GP Tax', 560, 50, 'transactional', 'General corporate tax service', 6, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp payroll services', 'Medical Expenses', 560, 40, 'transactional', 'Payroll for practice staff', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant bristol', 'Location-Based', 392, 30, 'transactional', 'Local Bristol tax specialist', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax planning', 'GP Tax', 560, 50, 'transactional', 'Advanced tax strategy service', 6, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('nottingham gp accountant', 'Location-Based', 392, 30, 'transactional', 'Local Nottingham market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant birmingham', 'Location-Based', 392, 30, 'transactional', 'Local Birmingham tax specialist', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant cost', 'Pricing', 560, 40, 'transactional', 'Direct pricing query', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to choose a gp accountant', 'Informational', 120, 30, 'informational', 'Educational research query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant nottingham', 'Location-Based', 392, 30, 'transactional', 'Local Nottingham medical specialist', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant cardiff', 'Location-Based', 392, 30, 'transactional', 'Local Cardiff medical specialist', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant edinburgh', 'Location-Based', 392, 30, 'transactional', 'Local Edinburgh market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax advice', 'GP Tax', 560, 50, 'transactional', 'General tax advisory service', 6, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant bristol', 'Location-Based', 392, 30, 'transactional', 'Local Bristol market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant sheffield', 'Location-Based', 392, 30, 'transactional', 'Local Sheffield market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('newcastle gp accountant', 'Location-Based', 392, 30, 'transactional', 'Local Newcastle market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what does a gp accountant do', 'Informational', 120, 30, 'informational', 'Explains service scope', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in cardiff', 'Informational', 72, 25, 'informational', 'Patient registration query, low relevance', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp corporation tax', 'GP Tax', 560, 40, 'transactional', 'Specific corporate tax for GPs', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('average accountant salary manchester', 'Informational', 120, 30, 'informational', 'Job market query, low relevance', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting', 'Medical Expenses', 1400, 60, 'transactional', 'Broad accounting service term', 80, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant manchester', 'Location-Based', 392, 25, 'transactional', 'Manchester local recommendation query', 14, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountants adviseurs', 'Informational', 50, 20, 'navigational', 'Likely brand name, low volume', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant manchester', 'Location-Based', 392, 30, 'transactional', 'Manchester local market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant manchester', 'Location-Based', 392, 30, 'transactional', 'Local Manchester medical specialist', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('affordable gp accountant', 'Pricing', 560, 35, 'transactional', 'Budget-conscious client query', 21, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant', 'Core Service', 1400, 60, 'transactional', 'Primary target keyword', 80, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant leeds', 'Location-Based', 392, 30, 'transactional', 'Local Leeds market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('bristol gp accountant', 'Location-Based', 392, 30, 'transactional', 'Local Bristol market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant leeds', 'Location-Based', 392, 30, 'transactional', 'Local Leeds tax specialist', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp financial planning', 'Medical Expenses', 560, 40, 'transactional', 'Broader financial advisory service', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how much is a gp accountant', 'Pricing', 120, 30, 'informational', 'Cost research query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountants schagen', 'Informational', 50, 20, 'navigational', 'Likely brand name, low volume', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('why use a gp accountant', 'Informational', 120, 30, 'informational', 'Persuasive educational query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant services', 'Core Service', 560, 40, 'transactional', 'Service listing query', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('leeds gp accountant', 'Location-Based', 392, 30, 'transactional', 'Local Leeds market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('coventry gp accountant', 'Location-Based', 392, 30, 'transactional', 'Local Coventry market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in manchester', 'Informational', 72, 25, 'informational', 'Patient registration query, low relevance', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant leeds', 'Location-Based', 392, 30, 'transactional', 'Local Leeds medical specialist', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant access', 'Core Service', 560, 40, 'transactional', 'Service availability query', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('specialist gp accountant', 'Core Service', 560, 40, 'transactional', 'High-intent specialist query', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant bookkeeping', 'Medical Expenses', 560, 50, 'transactional', 'General bookkeeping service', 6, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('local gp accountant', 'Location-Based', 560, 40, 'transactional', 'Geographic service query', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant nottingham', 'Location-Based', 392, 30, 'transactional', 'Local Nottingham market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('sheffield gp accountant', 'Location-Based', 392, 30, 'transactional', 'Local Sheffield market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how much does a gp accountant cost', 'Pricing', 120, 30, 'informational', 'Detailed cost research query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting system', 'Medical Expenses', 560, 40, 'transactional', 'Software or process query', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax return', 'GP Tax', 560, 40, 'transactional', 'Core tax filing service', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant coventry', 'Location-Based', 392, 30, 'transactional', 'Local Coventry market opportunity', 9, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant', 'General', 1500, 40, 'transactional', 'Primary target keyword', 100, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant birmingham', 'Location-Based', 140, 25, 'transactional', 'Birmingham local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what qualifications do i need to become an accountant in the uk', 'General Accounting', 120, 30, 'informational', 'Career advice query, low commercial intent', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant help', 'GP Tax', 280, 40, 'transactional', 'Direct service-seeking intent', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('manchester gp accountant', 'Location-Based', 140, 25, 'transactional', 'Manchester local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant self assessment', 'General Accounting', 560, 50, 'transactional', 'High volume, generic tax service need', 6, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in sheffield', 'General Medical', 120, 30, 'informational', 'Medical admin query, off-topic', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant glasgow', 'Location-Based', 140, 25, 'transactional', 'Glasgow medical accounting niche', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant jobs', 'General Accounting', 200, 40, 'informational', 'Job search, not client acquisition', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant accounting services', 'General Accounting', 560, 50, 'transactional', 'Very generic, high competition', 6, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('birmingham gp accountant', 'Location-Based', 140, 25, 'transactional', 'Birmingham local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in liverpool', 'General Medical', 120, 30, 'informational', 'Medical admin query, off-topic', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what is gp in accounting', 'GP Tax', 120, 30, 'informational', 'Definitional query for GP accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant jobs near me', 'General Accounting', 120, 30, 'informational', 'Job search, not client acquisition', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant glasgow', 'Location-Based', 140, 25, 'transactional', 'Glasgow local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant uk', 'GP Tax', 280, 40, 'transactional', 'National GP accounting service search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax planning', 'GP Tax', 200, 40, 'transactional', 'Specific, high-value service intent', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('experienced gp accountant', 'GP Tax', 200, 35, 'transactional', 'Qualifier indicates serious buyer', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant london', 'Location-Based', 140, 30, 'transactional', 'London market with ''best'' qualifier', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('when to hire a gp accountant', 'GP Tax', 120, 30, 'informational', 'Early-stage research for hiring', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting services', 'GP Tax', 280, 40, 'transactional', 'Direct service-seeking intent', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp self assessment', 'GP Tax', 280, 40, 'transactional', 'Specific tax service for GPs', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant newcastle', 'Location-Based', 140, 25, 'transactional', 'Newcastle local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp boyle accountants newry', 'Location-Based', 50, 20, 'navigational', 'Branded, specific firm search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant london', 'Location-Based', 140, 25, 'transactional', 'London medical accounting niche', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in bristol', 'General Medical', 120, 30, 'informational', 'Medical admin query, off-topic', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('glasgow gp near me', 'General Medical', 120, 30, 'informational', 'Medical practice search, off-topic', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('bradford gp accountant', 'Location-Based', 140, 25, 'transactional', 'Bradford local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to find a gp accountant', 'GP Tax', 120, 30, 'informational', 'Research query for finding services', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant london', 'Location-Based', 140, 30, 'transactional', 'London-specific GP tax specialist', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant fees', 'GP Tax', 200, 40, 'transactional', 'Price-sensitive service research', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('do i need a gp accountant', 'GP Tax', 120, 30, 'informational', 'Early-stage need assessment', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('glasgow gp jobs', 'General Medical', 120, 30, 'informational', 'Medical job search, off-topic', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant near me', 'Medical Expenses', 200, 40, 'transactional', 'Local medical accountant search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting meaning', 'GP Tax', 120, 30, 'informational', 'Definitional query for GP accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax return', 'General Accounting', 560, 50, 'transactional', 'High volume, generic tax service', 6, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp audit examples', 'GP Tax', 120, 30, 'informational', 'Specific informational query on audits', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting & tax services', 'GP Tax', 200, 40, 'transactional', 'Full-service offering intent', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant uk', 'Medical Expenses', 280, 40, 'transactional', 'National medical accounting service search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('leicester gp accountant', 'Location-Based', 140, 25, 'transactional', 'Leicester local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('find the gp near me', 'General Medical', 120, 30, 'informational', 'Medical practice search, off-topic', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant leicester', 'Location-Based', 140, 25, 'transactional', 'Leicester local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp glasgow', 'General Medical', 120, 30, 'informational', 'Medical admin query, off-topic', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant', 'GP Tax', 280, 35, 'transactional', 'Qualifier indicates comparison shopping', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('london gp accountant', 'Location-Based', 140, 30, 'transactional', 'London local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant newcastle', 'Location-Based', 140, 25, 'transactional', 'Newcastle medical accounting niche', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant manchester', 'Location-Based', 140, 25, 'transactional', 'Manchester-specific GP tax specialist', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant liverpool', 'Location-Based', 140, 25, 'transactional', 'Liverpool local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('glasgow gp accountant', 'Location-Based', 140, 25, 'transactional', 'Glasgow local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant advice', 'GP Tax', 200, 40, 'transactional', 'Seeking expert guidance', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant bristol', 'Location-Based', 140, 25, 'transactional', 'Bristol medical accounting niche', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant', 'General', 1500, 40, 'transactional', 'Primary target keyword', 100, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what is the best gp accountant', 'GP Tax', 120, 25, 'informational', 'High-intent informational query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('can an accountant become a doctor', 'Informational', 120, 20, 'informational', 'Off-topic informational query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('edinburgh gp accountant', 'Location-Based', 140, 25, 'transactional', 'Edinburgh local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant sheffield', 'Location-Based', 140, 25, 'transactional', 'Sheffield local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant financial planning', 'Financial Planning', 560, 40, 'transactional', 'Broad financial services query', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant cardiff', 'Location-Based', 140, 25, 'transactional', 'Cardiff local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant london', 'Location-Based', 140, 25, 'transactional', 'Competitive London market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('cardiff gp accountant', 'Location-Based', 140, 25, 'transactional', 'Cardiff local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant liverpool', 'Location-Based', 140, 25, 'transactional', 'Liverpool local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant payroll services', 'Payroll Services', 560, 40, 'transactional', 'Broad payroll services query', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant near me', 'Location-Based', 140, 25, 'transactional', 'High-intent local search query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant vat registration', 'VAT Services', 560, 40, 'transactional', 'Specific VAT service query', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant bradford', 'Location-Based', 140, 25, 'transactional', 'Bradford local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp bookkeeping', 'GP Tax', 560, 40, 'transactional', 'Specific GP bookkeeping service query', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant birmingham', 'Location-Based', 140, 20, 'transactional', 'High-intent Birmingham local query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('liverpool gp accountant', 'Location-Based', 140, 25, 'transactional', 'Liverpool local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp vat registration', 'VAT Services', 560, 40, 'transactional', 'Specific GP VAT service query', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
