-- Seed initial topic tree for medical niche
-- Generated by niche generator

INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant leeds', 'Location-Based', 140, 28, 'transactional', 'Leeds medical practice targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountants adviseurs', 'Location-Based', 50, 20, 'transactional', 'Dutch term, low UK volume', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant leeds', 'GP Tax', 140, 28, 'transactional', 'Leeds GP specific tax service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant accounting services', 'General Accounting', 800, 60, 'transactional', 'Generic, high competition', 20, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('specialist gp accountant', 'Private Practice', 200, 40, 'transactional', 'High-intent specialist search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant liverpool', 'Location-Based', 140, 28, 'transactional', 'Liverpool medical practice targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant near me', 'Location-Based', 560, 35, 'transactional', 'High local intent search', 21, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('glasgow gp accountant', 'Location-Based', 140, 28, 'transactional', 'Glasgow local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant payroll services', 'General Accounting', 560, 40, 'transactional', 'Payroll service offering', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what qualifications do i need to become an accountant in the uk', 'General Accounting', 120, 20, 'informational', 'Career advice query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp glasgow', 'Location-Based', 120, 20, 'informational', 'Patient registration, not accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant nottingham', 'Location-Based', 140, 28, 'transactional', 'Nottingham medical practice targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant fees', 'Pricing', 120, 30, 'transactional', 'Direct pricing research', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant financial planning', 'General Accounting', 560, 40, 'transactional', 'Financial planning service', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant cardiff', 'Location-Based', 140, 28, 'transactional', 'Cardiff local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('find the gp near me', 'Location-Based', 120, 20, 'informational', 'Patient search, not accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('nottingham gp accountant', 'Location-Based', 140, 28, 'transactional', 'Nottingham local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant birmingham', 'GP Tax', 140, 28, 'transactional', 'Birmingham GP specific tax service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax planning', 'GP Tax', 200, 40, 'transactional', 'Core GP tax service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant access', 'General Accounting', 50, 20, 'navigational', 'Ambiguous, possibly portal access', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting system', 'General Accounting', 50, 20, 'informational', 'Software or system query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('newcastle gp accountant', 'Location-Based', 140, 28, 'transactional', 'Newcastle local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('why use a gp accountant', 'Private Practice', 120, 20, 'informational', 'Persuasive informational content', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant bristol', 'Location-Based', 140, 28, 'transactional', 'Bristol local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant coventry', 'Location-Based', 140, 28, 'transactional', 'Coventry local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant sheffield', 'Location-Based', 140, 28, 'transactional', 'Sheffield local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant bristol', 'Location-Based', 140, 28, 'transactional', 'Bristol medical practice targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting services', 'General Accounting', 200, 40, 'transactional', 'General GP accounting offering', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant london', 'Location-Based', 140, 35, 'transactional', 'London market, higher competition', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant newcastle', 'Location-Based', 140, 28, 'transactional', 'Newcastle medical practice targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in cardiff', 'Location-Based', 120, 20, 'informational', 'Patient registration, not accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('coventry gp accountant', 'Location-Based', 140, 28, 'transactional', 'Coventry local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant uk', 'Private Practice', 560, 45, 'transactional', 'National GP accountant search', 11, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant london', 'Location-Based', 98, 30, 'transactional', 'London ''best'' comparison search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant glasgow', 'Location-Based', 140, 28, 'transactional', 'Glasgow medical practice targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp bookkeeping', 'General Accounting', 200, 40, 'transactional', 'GP specific bookkeeping service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant manchester', 'Location-Based', 140, 28, 'transactional', 'Manchester local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant', 'Private Practice', 140, 35, 'transactional', 'Comparison ''best'' search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp boyle accountants newry', 'Location-Based', 50, 20, 'navigational', 'Specific firm, Northern Ireland', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('local gp accountant', 'Location-Based', 140, 35, 'transactional', 'Localised service search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting software', 'General Accounting', 120, 30, 'informational', 'Software research query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant cardiff', 'Location-Based', 140, 28, 'transactional', 'Cardiff medical practice targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what is the best gp accountant', 'Private Practice', 120, 20, 'informational', 'Informational ''best'' comparison', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how much does a gp accountant cost', 'Pricing', 120, 22, 'informational', 'Direct cost research query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant cost', 'Pricing', 120, 30, 'transactional', 'Pricing research', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant bristol', 'GP Tax', 140, 28, 'transactional', 'Bristol GP specific tax service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to find a gp accountant', 'Private Practice', 120, 20, 'informational', 'How-to guide opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax advice', 'General Accounting', 560, 40, 'transactional', 'Generic tax advice service', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant manchester', 'Location-Based', 140, 28, 'transactional', 'Manchester medical practice targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('do i need a gp accountant', 'Private Practice', 120, 20, 'informational', 'Qualifying question for services', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('can an accountant become a doctor', 'General Accounting', 120, 20, 'informational', 'Off-topic career crossover', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in manchester', 'Location-Based', 120, 20, 'informational', 'Patient registration, not accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('leeds gp accountant', 'Location-Based', 140, 28, 'transactional', 'Leeds local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting', 'General Accounting', 800, 50, 'transactional', 'Core service term', 30, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant vat registration', 'General Accounting', 560, 40, 'transactional', 'VAT service offering', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant self assessment', 'General Accounting', 560, 40, 'transactional', 'Self assessment tax service', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant jobs', 'General Accounting', 120, 30, 'informational', 'Job search, not client search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant nottingham', 'Location-Based', 140, 28, 'transactional', 'Nottingham local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax advice', 'GP Tax', 200, 40, 'transactional', 'GP specific tax advice', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant near me', 'Location-Based', 140, 28, 'transactional', 'Local medical accountant search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp financial planning', 'Medical Expenses', 200, 40, 'transactional', 'GP wealth management service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant corporation tax', 'General Accounting', 560, 40, 'transactional', 'Corporation tax service', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax return', 'General Accounting', 560, 40, 'transactional', 'Tax return service', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant tax planning', 'General Accounting', 560, 40, 'transactional', 'Tax planning service', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('when to hire a gp accountant', 'Private Practice', 120, 20, 'informational', 'Timing and need query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('bristol gp accountant', 'Location-Based', 140, 28, 'transactional', 'Bristol local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax return', 'GP Tax', 200, 40, 'transactional', 'GP specific tax return service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant edinburgh', 'Location-Based', 140, 28, 'transactional', 'Edinburgh local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp payroll services', 'General Accounting', 200, 40, 'transactional', 'GP specific payroll service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in sheffield', 'Location-Based', 120, 20, 'informational', 'Patient registration, not accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp audit examples', 'General Accounting', 50, 20, 'informational', 'Niche informational query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp self assessment', 'GP Tax', 200, 40, 'transactional', 'GP self assessment service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant manchester', 'Location-Based', 98, 30, 'transactional', 'Manchester ''best'' comparison search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('leicester gp accountant', 'Location-Based', 140, 28, 'transactional', 'Leicester local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting meaning', 'General Accounting', 50, 20, 'informational', 'Definitional query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('manchester gp accountant', 'Location-Based', 140, 28, 'transactional', 'Manchester local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what is gp in accounting', 'General Accounting', 120, 20, 'informational', 'Definition of GP term', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('what does a gp accountant do', 'Private Practice', 120, 20, 'informational', 'Service explanation query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant birmingham', 'Location-Based', 140, 28, 'transactional', 'Birmingham local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('birmingham gp accountant', 'Location-Based', 140, 28, 'transactional', 'Birmingham local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant help', 'General Accounting', 120, 30, 'transactional', 'Support or assistance query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant manchester', 'GP Tax', 140, 28, 'transactional', 'Manchester GP specific tax service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountants schagen', 'Location-Based', 50, 20, 'navigational', 'Dutch term, low UK volume', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant services', 'General Accounting', 200, 40, 'transactional', 'General service offering', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant london', 'Location-Based', 140, 35, 'transactional', 'London medical practice targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant liverpool', 'Location-Based', 140, 28, 'transactional', 'Liverpool local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('glasgow gp jobs', 'Location-Based', 120, 30, 'informational', 'Job search, not client search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in liverpool', 'Location-Based', 120, 20, 'informational', 'Patient registration, not accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('best gp accountant birmingham', 'Location-Based', 98, 30, 'transactional', 'Birmingham ''best'' comparison search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to register with a gp in bristol', 'Location-Based', 120, 20, 'informational', 'Patient registration, not accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('cardiff gp accountant', 'Location-Based', 140, 28, 'transactional', 'Cardiff local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp vat registration', 'GP Tax', 200, 40, 'transactional', 'GP specific VAT service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('affordable gp accountant', 'Pricing', 120, 35, 'transactional', 'Price-sensitive search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how much is a gp accountant', 'Pricing', 120, 20, 'informational', 'Pricing research query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('accountant bookkeeping', 'General Accounting', 560, 40, 'transactional', 'Generic bookkeeping service', 16, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant uk', 'Private Practice', 140, 35, 'transactional', 'National medical accountant search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('glasgow gp near me', 'Location-Based', 120, 20, 'informational', 'Patient search, not accounting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant sheffield', 'Location-Based', 140, 28, 'transactional', 'Sheffield medical practice targeting', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant leeds', 'Location-Based', 140, 28, 'transactional', 'Leeds local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant leicester', 'Location-Based', 140, 28, 'transactional', 'Leicester local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('london gp accountant', 'Location-Based', 140, 35, 'transactional', 'London market, higher competition', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('how to choose a gp accountant', 'Private Practice', 120, 20, 'informational', 'Selection guide opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('liverpool gp accountant', 'Location-Based', 140, 28, 'transactional', 'Liverpool local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant', 'Private Practice', 800, 50, 'transactional', 'Primary target keyword', 30, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('edinburgh gp accountant', 'Location-Based', 140, 28, 'transactional', 'Edinburgh local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('sheffield gp accountant', 'Location-Based', 140, 28, 'transactional', 'Sheffield local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accounting & tax services', 'GP Tax', 120, 35, 'transactional', 'Combined service offering', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('medical accountant jobs near me', 'Location-Based', 120, 28, 'informational', 'Job search, not client search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp tax accountant london', 'GP Tax', 140, 35, 'transactional', 'London GP specific tax service', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('average accountant salary manchester', 'General Accounting', 120, 20, 'informational', 'Salary research, off-topic', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('bradford gp accountant', 'Location-Based', 140, 28, 'transactional', 'Bradford local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp corporation tax', 'GP Tax', 200, 40, 'transactional', 'GP specific corporation tax', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('experienced gp accountant', 'Private Practice', 120, 35, 'transactional', 'Experience-focused search', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant advice', 'General Accounting', 120, 35, 'transactional', 'Advice service query', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant glasgow', 'Location-Based', 140, 28, 'transactional', 'Glasgow local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant newcastle', 'Location-Based', 140, 28, 'transactional', 'Newcastle local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
INSERT INTO public.blog_topics_medical (keyword, category, search_volume, difficulty, intent, notes, priority, status)
VALUES ('gp accountant bradford', 'Location-Based', 140, 28, 'transactional', 'Bradford local market opportunity', 0, 'pending')
ON CONFLICT (keyword) DO NOTHING;
