-- Migration: 20260711000002_add_tranche_pilot_to_leads_source.sql
-- Tranche: pilot | new source keys: charities
-- Generated by optimisation_engine.ops.spinup_site.
--
-- ROLLBACK / previous constraint definition (repo-known as of generation;
-- RE-READ THE LIVE DEF before applying):
--   SELECT conname, pg_get_constraintdef(oid)
--   FROM pg_constraint WHERE conname LIKE '%source%' AND conrelid = 'leads'::regclass;
--   leads_source_valid: CHECK ((source = ANY (ARRAY['dentists', 'property', 'medical', 'solicitors', 'generalist', 'general', 'agency', 'agency-founder-finance', 'contractors-ir35', 'construction-cis'])) OR source IS NULL)
--
-- Strictly additive. Run manually via Supabase SQL (Management API).

BEGIN;

ALTER TABLE leads DROP CONSTRAINT IF EXISTS leads_source_valid;

ALTER TABLE leads ADD CONSTRAINT leads_source_valid
  CHECK (
    source IN (
      'dentists',
      'property',
      'medical',
      'solicitors',
      'generalist',
      'general',
      'agency',
      'agency-founder-finance',
      'contractors-ir35',
      'construction-cis',
      'test', -- present in the LIVE constraint (drift vs repo-known def); preserved on re-read 2026-07-11
      'charities'
    )
    OR source IS NULL
  );

COMMIT;

-- Verify after applying:
--   SELECT conname, pg_get_constraintdef(oid)
--   FROM pg_constraint WHERE conname = 'leads_source_valid';
